'use strict';

// ContactFlow Professional 1.2 — account vault, encrypted sync, Telegram Mini App + opt-in campaigns.
pageMeta.cloud=['حساب و Sync','ثبت‌نام، Recovery و همگام‌سازی رمزگذاری‌شده'];
pageMeta.telegram=['تلگرام و Mini App','Business Private Chat و مدیریت ربات'];

const PRO_CHUNK=5000;
const proState={token:sessionStorage.getItem('cf_pro_token')||'',key:null,vaultRaw:null,userSalt:null,username:sessionStorage.getItem('cf_pro_user')||'',syncing:false,lastCampaign:null};
const te=new TextEncoder(),td=new TextDecoder();
const b64=u8=>{let s='';for(let i=0;i<u8.length;i+=0x8000)s+=String.fromCharCode(...u8.subarray(i,i+0x8000));return btoa(s);};
const unb64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
const b64url=u8=>b64(u8).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');

function cloudUrl(){const configured=String(window.CONTACTFLOW_CONFIG?.apiBase||'').trim().replace(/\/$/,'');const explicit=($('cloud-url')?.value||$('auth-server-url')?.value||localStorage.getItem('cf_cloud_url')||configured||'').trim().replace(/\/$/,'');if(explicit)return explicit;const shell=['127.0.0.1','localhost','appassets.androidplatform.net'].includes(location.hostname);if(!shell&&(location.protocol==='http:'||location.protocol==='https:'))return location.origin;return'';}
function setProProgress(pct,label){$('sync-progress')?.classList.remove('hidden');if($('sync-pct'))$('sync-pct').textContent=`${Math.round(pct)}%`;if($('sync-bar'))$('sync-bar').style.width=`${Math.max(0,Math.min(100,pct))}%`;if($('sync-label'))$('sync-label').textContent=label;}
function setAccountUI(ok,detail=''){if(!$('account-pill'))return;$('account-pill').textContent=ok?'متصل':'Local';$('account-pill').className=`pill ${ok?'active':'queued'}`;$('account-state').textContent=ok?`ورود: ${proState.username}${detail?' • '+detail:''}`:'وارد نشده‌اید';$('account-badge').classList.toggle('offline',!ok);$('account-badge').querySelector('span').textContent=ok?proState.username:'Local';}
async function pbkdf2Bytes(password,salt,label,iters){const base=await crypto.subtle.importKey('raw',te.encode(`${label}|${password}`),'PBKDF2',false,['deriveBits']);return new Uint8Array(await crypto.subtle.deriveBits({name:'PBKDF2',salt,iterations:iters,hash:'SHA-256'},base,256));}
async function importAes(raw){return crypto.subtle.importKey('raw',raw,{name:'AES-GCM'},false,['encrypt','decrypt']);}
async function derivePassword(password,salt){const auth=await pbkdf2Bytes(password,salt,'contactflow-auth',180000),wrapRaw=await pbkdf2Bytes(password,salt,'contactflow-vault-wrap',260000);return {authProof:b64(auth),wrapKey:await importAes(wrapRaw)};}
async function deriveLegacy(password,salt){const auth=await pbkdf2Bytes(password,salt,'contactflow-auth',180000),enc=await pbkdf2Bytes(password,salt,'contactflow-encryption',260000);return {authProof:b64(auth),raw:enc,key:await importAes(enc)};}
async function deriveRecovery(code,salt){const proof=await pbkdf2Bytes(code,salt,'contactflow-recovery-proof',220000),wrapRaw=await pbkdf2Bytes(code,salt,'contactflow-recovery-wrap',300000);return {recoveryProof:b64(proof),wrapKey:await importAes(wrapRaw)};}
async function encryptBytes(raw,key){const iv=crypto.getRandomValues(new Uint8Array(12)),ct=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},key,raw));return {iv:b64(iv),data:b64(ct)};}
async function decryptBytes(payload,key){return new Uint8Array(await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(payload.iv)},key,unb64(payload.data)));}
async function wrapVault(raw,key){return JSON.stringify(await encryptBytes(raw,key));}
async function unwrapVault(wrap,key){const payload=typeof wrap==='string'?JSON.parse(wrap):wrap;return decryptBytes(payload,key);}
async function encryptObject(obj,key=proState.key){const iv=crypto.getRandomValues(new Uint8Array(12)),data=te.encode(JSON.stringify(obj)),ct=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},key,data));return {iv:b64(iv),data:b64(ct)};}
async function decryptObject(payload,key=proState.key){const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(payload.iv)},key,unb64(payload.data));return JSON.parse(td.decode(plain));}
async function api(path,opts={}){const base=cloudUrl();if(!base)throw new Error('سرور مرکزی حساب تنظیم نشده است. در تنظیمات Server URL را وارد کنید.');const headers={'Content-Type':'application/json',...(opts.headers||{})};if(proState.token)headers.Authorization=`Bearer ${proState.token}`;const r=await fetch(base+path,{...opts,headers});let body=null;try{body=await r.json();}catch{}if(!r.ok){if(r.status===404&&path.startsWith('/api/'))throw new Error('API حساب روی این آدرس پیدا نشد؛ آدرس UI محلی 127.0.0.1 را به‌عنوان Cloud Server وارد نکنید.');throw new Error(body?.error||`HTTP ${r.status}`);}return body;}
function setAuthGate(show){$('auth-gate')?.classList.toggle('hidden',!show);}function accountFields(){const gate=!$('auth-gate')?.classList.contains('hidden');return {username:(gate?$('auth-user')?.value:$('cloud-user')?.value||'').trim(),password:gate?$('auth-pass')?.value:($('cloud-pass')?.value||'')}}function mirrorAccountFields(username=''){if($('cloud-user')&&username)$('cloud-user').value=username;if($('auth-user')&&username)$('auth-user').value=username;}function rememberSession(out,username){proState.token=out.token;proState.username=username;sessionStorage.setItem('cf_pro_token',out.token);sessionStorage.setItem('cf_pro_user',username);mirrorAccountFields(username);setAccountUI(true);setAuthGate(false);}
function showRecovery(code){for(const el of [$('recovery-box'),$('auth-recovery-box')]){if(!el)continue;el.classList.remove('hidden');el.innerHTML=`<strong>Recovery Code — فقط یک‌بار نمایش داده می‌شود</strong><br><code dir="ltr">${escapeHtml(code)}</code><br><small>این کد را آفلاین نگه دارید. بدون رمز یا Recovery Code، E2EE قابل بازیابی نیست.</small>`;}}

async function registerAccount(){
  try{const base=cloudUrl(),{username,password}=accountFields();if(!base||username.length<3||password.length<12)throw new Error('نام کاربری حداقل 3 کاراکتر، رمز حداقل 12 کاراکتر و اتصال سرور مرکزی لازم است.');localStorage.setItem('cf_cloud_url',base);
    const salt=crypto.getRandomValues(new Uint8Array(16)),recoverySalt=crypto.getRandomValues(new Uint8Array(16)),vaultRaw=crypto.getRandomValues(new Uint8Array(32)),recoveryCode=b64url(crypto.getRandomValues(new Uint8Array(24)));const pwd=await derivePassword(password,salt),rec=await deriveRecovery(recoveryCode,recoverySalt),passwordWrap=await wrapVault(vaultRaw,pwd.wrapKey),recoveryWrap=await wrapVault(vaultRaw,rec.wrapKey);
    const out=await api('/api/v1/auth/register',{method:'POST',body:JSON.stringify({username,salt:b64(salt),authProof:pwd.authProof,passwordWrap,recoverySalt:b64(recoverySalt),recoveryProof:rec.recoveryProof,recoveryWrap})});proState.vaultRaw=vaultRaw;proState.key=await importAes(vaultRaw);proState.userSalt=salt;rememberSession(out,username);showRecovery(recoveryCode);toast('حساب ساخته شد. Recovery Code را ذخیره کنید.', 'good',8000);await pushSnapshot();
  }catch(e){toast(e.message,'bad',8000);}
}
async function loginAccount(){
  try{const base=cloudUrl(),{username,password}=accountFields();if(!base||!username||!password)throw new Error('نام کاربری، رمز و اتصال سرور مرکزی لازم است.');localStorage.setItem('cf_cloud_url',base);const info=await api(`/api/v1/auth/salt?username=${encodeURIComponent(username)}`),salt=unb64(info.salt);
    if(info.passwordWrap){const pwd=await derivePassword(password,salt),out=await api('/api/v1/auth/login',{method:'POST',body:JSON.stringify({username,authProof:pwd.authProof})}),raw=await unwrapVault(out.passwordWrap||info.passwordWrap,pwd.wrapKey);proState.vaultRaw=raw;proState.key=await importAes(raw);proState.userSalt=salt;rememberSession(out,username);}else{const legacy=await deriveLegacy(password,salt),out=await api('/api/v1/auth/login',{method:'POST',body:JSON.stringify({username,authProof:legacy.authProof})});proState.vaultRaw=legacy.raw;proState.key=legacy.key;proState.userSalt=salt;rememberSession(out,username);toast('حساب قدیمی وارد شد؛ برای فعال‌سازی Recovery رمز را یک‌بار تغییر دهید.','good',7000);}toast('ورود موفق بود.');await Promise.all([refreshCloudStatus(),refreshCloudFiles()]);
  }catch(e){toast(`ورود ناموفق: ${e.message}`,'bad',8000);}
}
async function logoutAccount(){try{if(proState.token)await api('/api/v1/auth/logout',{method:'POST',body:'{}'});}catch{}proState.token='';proState.key=null;proState.vaultRaw=null;proState.userSalt=null;proState.username='';sessionStorage.removeItem('cf_pro_token');sessionStorage.removeItem('cf_pro_user');setAccountUI(false);setAuthGate(true);toast('از حساب خارج شدید.');}
async function changeUsername(){if(!proState.token){toast('ابتدا وارد شوید.','bad');return;}const username=prompt('نام کاربری جدید:');if(!username)return;try{const r=await api('/api/v1/auth/change-username',{method:'POST',body:JSON.stringify({username})});proState.username=r.username;$('cloud-user').value=r.username;sessionStorage.setItem('cf_pro_user',r.username);setAccountUI(true);toast('نام کاربری تغییر کرد.');}catch(e){toast(e.message,'bad');}}
async function changePassword(){if(!proState.token||!proState.vaultRaw){toast('ابتدا با رمز فعلی وارد شوید.','bad');return;}const password=prompt('رمز جدید (حداقل 12 کاراکتر):');if(!password||password.length<12){if(password)toast('رمز کوتاه است.','bad');return;}try{const salt=crypto.getRandomValues(new Uint8Array(16)),pwd=await derivePassword(password,salt),passwordWrap=await wrapVault(proState.vaultRaw,pwd.wrapKey),out=await api('/api/v1/auth/change-password',{method:'POST',body:JSON.stringify({salt:b64(salt),authProof:pwd.authProof,passwordWrap})});proState.userSalt=salt;proState.token=out.token;sessionStorage.setItem('cf_pro_token',out.token);$('cloud-pass').value='';toast('رمز تغییر کرد؛ Vault و Backupهای ابری قابل دسترسی باقی ماندند.');}catch(e){toast(`تغییر رمز: ${e.message}`,'bad');}}
async function recoverAccount(){const username=accountFields().username||prompt('نام کاربری حساب:');if(!username)return;const recoveryCode=prompt('Recovery Code:');if(!recoveryCode)return;const newPassword=prompt('رمز جدید (حداقل 12 کاراکتر):');if(!newPassword||newPassword.length<12){toast('رمز جدید معتبر نیست.','bad');return;}try{const ri=await api(`/api/v1/auth/recovery-info?username=${encodeURIComponent(username)}`),rec=await deriveRecovery(recoveryCode,unb64(ri.recoverySalt)),vaultRaw=await unwrapVault(ri.recoveryWrap,rec.wrapKey),salt=crypto.getRandomValues(new Uint8Array(16)),pwd=await derivePassword(newPassword,salt),passwordWrap=await wrapVault(vaultRaw,pwd.wrapKey),out=await api('/api/v1/auth/recover',{method:'POST',body:JSON.stringify({username,recoveryProof:rec.recoveryProof,salt:b64(salt),authProof:pwd.authProof,passwordWrap})});proState.vaultRaw=vaultRaw;proState.key=await importAes(vaultRaw);proState.userSalt=salt;rememberSession(out,username);toast('حساب با Recovery Code بازیابی شد. اکنون می‌توانید Snapshot را دریافت کنید.');}catch(e){toast(`Recovery ناموفق: ${e.message}`,'bad',9000);}}


const CLOUD_FILE_CHUNK=4*1024*1024;
async function archiveCloudFile(blob,kind='artifact',name='file'){
  if(!proState.token||!proState.key||!navigator.onLine)return null;
  try{const begin=await api('/api/v1/files/begin',{method:'POST',body:JSON.stringify({name,mime:blob.type||'application/octet-stream',kind,size:blob.size})}),id=begin.fileId;let part=0;
    for(let off=0;off<blob.size;off+=CLOUD_FILE_CHUNK){const raw=new Uint8Array(await blob.slice(off,Math.min(blob.size,off+CLOUD_FILE_CHUNK)).arrayBuffer()),enc=await encryptBytes(raw,proState.key);await api(`/api/v1/files/${id}/parts/${part}`,{method:'PUT',body:JSON.stringify(enc)});part++;}
    await api(`/api/v1/files/${id}/complete`,{method:'POST',body:JSON.stringify({parts:part})});await refreshCloudFiles();return id;
  }catch(e){toast(`آرشیو ابری ${name}: ${e.message}`,'bad',7000);return null;}
}
window.ContactFlowProArchiveFile=(blob,kind,name)=>archiveCloudFile(blob,kind,name||blob.name||'file');
async function refreshCloudFiles(){const el=$('cloud-files-list');if(!el||!proState.token)return;try{const r=await api('/api/v1/files');el.innerHTML=r.items.length?r.items.map(x=>`<div class="export-row"><div><strong>${escapeHtml(x.name)}</strong><small>${escapeHtml(x.kind)} • ${formatBytes(x.size)} • ${new Date(x.createdAt).toLocaleString('fa-IR')}</small></div><div class="button-row"><button class="download-btn cloud-file-download" data-id="${escapeHtml(x.id)}" data-name="${escapeHtml(x.name)}" data-mime="${escapeHtml(x.mime||'application/octet-stream')}">دریافت</button><button class="danger-btn cloud-file-delete" data-id="${escapeHtml(x.id)}">حذف</button></div></div>`).join(''):'<div class="empty-state compact">فایل ابری ثبت نشده است.</div>';document.querySelectorAll('.cloud-file-download').forEach(b=>b.onclick=()=>downloadCloudFile(b.dataset.id,b.dataset.name,b.dataset.mime));document.querySelectorAll('.cloud-file-delete').forEach(b=>b.onclick=()=>deleteCloudFile(b.dataset.id));}catch(e){el.innerHTML=`<div class="empty-state compact">${escapeHtml(e.message)}</div>`;}}
async function downloadCloudFile(id,name,mime){if(!proState.key)return toast('برای رمزگشایی ابتدا با رمز حساب وارد شوید.','bad');try{const list=await api('/api/v1/files'),meta=list.items.find(x=>x.id===id);if(!meta)throw new Error('فایل پیدا نشد.');const chunks=[];for(let i=0;i<meta.parts;i++){const enc=await api(`/api/v1/files/${id}/parts/${i}`),raw=await decryptBytes(enc,proState.key);chunks.push(raw);}const blob=new Blob(chunks,{type:mime||meta.mime||'application/octet-stream'});if(window.ContactFlowAndroid?.saveFile){const u8=new Uint8Array(await blob.arrayBuffer());let bin='';for(let i=0;i<u8.length;i+=0x8000)bin+=String.fromCharCode(...u8.subarray(i,i+0x8000));window.ContactFlowAndroid.saveFile(name,blob.type,btoa(bin));}else{const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),3000);}toast('فایل ابری رمزگشایی و آماده شد.');}catch(e){toast(`دریافت فایل: ${e.message}`,'bad',8000);}}
async function deleteCloudFile(id){if(!confirm('فایل ابری حذف شود؟'))return;try{await api(`/api/v1/files/${id}`,{method:'DELETE'});await refreshCloudFiles();}catch(e){toast(e.message,'bad');}}
async function refreshCloudStatus(){try{const r=await api('/api/v1/me');proState.username=r.username;setAccountUI(true,`Snapshotها: ${r.snapshots||0}`);const latest=await api('/api/v1/snapshots/latest');$('sync-last').textContent=latest?.snapshot?`آخرین Cloud: ${new Date(latest.snapshot.createdAt).toLocaleString('fa-IR')}`:'هنوز Snapshot ابری ندارید.';$('sync-pill').textContent='Online';$('sync-pill').className='pill active';}catch(e){$('sync-pill').textContent='Offline';$('sync-pill').className='pill queued';if(proState.token)toast(`Cloud: ${e.message}`,'bad');}}
async function collectSmallStores(){const out={version:APP_VERSION,createdAt:new Date().toISOString(),imports:[],meta:[],settings:[],artifacts:[]};for(const name of ['imports','meta','settings','artifacts']){const tx=state.db.transaction(name,'readonly');out[name]=await reqP(tx.objectStore(name).getAll());}return out;}
async function getContactBatch(afterKey=null,limit=PRO_CHUNK){const tx=state.db.transaction('contacts','readonly'),store=tx.objectStore('contacts'),range=afterKey?IDBKeyRange.lowerBound(afterKey,true):null;return reqP(store.getAll(range,limit));}
async function pushSnapshot(){if(proState.syncing)return;if(!proState.token||!proState.key){toast('ابتدا وارد حساب شوید.','bad');return;}proState.syncing=true;$('sync-pill').textContent='Uploading';$('sync-pill').className='pill queued';try{const stats=await getStats(),begin=await api('/api/v1/snapshots',{method:'POST',body:JSON.stringify({clientVersion:APP_VERSION,total:stats.total||0})}),id=begin.snapshotId;let part=0,processed=0;const small=await encryptObject({kind:'metadata',payload:await collectSmallStores()});await api(`/api/v1/snapshots/${id}/parts/${part}`,{method:'PUT',body:JSON.stringify({...small,kind:'metadata',count:0})});part++;let last=null;while(true){const rows=await getContactBatch(last,PRO_CHUNK);if(!rows.length)break;last=rows[rows.length-1].phone;const enc=await encryptObject({kind:'contacts',rows});await api(`/api/v1/snapshots/${id}/parts/${part}`,{method:'PUT',body:JSON.stringify({...enc,kind:'contacts',count:rows.length})});processed+=rows.length;part++;setProProgress(stats.total?processed/stats.total*96:50,`ارسال ${fmt.format(processed)} مخاطب`);await new Promise(r=>setTimeout(r,0));}await api(`/api/v1/snapshots/${id}/finish`,{method:'POST',body:JSON.stringify({parts:part,total:processed})});localStorage.setItem('cf_last_synced_revision',localStorage.getItem('cf_local_revision')||'');localStorage.setItem('cf_last_sync_at',new Date().toISOString());setProProgress(100,'Sync کامل شد');$('sync-last').textContent=`آخرین Sync: ${new Date().toLocaleString('fa-IR')}`;$('sync-pill').textContent='Synced';$('sync-pill').className='pill active';toast(`Snapshot ${fmt.format(processed)} مخاطب + تاریخچه فایل/خروجی ثبت شد.`);}catch(e){$('sync-pill').textContent='Error';toast(`Sync ناموفق: ${e.message}`,'bad',9000);}finally{proState.syncing=false;}}
async function clearForRestore(){const tx=state.db.transaction(['contacts','imports','meta','settings','artifacts'],'readwrite');for(const n of ['contacts','imports','meta','settings','artifacts'])tx.objectStore(n).clear();await txDone(tx);}
async function applySnapshotObject(obj){if(obj.kind==='metadata'){const p=obj.payload||{};for(const name of ['imports','meta','settings','artifacts']){const tx=state.db.transaction(name,'readwrite'),st=tx.objectStore(name);for(const row of p[name]||[])st.put(row);await txDone(tx);}return 0;}if(obj.kind==='contacts'){const r=await addContactsBatch(obj.rows||[]);return r.added;}throw new Error('نوع قطعه ناشناخته است.');}
async function applySnapshotParts(parts,fetchPart){if(!parts)throw new Error('Snapshot بدون قطعه است.');const firstEnc=await fetchPart(0),firstObj=await decryptObject(firstEnc);await clearForRestore();let contacts=await applySnapshotObject(firstObj);for(let i=1;i<parts;i++){setProProgress(i/parts*95,`Restore قطعه ${i+1} از ${parts}`);contacts+=await applySnapshotObject(await decryptObject(await fetchPart(i)));}touchRevision();setProProgress(100,'Restore کامل شد');await initData();return contacts;}
async function pullSnapshot(){if(!proState.token||!proState.key){toast('ابتدا وارد حساب شوید.','bad');return;}if(!confirm('آخرین Snapshot ابری جایگزین دیتابیس محلی شود؟'))return;proState.syncing=true;try{const latest=await api('/api/v1/snapshots/latest');if(!latest.snapshot)throw new Error('Snapshot ابری وجود ندارد.');const id=latest.snapshot.id,n=await applySnapshotParts(latest.snapshot.parts,i=>api(`/api/v1/snapshots/${id}/parts/${i}`));toast(`${fmt.format(n)} مخاطب از Cloud بازیابی شد.`);await refreshCloudStatus();}catch(e){toast(`Restore ناموفق: ${e.message}`,'bad',9000);}finally{proState.syncing=false;}}
async function* cursorStoreBatches(){let last=null;while(true){const rows=await getContactBatch(last,PRO_CHUNK);if(!rows.length)break;last=rows[rows.length-1].phone;yield rows;}}
async function localBackup(){const password=$('cloud-pass').value;if(password.length<12){toast('برای Backup رمز حداقل 12 کاراکتر وارد کنید.','bad');return;}try{const salt=crypto.getRandomValues(new Uint8Array(16)),legacy=await deriveLegacy(password,salt),header={format:'ContactFlowBackup',version:2,appVersion:APP_VERSION,salt:b64(salt),createdAt:new Date().toISOString()};let writer=null,parts=[];if('showSaveFilePicker'in window){const h=await showSaveFilePicker({suggestedName:`ContactFlow_${new Date().toISOString().slice(0,10)}.cfbackup`});writer=await h.createWritable();await writer.write(JSON.stringify(header)+'\n');}else parts.push(JSON.stringify(header)+'\n');const emit=async obj=>{const line=JSON.stringify(await encryptObject(obj,legacy.key))+'\n';if(writer)await writer.write(line);else parts.push(line);};await emit({kind:'metadata',payload:await collectSmallStores()});let count=0;for await(const rows of cursorStoreBatches()){await emit({kind:'contacts',rows});count+=rows.length;setProProgress(50,`Backup ${fmt.format(count)} مخاطب`);}if(writer)await writer.close();else{const blob=new Blob(parts,{type:'application/x-contactflow-backup'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`ContactFlow_${new Date().toISOString().slice(0,10)}.cfbackup`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),3000);}toast(`Backup ${fmt.format(count)} مخاطب ساخته شد.`);}catch(e){if(e.name!=='AbortError')toast(`Backup ناموفق: ${e.message}`,'bad',8000);}}
async function* textLines(file){const reader=file.stream().getReader(),dec=new TextDecoder();let buf='';while(true){const {value,done}=await reader.read();if(done)break;buf+=dec.decode(value,{stream:true});let p;while((p=buf.indexOf('\n'))>=0){yield buf.slice(0,p);buf=buf.slice(p+1);}}buf+=dec.decode();if(buf.trim())yield buf;}
async function restoreLocalBackup(file){const password=$('cloud-pass').value;if(!password){toast('رمز Backup را وارد کنید.','bad');return;}if(!confirm('Backup جایگزین دیتابیس محلی شود؟'))return;try{const it=textLines(file)[Symbol.asyncIterator](),first=await it.next();if(first.done)throw new Error('فایل خالی است.');const header=JSON.parse(first.value);if(header.format!=='ContactFlowBackup')throw new Error('فرمت Backup معتبر نیست.');const legacy=await deriveLegacy(password,unb64(header.salt)),second=await it.next();if(second.done)throw new Error('Backup ناقص است.');const firstObj=await decryptObject(JSON.parse(second.value),legacy.key);await clearForRestore();let count=await applySnapshotObject(firstObj),i=1;while(true){const n=await it.next();if(n.done)break;if(!n.value.trim())continue;count+=await applySnapshotObject(await decryptObject(JSON.parse(n.value),legacy.key));i++;setProProgress(60,`Restore ${fmt.format(count)} • قطعه ${i}`);}touchRevision();await initData();setProProgress(100,'Restore کامل شد');toast(`${fmt.format(count)} مخاطب بازیابی شد.`);}catch(e){toast(`Restore ناموفق: ${e.message}`,'bad',9000);}}

async function tgApi(path,opts={}){return api(path,opts);}
async function tgSaveConfig(){const botToken=$('tg-bot-token').value.trim(),adminId=$('tg-admin-id').value.trim(),miniAppUrl=$('tg-miniapp-url').value.trim(),requiredChats=$('tg-required-chats').value.trim();if(!proState.token){toast('ابتدا وارد حساب ContactFlow شوید.','bad');return;}try{const r=await tgApi('/api/v1/telegram/config',{method:'POST',body:JSON.stringify({botToken,adminId,miniAppUrl,requiredChats})});$('tg-bot-token').value='';toast(`ربات @${r.bot.username||r.bot.id} ذخیره شد. Token در Server رمزگذاری شد.`);await tgHealth();}catch(e){toast(`تنظیم ربات: ${e.message}`,'bad',9000);}}
async function tgHealth(){try{const r=await tgApi('/api/v1/telegram/health');$('tg-pro-state').textContent=r.configured?(r.bot?.username?`@${r.bot.username}`:'Bot آماده است'):'Bot Token تنظیم نشده';$('tg-pro-pill').textContent=r.configured?'Ready':'No Token';$('tg-pro-pill').className=`pill ${r.configured?'active':'queued'}`;if(r.adminId)$('tg-admin-id').value=r.adminId;if(r.miniAppUrl)$('tg-miniapp-url').value=r.miniAppUrl;if(r.requiredChats)$('tg-required-chats').value=r.requiredChats;}catch(e){$('tg-pro-state').textContent=e.message;$('tg-pro-pill').textContent='Offline';$('tg-pro-pill').className='pill queued';}}
async function tgSyncUsers(){try{const r=await tgApi('/api/v1/telegram/sync-updates',{method:'POST',body:'{}'});toast(`${fmt.format(r.updated||0)} Update پردازش شد.`);await Promise.all([tgRefreshSubs(),tgRefreshSuppression()]);}catch(e){toast(`Telegram: ${e.message}`,'bad',8000);}}
async function tgRefreshSubs(){try{const r=await tgApi('/api/v1/telegram/subscribers');$('tg-subs-count').textContent=`${fmt.format(r.items.length)} کاربر`;$('tg-subs-table').innerHTML=r.items.length?r.items.map(x=>`<tr><td dir="ltr">${escapeHtml(x.chatId)}</td><td>${escapeHtml(x.firstName||'—')}</td><td dir="ltr">${escapeHtml(x.username||'—')}</td><td>${new Date(x.lastSeen).toLocaleString('fa-IR')}</td></tr>`).join(''):'<tr><td colspan="4">Subscriber وجود ندارد.</td></tr>';}catch(e){toast(`لیست Telegram: ${e.message}`,'bad');}}

async function tgExportSubs(){try{const r=await tgApi('/api/v1/telegram/subscribers');const rows=[['chat_id','first_name','username','last_bot_interaction']];for(const x of r.items)rows.push([x.chatId,x.firstName||'',x.username||'',x.lastSeen||'']);const esc=v=>'"'+String(v??'').replaceAll('"','""')+'"';const csv='\ufeff'+rows.map(r=>r.map(esc).join(',')).join('\r\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'});const name=`telegram_optin_${new Date().toISOString().slice(0,10)}.csv`;if(window.ContactFlowAndroid?.saveFile){const u8=new Uint8Array(await blob.arrayBuffer());let bin='';for(let i=0;i<u8.length;i+=0x8000)bin+=String.fromCharCode(...u8.subarray(i,i+0x8000));window.ContactFlowAndroid.saveFile(name,blob.type,btoa(bin));}else{const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),2000);}await addArtifact({type:'telegram-export',name,count:r.items.length});toast(`خروجی ${fmt.format(r.items.length)} مخاطب opt-in ساخته شد.`);}catch(e){toast(`خروجی Telegram: ${e.message}`,'bad');}}

async function tgRefreshBusiness(){try{const r=await tgApi('/api/v1/telegram/business-connections');$('tg-business-table').innerHTML=r.items.length?r.items.map(x=>`<tr><td dir="ltr">${escapeHtml(x.connectionId)}</td><td dir="ltr">${escapeHtml(x.businessUserId||'—')}</td><td>${x.enabled?'فعال':'غیرفعال'}</td><td>${new Date(x.lastSeen).toLocaleString('fa-IR')}</td></tr>`).join(''):'<tr><td colspan="4">Business Connection ثبت نشده است.</td></tr>';const sel=$('tg-business-connection');if(sel){const cur=sel.value;sel.innerHTML='<option value="">انتخاب Connection</option>'+r.items.filter(x=>x.enabled).map(x=>`<option value="${escapeHtml(x.connectionId)}">${escapeHtml(x.businessUserId||x.connectionId)}</option>`).join('');if(r.items.some(x=>x.connectionId===cur))sel.value=cur;}}catch(e){toast(`Business Connections: ${e.message}`,'bad');}}
async function tgLoadBusinessChats(){const connectionId=$('tg-business-connection')?.value||'';if(!connectionId)return toast('Business Connection را انتخاب کنید.','bad');try{const r=await tgApi(`/api/v1/telegram/business-chats?connectionId=${encodeURIComponent(connectionId)}`);$('tg-business-chats').innerHTML=r.items.length?r.items.map(x=>`<tr><td><input class="tg-bchat-check" type="checkbox" data-id="${escapeHtml(x.chatId)}"></td><td dir="ltr">${escapeHtml(x.chatId)}</td><td>${escapeHtml(x.firstName||'—')}</td><td dir="ltr">${escapeHtml(x.username||'—')}</td><td>${new Date(x.lastSeen).toLocaleString('fa-IR')}</td></tr>`).join(''):'<tr><td colspan="5">چت Business موجود نیست.</td></tr>';}catch(e){toast(`Business Chats: ${e.message}`,'bad');}}
async function tgBusinessSend(){const connectionId=$('tg-business-connection')?.value||'',text=$('tg-business-message')?.value.trim()||'',linkText=$('tg-business-link-text')?.value.trim()||'',linkUrl=$('tg-business-link-url')?.value.trim()||'',chatIds=[...document.querySelectorAll('.tg-bchat-check:checked')].map(x=>x.dataset.id);if(!connectionId||!text||!chatIds.length)return toast('Connection، متن و چت‌های مقصد را انتخاب کنید.','bad');if(!confirm(`ارسال از طرف حساب Business به ${chatIds.length} چت موجود انجام شود؟`))return;try{const r=await tgApi('/api/v1/telegram/business-send',{method:'POST',body:JSON.stringify({connectionId,text,linkText,linkUrl,chatIds})});if(linkUrl)await addArtifact({type:'business-link',name:linkText||'لینک Business',url:linkUrl,count:r.sent});toast(`ارسال Business: ${fmt.format(r.sent)} موفق • ${fmt.format(r.failed)} ناموفق.`);}catch(e){toast(`Business Send: ${e.message}`,'bad',8000);}}
async function tgBusinessExport(){const connectionId=$('tg-business-connection')?.value||'';if(!connectionId)return toast('Connection را انتخاب کنید.','bad');try{const r=await tgApi(`/api/v1/telegram/business-chats?connectionId=${encodeURIComponent(connectionId)}`),rows=[['connection_id','chat_id','peer_user_id','first_name','username','last_business_interaction'],...r.items.map(x=>[x.connectionId,x.chatId,x.peerUserId||'',x.firstName||'',x.username||'',x.lastSeen||''])],esc=v=>'"'+String(v??'').replaceAll('"','""')+'"',blob=new Blob(['\ufeff'+rows.map(a=>a.map(esc).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'});appendExport(blob,`telegram_business_${Date.now()}.csv`,r.items.length,'telegram-business-export');toast('CSV چت‌های Business ساخته شد.');}catch(e){toast(e.message,'bad');}}

async function tgRefreshSuppression(){try{const [s,a]=await Promise.all([tgApi('/api/v1/telegram/suppression'),tgApi('/api/v1/telegram/ad-requests')]);$('tg-suppression-count').textContent=`${fmt.format(s.items.length)} عدم دریافت`;$('tg-suppression-table').innerHTML=s.items.length?s.items.map(x=>`<tr><td dir="ltr">${escapeHtml(x.chatId)}</td><td>عدم دریافت</td><td><button class="ghost-btn tg-enable" data-id="${escapeHtml(x.chatId)}">فعال‌سازی مجدد</button></td></tr>`).join(''):'<tr><td colspan="3">لیست خالی است.</td></tr>';document.querySelectorAll('.tg-enable').forEach(b=>b.onclick=()=>tgEnable(b.dataset.id));$('tg-adrequests').innerHTML=a.items.length?a.items.map(x=>`<div class="export-row"><div><strong>${escapeHtml(x.firstName||x.username||x.chatId)}</strong><small>${new Date(x.createdAt).toLocaleString('fa-IR')} • ${escapeHtml(x.chatId)}</small></div><span class="pill queued">${escapeHtml(x.status)}</span></div>`).join(''):'<div class="empty-state compact">درخواستی ثبت نشده است.</div>';}catch(e){toast(`Suppression: ${e.message}`,'bad');}}
async function tgEnable(id){if(!confirm('دریافت تبلیغ برای این کاربر دوباره فعال شود؟'))return;try{await tgApi(`/api/v1/telegram/suppression/${encodeURIComponent(id)}/enable`,{method:'POST',body:'{}'});await tgRefreshSuppression();toast('دریافت مجدد فعال شد.');}catch(e){toast(e.message,'bad');}}
async function tgCampaign(){const text=$('tg-message').value.trim(),linkText=$('tg-link-text').value.trim(),linkUrl=$('tg-link-url').value.trim();if(!text){toast('متن پیام را وارد کنید.','bad');return;}if(!confirm('ارسال فقط برای کاربران opt-in و خارج از Suppression List انجام شود؟'))return;try{const r=await tgApi('/api/v1/telegram/campaigns',{method:'POST',body:JSON.stringify({text,linkText,linkUrl})});if(linkUrl)await addArtifact({type:'link',name:linkText||'لینک تبلیغ',url:linkUrl,count:r.recipients});proState.lastCampaign=r.id;$('tg-campaign-status').textContent=`Queued #${r.id}`;$('tg-campaign-status').className='pill queued';toast(`کمپین برای ${fmt.format(r.recipients)} مخاطب رضایت‌داده در صف قرار گرفت.`);pollCampaign();}catch(e){toast(`کمپین ساخته نشد: ${e.message}`,'bad',8000);}}
async function pollCampaign(){if(!proState.lastCampaign)return;try{const r=await tgApi(`/api/v1/telegram/campaigns/${proState.lastCampaign}`);$('tg-campaign-status').textContent=`${r.status} • ${r.sent}/${r.total}`;$('tg-campaign-status').className=`pill ${r.status==='done'?'active':'queued'}`;if(!['done','failed'].includes(r.status))setTimeout(pollCampaign,2500);}catch{}}

async function maybeMiniAppAuth(){const tg=window.Telegram?.WebApp;if(!tg?.initData)return;try{tg.ready();tg.expand();document.documentElement.dataset.telegram='1';const owner=new URLSearchParams(location.search).get('owner');if(!owner)return;const base=cloudUrl();if(!base)return;const r=await fetch(base+'/api/v1/telegram/miniapp-auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({owner,initData:tg.initData})}),b=await r.json();if(!r.ok)throw new Error(b.error||`HTTP ${r.status}`);rememberSession(b,b.username);$('cloud-user').value=b.username;toast(`Mini App: ادمین Telegram تأیید شد. برای Cloud Restore رمز حساب را یک‌بار وارد کنید.`);}catch(e){toast(`Mini App Auth: ${e.message}`,'bad',8000);}}
async function maybeAutoSync(){if(localStorage.getItem('cf_auto_sync')!=='1'||!proState.token||!proState.key||!navigator.onLine||proState.syncing)return;const rev=localStorage.getItem('cf_local_revision')||'',last=localStorage.getItem('cf_last_synced_revision')||'';if(rev!==last)pushSnapshot();}

function saveCentralServer(){const raw=($('auth-server-url')?.value||$('cloud-url')?.value||'').trim().replace(/\/$/,'');if(!raw)return toast('Server URL را وارد کنید.','bad');try{const u=new URL(raw);if(!['http:','https:'].includes(u.protocol))throw new Error();localStorage.setItem('cf_cloud_url',u.toString().replace(/\/$/,''));if($('cloud-url'))$('cloud-url').value=localStorage.getItem('cf_cloud_url');if($('auth-server-url'))$('auth-server-url').value=localStorage.getItem('cf_cloud_url');$('auth-server-state').textContent='سرور مرکزی ذخیره شد.';toast('آدرس سرور مرکزی ذخیره شد.');}catch{toast('Server URL معتبر نیست.','bad');}}
async function testCentralServer(){try{const base=cloudUrl();if(!base)throw new Error('Server URL تنظیم نشده است.');const r=await fetch(base+'/health',{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const b=await r.json();$('auth-server-state').textContent=`سرور آماده است • ${b.version||'ContactFlow'}`;toast('اتصال سرور مرکزی موفق است.');}catch(e){$('auth-server-state').textContent=e.message;toast(`سرور مرکزی: ${e.message}`,'bad',7000);}}
function copyGateCredentials(){if($('cloud-user'))$('cloud-user').value=$('auth-user')?.value||'';if($('cloud-pass'))$('cloud-pass').value=$('auth-pass')?.value||'';}
function bindProfessional(){
  const configured=localStorage.getItem('cf_cloud_url')||String(window.CONTACTFLOW_CONFIG?.apiBase||'');if($('cloud-url'))$('cloud-url').value=configured;if($('auth-server-url'))$('auth-server-url').value=configured;if($('cloud-user'))$('cloud-user').value=proState.username||'';if($('auth-user'))$('auth-user').value=proState.username||'';$('auto-sync').checked=localStorage.getItem('cf_auto_sync')==='1';setAccountUI(!!proState.token,proState.token?'برای Sync رمز را دوباره وارد کنید':'');setAuthGate(!proState.key);
  if($('auth-server-state'))$('auth-server-state').textContent=cloudUrl()?'سرور مرکزی آماده ورود/ثبت‌نام است.':'سرور مرکزی تنظیم نشده؛ در تنظیم پیشرفته Server URL را وارد کنید.';
  $('auth-register')?.addEventListener('click',()=>{copyGateCredentials();registerAccount();});$('auth-login')?.addEventListener('click',()=>{copyGateCredentials();loginAccount();});$('auth-recover')?.addEventListener('click',()=>{copyGateCredentials();recoverAccount();});$('auth-save-server')?.addEventListener('click',saveCentralServer);$('save-cloud-server')?.addEventListener('click',saveCentralServer);$('test-cloud-server')?.addEventListener('click',testCentralServer);
  $('cloud-register').addEventListener('click',registerAccount);$('cloud-files-refresh')?.addEventListener('click',refreshCloudFiles);$('cloud-login').addEventListener('click',loginAccount);$('cloud-logout').addEventListener('click',logoutAccount);$('change-username')?.addEventListener('click',changeUsername);$('change-password')?.addEventListener('click',changePassword);$('forgot-password')?.addEventListener('click',recoverAccount);$('sync-status').addEventListener('click',refreshCloudStatus);$('sync-push').addEventListener('click',pushSnapshot);$('sync-pull').addEventListener('click',pullSnapshot);$('auto-sync').addEventListener('change',e=>localStorage.setItem('cf_auto_sync',e.target.checked?'1':'0'));$('backup-encrypted').addEventListener('click',localBackup);$('restore-file').addEventListener('change',e=>e.target.files[0]&&restoreLocalBackup(e.target.files[0]));
  $('tg-config-save')?.addEventListener('click',tgSaveConfig);$('tg-test')?.addEventListener('click',tgHealth);$('tg-sync-users')?.addEventListener('click',tgSyncUsers);$('tg-refresh-subs')?.addEventListener('click',tgRefreshSubs);$('tg-export-subs')?.addEventListener('click',tgExportSubs);$('tg-refresh-suppression')?.addEventListener('click',tgRefreshSuppression);$('tg-refresh-business')?.addEventListener('click',tgRefreshBusiness);$('tg-business-load-chats')?.addEventListener('click',tgLoadBusinessChats);$('tg-business-send')?.addEventListener('click',tgBusinessSend);$('tg-business-export')?.addEventListener('click',tgBusinessExport);$('tg-send-campaign')?.addEventListener('click',tgCampaign);
  document.querySelectorAll('[data-page="cloud"]').forEach(x=>x.addEventListener('click',()=>setTimeout(refreshCloudStatus,0)));document.querySelectorAll('[data-page="telegram"]').forEach(x=>x.addEventListener('click',()=>setTimeout(()=>{tgHealth();tgRefreshSubs();tgRefreshSuppression();},0)));window.addEventListener('online',()=>setTimeout(maybeAutoSync,1000));setInterval(maybeAutoSync,5*60*1000);maybeMiniAppAuth();
}
setTimeout(bindProfessional,0);
