plugins {
    id 'com.android.application'
}

android {
    namespace 'ir.contactflow.personal'
    compileSdk 36

    defaultConfig {
        applicationId 'ir.contactflow.personal'
        minSdk 21
        targetSdk 36
        versionCode 20001
        versionName '2.0.0-alpha.1'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
