'use strict';

const http=require('http');
const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const {DatabaseSync}=require('node:sqlite');

const PORT=Number(process.env.PORT||8787);
const HOST=process.env.HOST||'127.0.0.1';
const DATA_DIR=path.resolve(process.env.DATA_DIR||path.join(__dirname,'data'));
const DB_PATH=path.join(DATA_DIR,'contactflow.db');
const PUBLIC_DIR=path.resolve(process.env.PUBLIC_DIR||path.join(__dirname,'..'));
const CORS_ORIGIN=process.env.CORS_ORIGIN||'*';
const SESSION_DAYS=Math.max(1,Number(process.env.SESSION_DAYS||30));
const MAX_BODY=15*1024*1024;
fs.mkdirSync(DATA_DIR,{recursive:true});

function loadServerSecret(){
  if(process.env.CONTACTFLOW_SERVER_SECRET)return crypto.createHash('sha256').update(process.env.CONTACTFLOW_SERVER_SECRET).digest();
  const f=path.join(DATA_DIR,'.server_secret');
  if(fs.existsSync(f))return Buffer.from(fs.readFileSync(f,'utf8').trim(),'base64');
  const k=crypto.randomBytes(32);fs.writeFileSync(f,k.toString('base64'),{mode:0o600});return k;
}
const SERVER_SECRET=loadServerSecret();
const db=new DatabaseSync(DB_PATH);
db.exec(`PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY,username TEXT UNIQUE NOT NULL,user_salt TEXT NOT NULL,auth_salt TEXT NOT NULL,auth_hash TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sessions(id INTEGER PRIMARY KEY,user_id INTEGER NOT NULL,token_hash TEXT UNIQUE NOT NULL,expires_at TEXT NOT NULL,created_at TEXT NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS snapshots(id TEXT PRIMARY KEY,user_id INTEGER NOT NULL,status TEXT NOT NULL,client_version TEXT,declared_total INTEGER DEFAULT 0,parts INTEGER DEFAULT 0,total INTEGER DEFAULT 0,created_at TEXT NOT NULL,finished_at TEXT,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS snapshot_parts(snapshot_id TEXT NOT NULL,part_no INTEGER NOT NULL,iv TEXT NOT NULL,data TEXT NOT NULL,kind TEXT NOT NULL,count INTEGER DEFAULT 0,PRIMARY KEY(snapshot_id,part_no),FOREIGN KEY(snapshot_id) REFERENCES snapshots(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS user_settings(user_id INTEGER NOT NULL,key TEXT NOT NULL,value TEXT,PRIMARY KEY(user_id,key),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS user_files(id TEXT PRIMARY KEY,user_id INTEGER NOT NULL,name TEXT NOT NULL,mime TEXT,kind TEXT,size INTEGER DEFAULT 0,parts INTEGER DEFAULT 0,status TEXT NOT NULL,created_at TEXT NOT NULL,finished_at TEXT,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS user_file_parts(file_id TEXT NOT NULL,part_no INTEGER NOT NULL,iv TEXT NOT NULL,data TEXT NOT NULL,PRIMARY KEY(file_id,part_no),FOREIGN KEY(file_id) REFERENCES user_files(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS telegram_subscribers(user_id INTEGER NOT NULL,chat_id TEXT NOT NULL,first_name TEXT,username TEXT,last_seen TEXT NOT NULL,opted_in INTEGER NOT NULL DEFAULT 0,suppressed INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(user_id,chat_id),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS telegram_business_connections(user_id INTEGER NOT NULL,connection_id TEXT NOT NULL,business_user_id TEXT,enabled INTEGER NOT NULL DEFAULT 1,last_seen TEXT NOT NULL,PRIMARY KEY(user_id,connection_id),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS telegram_business_chats(user_id INTEGER NOT NULL,connection_id TEXT NOT NULL,chat_id TEXT NOT NULL,peer_user_id TEXT,first_name TEXT,username TEXT,last_seen TEXT NOT NULL,PRIMARY KEY(user_id,connection_id,chat_id),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS ad_requests(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,chat_id TEXT NOT NULL,first_name TEXT,username TEXT,status TEXT NOT NULL DEFAULT 'new',created_at TEXT NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS campaigns(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,text TEXT NOT NULL,link_text TEXT,link_url TEXT,status TEXT NOT NULL,total INTEGER DEFAULT 0,sent INTEGER DEFAULT 0,failed INTEGER DEFAULT 0,created_at TEXT NOT NULL,finished_at TEXT,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS campaign_recipients(id INTEGER PRIMARY KEY AUTOINCREMENT,campaign_id INTEGER NOT NULL,chat_id TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'queued',error TEXT,FOREIGN KEY(campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS idx_snapshots_user_created ON snapshots(user_id,created_at DESC);
CREATE INDEX IF NOT EXISTS idx_campaign_recipients_status ON campaign_recipients(status,campaign_id);
CREATE INDEX IF NOT EXISTS idx_ad_requests_user ON ad_requests(user_id,created_at DESC);`);
function ensureColumn(table,col,ddl){const cols=db.prepare(`PRAGMA table_info(${table})`).all().map(x=>x.name);if(!cols.includes(col))db.exec(`ALTER TABLE ${table} ADD COLUMN ${ddl}`);}
ensureColumn('users','password_wrap','password_wrap TEXT');
ensureColumn('users','recovery_salt','recovery_salt TEXT');
ensureColumn('users','recovery_hash','recovery_hash TEXT');
ensureColumn('users','recovery_wrap','recovery_wrap TEXT');
ensureColumn('telegram_subscribers','suppressed','suppressed INTEGER NOT NULL DEFAULT 0');
ensureColumn('campaigns','link_text','link_text TEXT');
ensureColumn('campaigns','link_url','link_url TEXT');
ensureColumn('campaigns','content_hash','content_hash TEXT');

const now=()=>new Date().toISOString();
const sha=s=>crypto.createHash('sha256').update(String(s)).digest('hex');
const randomToken=(bytes=32)=>crypto.randomBytes(bytes).toString('base64url');
const json=(res,status,obj)=>{const body=Buffer.from(JSON.stringify(obj));res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Content-Length':body.length,'Access-Control-Allow-Origin':CORS_ORIGIN,'Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Allow-Methods':'GET,POST,PUT,DELETE,OPTIONS','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(body);};
function cleanUsername(v){v=String(v||'').trim().toLowerCase();if(!/^[a-z0-9_.-]{3,50}$/.test(v))throw Object.assign(new Error('نام کاربری فقط حروف انگلیسی، عدد، نقطه، خط تیره و زیرخط؛ 3 تا 50 کاراکتر.'),{status:400});return v;}
function scryptHash(proof,salt){return crypto.scryptSync(String(proof),Buffer.from(salt,'base64'),32,{N:16384,r:8,p:1}).toString('base64');}
function issueSession(userId){const token=randomToken(),hash=sha(token),exp=new Date(Date.now()+SESSION_DAYS*86400000).toISOString();db.prepare('INSERT INTO sessions(user_id,token_hash,expires_at,created_at) VALUES(?,?,?,?)').run(userId,hash,exp,now());return token;}
function auth(req){const raw=String(req.headers.authorization||'');if(!raw.startsWith('Bearer '))return null;const token=raw.slice(7),row=db.prepare(`SELECT u.id,u.username FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>?`).get(sha(token),now());return row||null;}
async function readBody(req){let n=0,chunks=[];for await(const c of req){n+=c.length;if(n>MAX_BODY)throw Object.assign(new Error('درخواست بیش از حد بزرگ است.'),{status:413});chunks.push(c);}if(!chunks.length)return {};try{return JSON.parse(Buffer.concat(chunks).toString('utf8'));}catch{throw Object.assign(new Error('JSON نامعتبر است.'),{status:400});}}
function pruneSessions(){db.prepare('DELETE FROM sessions WHERE expires_at<=?').run(now());}
function requireAuth(req,res){const u=auth(req);if(!u){json(res,401,{error:'نیاز به ورود دارد.'});return null;}return u;}
function getSetting(uid,key,def=''){return db.prepare('SELECT value FROM user_settings WHERE user_id=? AND key=?').get(uid,key)?.value??def;}
function setSetting(uid,key,value){db.prepare('INSERT INTO user_settings(user_id,key,value) VALUES(?,?,?) ON CONFLICT(user_id,key) DO UPDATE SET value=excluded.value').run(uid,key,String(value));}
function encryptSecret(value){const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',SERVER_SECRET,iv);const ct=Buffer.concat([cipher.update(String(value),'utf8'),cipher.final()]),tag=cipher.getAuthTag();return [iv,tag,ct].map(x=>x.toString('base64url')).join('.');}
function decryptSecret(value){if(!value)return'';const [i,t,c]=String(value).split('.');const d=crypto.createDecipheriv('aes-256-gcm',SERVER_SECRET,Buffer.from(i,'base64url'));d.setAuthTag(Buffer.from(t,'base64url'));return Buffer.concat([d.update(Buffer.from(c,'base64url')),d.final()]).toString('utf8');}
function safeUrl(v){if(!v)return'';let u;try{u=new URL(String(v));}catch{throw Object.assign(new Error('URL معتبر نیست.'),{status:400});}if(!['https:','http:'].includes(u.protocol))throw Object.assign(new Error('URL باید http/https باشد.'),{status:400});return u.toString();}

function telegramToken(uid){return decryptSecret(getSetting(uid,'telegram_token_enc',''));}
async function telegramWithToken(token,method,payload={}){if(!token)throw Object.assign(new Error('Bot Token تنظیم نشده است.'),{status:503});const r=await fetch(`https://api.telegram.org/bot${token}/${method}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const b=await r.json();if(!b.ok){const e=new Error(b.description||'Telegram API error');e.telegram=b;throw e;}return b.result;}
async function telegram(uid,method,payload={}){return telegramWithToken(telegramToken(uid),method,payload);}
function inlineKeyboard(c){const rows=[];if(c.link_url)rows.push([{text:c.link_text||'مشاهده تبلیغ',url:c.link_url}]);rows.push([{text:'تبلیغ بیاد ✅',callback_data:'cf_keep'},{text:'تبلیغ نیاد ❌',callback_data:'cf_stop'}]);rows.push([{text:'من هم تبلیغ می‌خواهم',callback_data:'cf_ad_request'}]);return {inline_keyboard:rows};}
function timingEqHex(a,b){try{const aa=Buffer.from(String(a),'hex'),bb=Buffer.from(String(b),'hex');return aa.length===bb.length&&crypto.timingSafeEqual(aa,bb);}catch{return false;}}
function validateMiniAppData(initData,token,maxAgeSec=3600){
  const p=new URLSearchParams(String(initData||'')),hash=p.get('hash');if(!hash)return null;p.delete('hash');p.delete('signature');
  const arr=[];for(const [k,v] of [...p.entries()].sort(([a],[b])=>a.localeCompare(b)))arr.push(`${k}=${v}`);const data=arr.join('\n');
  const secret=crypto.createHmac('sha256','WebAppData').update(token).digest();const expected=crypto.createHmac('sha256',secret).update(data).digest('hex');if(!timingEqHex(hash,expected))return null;
  const authDate=Number(p.get('auth_date')||0);if(!authDate||Math.abs(Date.now()/1000-authDate)>maxAgeSec)return null;
  try{return {user:JSON.parse(p.get('user')||'null'),queryId:p.get('query_id')||''};}catch{return null;}
}
async function membershipState(uid,userId){const chats=getSetting(uid,'telegram_required_chats','').split(',').map(x=>x.trim()).filter(Boolean);if(!chats.length)return {ok:true,missing:[]};const missing=[];for(const chat of chats){try{const m=await telegram(uid,'getChatMember',{chat_id:chat,user_id:Number(userId)});if(['left','kicked'].includes(m.status))missing.push(chat);}catch{missing.push(chat);}}return {ok:missing.length===0,missing};}

const loginRate=new Map();
function rateOkay(req){const ip=req.socket.remoteAddress||'x',t=Date.now(),a=(loginRate.get(ip)||[]).filter(x=>t-x<60000);if(a.length>=20)return false;a.push(t);loginRate.set(ip,a);return true;}

async function handleTelegramUpdates(uid){
  const token=telegramToken(uid);if(!token)throw Object.assign(new Error('Bot Token تنظیم نشده است.'),{status:503});let offset=Number(getSetting(uid,'telegram_offset','0'));
  const updates=await telegramWithToken(token,'getUpdates',{offset,limit:100,timeout:0,allowed_updates:['message','callback_query','business_connection','business_message','edited_business_message']});let changed=0;
  const upsert=db.prepare(`INSERT INTO telegram_subscribers(user_id,chat_id,first_name,username,last_seen,opted_in,suppressed) VALUES(?,?,?,?,?,?,?) ON CONFLICT(user_id,chat_id) DO UPDATE SET first_name=excluded.first_name,username=excluded.username,last_seen=excluded.last_seen,opted_in=excluded.opted_in,suppressed=CASE WHEN telegram_subscribers.suppressed=1 THEN 1 ELSE excluded.suppressed END`);
  for(const u of updates){
    offset=Math.max(offset,Number(u.update_id)+1);
    if(u.business_connection){const bc=u.business_connection;db.prepare(`INSERT INTO telegram_business_connections(user_id,connection_id,business_user_id,enabled,last_seen) VALUES(?,?,?,?,?) ON CONFLICT(user_id,connection_id) DO UPDATE SET business_user_id=excluded.business_user_id,enabled=excluded.enabled,last_seen=excluded.last_seen`).run(uid,String(bc.id||bc.connection_id||''),String(bc.user?.id||bc.user_id||''),bc.is_enabled===false||bc.disabled?0:1,now());changed++;continue;}
    const bm=u.business_message||u.edited_business_message;if(bm&&bm.business_connection_id&&bm.chat?.type==='private'){const peer=bm.from||bm.chat||{};db.prepare(`INSERT INTO telegram_business_chats(user_id,connection_id,chat_id,peer_user_id,first_name,username,last_seen) VALUES(?,?,?,?,?,?,?) ON CONFLICT(user_id,connection_id,chat_id) DO UPDATE SET peer_user_id=excluded.peer_user_id,first_name=excluded.first_name,username=excluded.username,last_seen=excluded.last_seen`).run(uid,String(bm.business_connection_id),String(bm.chat.id),String(peer.id||''),String(peer.first_name||bm.chat.first_name||''),String(peer.username||bm.chat.username||''),new Date((bm.date||Date.now()/1000)*1000).toISOString());changed++;continue;}
    if(u.callback_query){const q=u.callback_query,from=q.from,chatId=String(q.message?.chat?.id||from?.id||'');if(!from||!chatId)continue;const current=db.prepare('SELECT opted_in,suppressed FROM telegram_subscribers WHERE user_id=? AND chat_id=?').get(uid,chatId)||{opted_in:1,suppressed:0};let opted=current.opted_in,supp=current.suppressed;let answer='';if(q.data==='cf_stop'){opted=0;supp=1;answer='دیگر پیام تبلیغاتی دریافت نمی‌کنید.';}else if(q.data==='cf_keep'){opted=1;supp=0;answer='دریافت پیام‌های مجاز فعال می‌ماند.';}else if(q.data==='cf_ad_request'){db.prepare("INSERT INTO ad_requests(user_id,chat_id,first_name,username,status,created_at) VALUES(?,?,?,?, 'new',?)").run(uid,chatId,String(from.first_name||''),String(from.username||''),now());answer='درخواست تبلیغ شما ثبت شد.';}else if(q.data==='cf_subscribe'){opted=1;supp=0;answer='دریافت پیام فعال شد.';}upsert.run(uid,chatId,String(from.first_name||''),String(from.username||''),now(),opted,supp);try{await telegramWithToken(token,'answerCallbackQuery',{callback_query_id:q.id,text:answer||'ثبت شد'});}catch{}changed++;continue;}
    const msg=u.message;if(msg&&msg.chat?.type==='private'&&msg.from){const chatId=String(msg.chat.id),text=String(msg.text||'').trim().toLowerCase(),existing=db.prepare('SELECT opted_in,suppressed FROM telegram_subscribers WHERE user_id=? AND chat_id=?').get(uid,chatId)||{opted_in:0,suppressed:0};let opted=existing.opted_in,supp=existing.suppressed;if(/^\/(start|subscribe)(\s|$)/.test(text)){const ms=await membershipState(uid,msg.from.id);if(ms.ok){opted=1;supp=0;try{await telegramWithToken(token,'sendMessage',{chat_id:chatId,text:'عضویت شما برای دریافت پیام‌های مجاز فعال شد.',reply_markup:{inline_keyboard:[[{text:'باز کردن پنل',web_app:{url:getSetting(uid,'telegram_miniapp_url','')}}]].filter(r=>r[0].web_app.url)}});}catch{}}else{opted=0;try{await telegramWithToken(token,'sendMessage',{chat_id:chatId,text:`برای استفاده ابتدا عضو شوید: ${ms.missing.join(' ، ')}`});}catch{}}}if(/^\/(stop|unsubscribe)(\s|$)/.test(text)){opted=0;supp=1;}upsert.run(uid,chatId,String(msg.from.first_name||''),String(msg.from.username||''),new Date((msg.date||Date.now()/1000)*1000).toISOString(),opted,supp);changed++;}
  }
  setSetting(uid,'telegram_offset',offset);return {updated:changed,offset};
}

async function apiRoute(req,res,url){
  const method=req.method;
  if(method==='OPTIONS'){res.writeHead(204,{'Access-Control-Allow-Origin':CORS_ORIGIN,'Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Allow-Methods':'GET,POST,PUT,DELETE,OPTIONS'});return res.end();}
  if(url.pathname==='/health')return json(res,200,{ok:true,service:'ContactFlow Professional Server',version:'1.2.0',time:now()});

  if(url.pathname==='/api/v1/auth/salt'&&method==='GET'){
    const username=cleanUsername(url.searchParams.get('username'));const row=db.prepare('SELECT user_salt,password_wrap FROM users WHERE username=?').get(username);if(!row)return json(res,404,{error:'حساب پیدا نشد.'});return json(res,200,{salt:row.user_salt,passwordWrap:row.password_wrap||null,legacy:!row.password_wrap});
  }
  if(url.pathname==='/api/v1/auth/recovery-info'&&method==='GET'){
    const username=cleanUsername(url.searchParams.get('username'));const row=db.prepare('SELECT recovery_salt,recovery_wrap FROM users WHERE username=?').get(username);if(!row||!row.recovery_salt||!row.recovery_wrap)return json(res,404,{error:'Recovery برای این حساب فعال نیست.'});return json(res,200,{recoverySalt:row.recovery_salt,recoveryWrap:row.recovery_wrap});
  }
  if(url.pathname==='/api/v1/auth/register'&&method==='POST'){
    if(!rateOkay(req))return json(res,429,{error:'تلاش بیش از حد؛ کمی بعد دوباره امتحان کنید.'});const b=await readBody(req),username=cleanUsername(b.username);if(!b.salt||!b.authProof||!b.passwordWrap||!b.recoverySalt||!b.recoveryProof||!b.recoveryWrap)return json(res,400,{error:'اطلاعات ثبت‌نام کامل نیست.'});
    const authSalt=crypto.randomBytes(16).toString('base64'),authHash=scryptHash(b.authProof,authSalt);let info;try{info=db.prepare('INSERT INTO users(username,user_salt,auth_salt,auth_hash,password_wrap,recovery_salt,recovery_hash,recovery_wrap,created_at) VALUES(?,?,?,?,?,?,?,?,?)').run(username,b.salt,authSalt,authHash,String(b.passwordWrap),String(b.recoverySalt),sha(b.recoveryProof),String(b.recoveryWrap),now());}catch(e){if(String(e).includes('UNIQUE'))return json(res,409,{error:'این نام کاربری قبلاً وجود دارد.'});throw e;}const token=issueSession(Number(info.lastInsertRowid));return json(res,201,{token,username});
  }
  if(url.pathname==='/api/v1/auth/login'&&method==='POST'){
    if(!rateOkay(req))return json(res,429,{error:'تلاش بیش از حد؛ کمی بعد دوباره امتحان کنید.'});const b=await readBody(req),username=cleanUsername(b.username),row=db.prepare('SELECT * FROM users WHERE username=?').get(username);if(!row)return json(res,401,{error:'نام کاربری یا رمز نادرست است.'});const got=Buffer.from(scryptHash(b.authProof||'',row.auth_salt),'base64'),want=Buffer.from(row.auth_hash,'base64');if(got.length!==want.length||!crypto.timingSafeEqual(got,want))return json(res,401,{error:'نام کاربری یا رمز نادرست است.'});const token=issueSession(row.id);return json(res,200,{token,username,passwordWrap:row.password_wrap||null,legacy:!row.password_wrap});
  }
  if(url.pathname==='/api/v1/auth/recover'&&method==='POST'){
    if(!rateOkay(req))return json(res,429,{error:'تلاش بیش از حد.'});const b=await readBody(req),username=cleanUsername(b.username),row=db.prepare('SELECT * FROM users WHERE username=?').get(username);if(!row||!row.recovery_hash||sha(b.recoveryProof||'')!==row.recovery_hash)return json(res,401,{error:'Recovery Code نادرست است.'});if(!b.salt||!b.authProof||!b.passwordWrap)return json(res,400,{error:'رمز جدید کامل نیست.'});const authSalt=crypto.randomBytes(16).toString('base64'),authHash=scryptHash(b.authProof,authSalt);db.prepare('UPDATE users SET user_salt=?,auth_salt=?,auth_hash=?,password_wrap=? WHERE id=?').run(b.salt,authSalt,authHash,String(b.passwordWrap),row.id);db.prepare('DELETE FROM sessions WHERE user_id=?').run(row.id);const token=issueSession(row.id);return json(res,200,{token,username});
  }
  if(url.pathname==='/api/v1/telegram/miniapp-auth'&&method==='POST'){
    const b=await readBody(req),owner=cleanUsername(b.owner),row=db.prepare('SELECT id,username FROM users WHERE username=?').get(owner);if(!row)return json(res,404,{error:'مالک Mini App پیدا نشد.'});const token=telegramToken(row.id),validated=validateMiniAppData(b.initData,token);if(!validated?.user)return json(res,401,{error:'Telegram initData نامعتبر یا منقضی است.'});const adminId=getSetting(row.id,'telegram_admin_id','');if(String(validated.user.id)!==String(adminId))return json(res,403,{error:'این Telegram ID ادمین نیست.'});const ms=await membershipState(row.id,validated.user.id);if(!ms.ok)return json(res,403,{error:'عضویت کانال‌های لازم تکمیل نیست.',missing:ms.missing});const session=issueSession(row.id);return json(res,200,{token:session,username:row.username,telegramUser:validated.user});
  }

  if(url.pathname==='/api/v1/auth/logout'&&method==='POST'){const raw=String(req.headers.authorization||'');if(raw.startsWith('Bearer '))db.prepare('DELETE FROM sessions WHERE token_hash=?').run(sha(raw.slice(7)));return json(res,200,{ok:true});}
  const user=requireAuth(req,res);if(!user)return;

  if(url.pathname==='/api/v1/me'&&method==='GET'){const c=db.prepare("SELECT count(*) c FROM snapshots WHERE user_id=? AND status='complete'").get(user.id).c;const a=db.prepare('SELECT count(*) c FROM telegram_subscribers WHERE user_id=? AND opted_in=1 AND suppressed=0').get(user.id).c;return json(res,200,{username:user.username,snapshots:c,telegramOptIn:a});}
  if(url.pathname==='/api/v1/files'&&method==='GET'){const rows=db.prepare("SELECT id,name,mime,kind,size,parts,created_at createdAt,finished_at finishedAt FROM user_files WHERE user_id=? AND status='complete' ORDER BY created_at DESC LIMIT 500").all(user.id);return json(res,200,{items:rows});}
  if(url.pathname==='/api/v1/files/begin'&&method==='POST'){const b=await readBody(req),name=String(b.name||'file').slice(0,240),mime=String(b.mime||'application/octet-stream').slice(0,120),kind=String(b.kind||'artifact').slice(0,40),size=Math.max(0,Number(b.size)||0);if(size>1024*1024*1024)return json(res,413,{error:'حداکثر اندازه هر فایل ابری 1GB است.'});const id=randomToken(18);db.prepare("INSERT INTO user_files(id,user_id,name,mime,kind,size,status,created_at) VALUES(?,?,?,?,?,?,'uploading',?)").run(id,user.id,name,mime,kind,size,now());return json(res,201,{fileId:id});}
  let fm=url.pathname.match(/^\/api\/v1\/files\/([A-Za-z0-9_-]+)\/parts\/(\d+)$/);if(fm&&method==='PUT'){const row=db.prepare('SELECT id FROM user_files WHERE id=? AND user_id=?').get(fm[1],user.id);if(!row)return json(res,404,{error:'فایل پیدا نشد.'});const b=await readBody(req);if(!b.iv||!b.data)return json(res,400,{error:'Chunk ناقص است.'});db.prepare('INSERT INTO user_file_parts(file_id,part_no,iv,data) VALUES(?,?,?,?) ON CONFLICT(file_id,part_no) DO UPDATE SET iv=excluded.iv,data=excluded.data').run(fm[1],Number(fm[2]),String(b.iv),String(b.data));return json(res,200,{ok:true});}
  if(fm&&method==='GET'){const own=db.prepare('SELECT id FROM user_files WHERE id=? AND user_id=?').get(fm[1],user.id);if(!own)return json(res,404,{error:'فایل پیدا نشد.'});const part=db.prepare('SELECT iv,data FROM user_file_parts WHERE file_id=? AND part_no=?').get(fm[1],Number(fm[2]));if(!part)return json(res,404,{error:'Chunk پیدا نشد.'});return json(res,200,part);}
  fm=url.pathname.match(/^\/api\/v1\/files\/([A-Za-z0-9_-]+)\/complete$/);if(fm&&method==='POST'){const own=db.prepare('SELECT id FROM user_files WHERE id=? AND user_id=?').get(fm[1],user.id);if(!own)return json(res,404,{error:'فایل پیدا نشد.'});const b=await readBody(req),parts=Math.max(0,Number(b.parts)||0),actual=db.prepare('SELECT count(*) c FROM user_file_parts WHERE file_id=?').get(fm[1]).c;if(actual!==parts)return json(res,400,{error:'تعداد Chunkها کامل نیست.'});db.prepare("UPDATE user_files SET parts=?,status='complete',finished_at=? WHERE id=?").run(parts,now(),fm[1]);return json(res,200,{ok:true});}
  fm=url.pathname.match(/^\/api\/v1\/files\/([A-Za-z0-9_-]+)$/);if(fm&&method==='DELETE'){const r=db.prepare('DELETE FROM user_files WHERE id=? AND user_id=?').run(fm[1],user.id);return json(res,r.changes?200:404,r.changes?{ok:true}:{error:'فایل پیدا نشد.'});}
  if(url.pathname==='/api/v1/auth/change-username'&&method==='POST'){const b=await readBody(req),newUsername=cleanUsername(b.username);try{db.prepare('UPDATE users SET username=? WHERE id=?').run(newUsername,user.id);}catch(e){if(String(e).includes('UNIQUE'))return json(res,409,{error:'نام کاربری قبلاً استفاده شده است.'});throw e;}return json(res,200,{username:newUsername});}
  if(url.pathname==='/api/v1/auth/change-password'&&method==='POST'){const b=await readBody(req);if(!b.salt||!b.authProof||!b.passwordWrap)return json(res,400,{error:'اطلاعات رمز جدید کامل نیست.'});const authSalt=crypto.randomBytes(16).toString('base64'),authHash=scryptHash(b.authProof,authSalt);db.prepare('UPDATE users SET user_salt=?,auth_salt=?,auth_hash=?,password_wrap=? WHERE id=?').run(b.salt,authSalt,authHash,String(b.passwordWrap),user.id);db.prepare('DELETE FROM sessions WHERE user_id=?').run(user.id);const token=issueSession(user.id);return json(res,200,{token});}

  if(url.pathname==='/api/v1/snapshots'&&method==='POST'){const b=await readBody(req),id=crypto.randomUUID();db.prepare('INSERT INTO snapshots(id,user_id,status,client_version,declared_total,created_at) VALUES(?,?,?,?,?,?)').run(id,user.id,'uploading',String(b.clientVersion||''),Number(b.total||0),now());return json(res,201,{snapshotId:id});}
  let m=url.pathname.match(/^\/api\/v1\/snapshots\/([0-9a-f-]+)\/parts\/(\d+)$/i);
  if(m&&method==='PUT'){const snap=db.prepare('SELECT id FROM snapshots WHERE id=? AND user_id=? AND status=?').get(m[1],user.id,'uploading');if(!snap)return json(res,404,{error:'Snapshot فعال پیدا نشد.'});const b=await readBody(req);if(!b.iv||!b.data||!['metadata','contacts'].includes(b.kind))return json(res,400,{error:'قطعه Snapshot نامعتبر است.'});db.prepare('INSERT OR REPLACE INTO snapshot_parts(snapshot_id,part_no,iv,data,kind,count) VALUES(?,?,?,?,?,?)').run(m[1],Number(m[2]),b.iv,b.data,b.kind,Number(b.count||0));return json(res,200,{ok:true});}
  m=url.pathname.match(/^\/api\/v1\/snapshots\/([0-9a-f-]+)\/finish$/i);
  if(m&&method==='POST'){const b=await readBody(req),snap=db.prepare('SELECT id FROM snapshots WHERE id=? AND user_id=?').get(m[1],user.id);if(!snap)return json(res,404,{error:'Snapshot پیدا نشد.'});const actual=db.prepare('SELECT count(*) c,coalesce(sum(count),0) total FROM snapshot_parts WHERE snapshot_id=?').get(m[1]);if(actual.c!==Number(b.parts))return json(res,409,{error:'تعداد قطعه‌ها کامل نیست.'});db.prepare("UPDATE snapshots SET status='complete',parts=?,total=?,finished_at=? WHERE id=?").run(actual.c,actual.total,now(),m[1]);const old=db.prepare("SELECT id FROM snapshots WHERE user_id=? AND status='complete' ORDER BY created_at DESC LIMIT -1 OFFSET 5").all(user.id);for(const x of old)db.prepare('DELETE FROM snapshots WHERE id=?').run(x.id);return json(res,200,{ok:true,parts:actual.c,total:actual.total});}
  if(url.pathname==='/api/v1/snapshots/latest'&&method==='GET'){const s=db.prepare("SELECT id,parts,total,created_at createdAt,finished_at finishedAt,client_version clientVersion FROM snapshots WHERE user_id=? AND status='complete' ORDER BY created_at DESC LIMIT 1").get(user.id);return json(res,200,{snapshot:s||null});}
  m=url.pathname.match(/^\/api\/v1\/snapshots\/([0-9a-f-]+)\/parts\/(\d+)$/i);
  if(m&&method==='GET'){const p=db.prepare('SELECT sp.iv,sp.data,sp.kind,sp.count FROM snapshot_parts sp JOIN snapshots s ON s.id=sp.snapshot_id WHERE sp.snapshot_id=? AND sp.part_no=? AND s.user_id=?').get(m[1],Number(m[2]),user.id);if(!p)return json(res,404,{error:'قطعه پیدا نشد.'});return json(res,200,p);}

  if(url.pathname==='/api/v1/telegram/config'&&method==='POST'){const b=await readBody(req);if(!/^\d{5,}:[A-Za-z0-9_-]{20,}$/.test(String(b.botToken||'')))return json(res,400,{error:'Bot Token معتبر نیست.'});if(!/^\d+$/.test(String(b.adminId||'')))return json(res,400,{error:'Admin ID باید عددی باشد.'});const token=String(b.botToken),me=await telegramWithToken(token,'getMe',{}),mini=b.miniAppUrl?safeUrl(b.miniAppUrl):'';setSetting(user.id,'telegram_token_enc',encryptSecret(token));setSetting(user.id,'telegram_admin_id',String(b.adminId));setSetting(user.id,'telegram_miniapp_url',mini);setSetting(user.id,'telegram_required_chats',String(b.requiredChats||''));let menuButton=false;if(mini){try{const u=new URL(mini);u.searchParams.set('owner',user.username);await telegramWithToken(token,'setChatMenuButton',{chat_id:Number(b.adminId),menu_button:{type:'web_app',text:'ContactFlow',web_app:{url:u.toString()}}});menuButton=true;}catch(e){console.warn('Mini App menu button:',e.message);}}return json(res,200,{ok:true,menuButton,bot:{id:me.id,username:me.username,firstName:me.first_name}});}
  if(url.pathname==='/api/v1/telegram/health'&&method==='GET'){const token=telegramToken(user.id);let bot=null;if(token){try{const x=await telegramWithToken(token,'getMe',{});bot={id:x.id,username:x.username};}catch{}}return json(res,200,{configured:!!token,bot,adminId:getSetting(user.id,'telegram_admin_id',''),miniAppUrl:getSetting(user.id,'telegram_miniapp_url',''),requiredChats:getSetting(user.id,'telegram_required_chats','')});}
  if(url.pathname==='/api/v1/telegram/sync-updates'&&method==='POST'){return json(res,200,await handleTelegramUpdates(user.id));}
  if(url.pathname==='/api/v1/telegram/subscribers'&&method==='GET'){const rows=db.prepare('SELECT chat_id chatId,first_name firstName,username,last_seen lastSeen FROM telegram_subscribers WHERE user_id=? AND opted_in=1 AND suppressed=0 ORDER BY last_seen DESC LIMIT 10000').all(user.id);return json(res,200,{items:rows});}
  if(url.pathname==='/api/v1/telegram/suppression'&&method==='GET'){const rows=db.prepare('SELECT chat_id chatId,first_name firstName,username,last_seen lastSeen FROM telegram_subscribers WHERE user_id=? AND suppressed=1 ORDER BY last_seen DESC LIMIT 10000').all(user.id);return json(res,200,{items:rows});}
  m=url.pathname.match(/^\/api\/v1\/telegram\/suppression\/(\d+)\/enable$/);if(m&&method==='POST'){db.prepare('UPDATE telegram_subscribers SET suppressed=0,opted_in=1 WHERE user_id=? AND chat_id=?').run(user.id,m[1]);return json(res,200,{ok:true});}
  if(url.pathname==='/api/v1/telegram/ad-requests'&&method==='GET'){const rows=db.prepare("SELECT id,chat_id chatId,first_name firstName,username,status,created_at createdAt FROM ad_requests WHERE user_id=? ORDER BY created_at DESC LIMIT 1000").all(user.id);return json(res,200,{items:rows});}
  if(url.pathname==='/api/v1/telegram/business-connections'&&method==='GET'){const rows=db.prepare('SELECT connection_id connectionId,business_user_id businessUserId,enabled,last_seen lastSeen FROM telegram_business_connections WHERE user_id=? ORDER BY last_seen DESC').all(user.id);return json(res,200,{items:rows});}
  if(url.pathname==='/api/v1/telegram/business-chats'&&method==='GET'){const connectionId=String(url.searchParams.get('connectionId')||'');const rows=connectionId?db.prepare('SELECT connection_id connectionId,chat_id chatId,peer_user_id peerUserId,first_name firstName,username,last_seen lastSeen FROM telegram_business_chats WHERE user_id=? AND connection_id=? ORDER BY last_seen DESC LIMIT 5000').all(user.id,connectionId):db.prepare('SELECT connection_id connectionId,chat_id chatId,peer_user_id peerUserId,first_name firstName,username,last_seen lastSeen FROM telegram_business_chats WHERE user_id=? ORDER BY last_seen DESC LIMIT 5000').all(user.id);return json(res,200,{items:rows});}
  if(url.pathname==='/api/v1/telegram/business-send'&&method==='POST'){const b=await readBody(req),connectionId=String(b.connectionId||''),text=String(b.text||'').trim(),linkText=String(b.linkText||'').trim().slice(0,64),linkUrl=b.linkUrl?safeUrl(b.linkUrl):'',chatIds=[...new Set((Array.isArray(b.chatIds)?b.chatIds:[]).map(String))].slice(0,100);if(!connectionId||!text||!chatIds.length)return json(res,400,{error:'Connection، متن و حداقل یک چت لازم است.'});const conn=db.prepare('SELECT connection_id FROM telegram_business_connections WHERE user_id=? AND connection_id=? AND enabled=1').get(user.id,connectionId);if(!conn)return json(res,404,{error:'Business Connection فعال پیدا نشد.'});let sent=0,failed=0;for(const chatId of chatIds){const own=db.prepare('SELECT chat_id FROM telegram_business_chats WHERE user_id=? AND connection_id=? AND chat_id=?').get(user.id,connectionId,chatId);if(!own){failed++;continue;}try{const payload={business_connection_id:connectionId,chat_id:chatId,text};if(linkUrl)payload.reply_markup={inline_keyboard:[[{text:linkText||'مشاهده',url:linkUrl}]]};await telegram(user.id,'sendMessage',payload);sent++;}catch{failed++;}}return json(res,200,{sent,failed,total:chatIds.length});}
  if(url.pathname==='/api/v1/telegram/campaigns'&&method==='POST'){const b=await readBody(req),text=String(b.text||'').trim(),linkText=String(b.linkText||'').trim().slice(0,64),linkUrl=b.linkUrl?safeUrl(b.linkUrl):'';if(!text||text.length>4000)return json(res,400,{error:'متن پیام باید بین 1 تا 4000 کاراکتر باشد.'});const contentHash=sha(JSON.stringify([text,linkText,linkUrl]));const same=db.prepare("SELECT id,status FROM campaigns WHERE user_id=? AND content_hash=? ORDER BY id DESC LIMIT 1").get(user.id,contentHash);if(same&&!b.force)return json(res,409,{error:`همین محتوای تبلیغ قبلاً در کمپین #${same.id} ثبت شده است. متن یا لینک را تغییر دهید.`});const subs=db.prepare('SELECT chat_id FROM telegram_subscribers WHERE user_id=? AND opted_in=1 AND suppressed=0').all(user.id);if(!subs.length)return json(res,400,{error:'مخاطب opt-in وجود ندارد.'});const info=db.prepare('INSERT INTO campaigns(user_id,text,link_text,link_url,content_hash,status,total,created_at) VALUES(?,?,?,?,?,?,?,?)').run(user.id,text,linkText,linkUrl,contentHash,'queued',subs.length,now()),id=Number(info.lastInsertRowid),ins=db.prepare("INSERT INTO campaign_recipients(campaign_id,chat_id,status) VALUES(?,?,'queued')");db.exec('BEGIN');try{for(const s of subs)ins.run(id,s.chat_id);db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}return json(res,201,{id,recipients:subs.length,contentHash});}
  m=url.pathname.match(/^\/api\/v1\/telegram\/campaigns\/(\d+)$/);if(m&&method==='GET'){const c=db.prepare('SELECT id,status,total,sent,failed,created_at createdAt,finished_at finishedAt FROM campaigns WHERE id=? AND user_id=?').get(Number(m[1]),user.id);if(!c)return json(res,404,{error:'کمپین پیدا نشد.'});return json(res,200,c);}
  return json(res,404,{error:'Endpoint پیدا نشد.'});
}

const MIME={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.webmanifest':'application/manifest+json; charset=utf-8','.png':'image/png','.svg':'image/svg+xml','.csv':'text/csv; charset=utf-8','.md':'text/markdown; charset=utf-8'};
function staticRoute(req,res,url){
  const pathname=decodeURIComponent(url.pathname==='/'?'/index.html':url.pathname),allowedFiles=new Set(['/index.html','/app.js','/pro.js','/config.js','/styles.css','/manifest.webmanifest','/sw.js']),webAsset=/^\/web\/(?:[a-zA-Z0-9._-]+|icons\/[a-zA-Z0-9._-]+)$/.test(pathname),allowed=allowedFiles.has(pathname)||/^\/icons\/[a-zA-Z0-9._-]+$/.test(pathname)||webAsset;if(!allowed)return json(res,404,{error:'Not found'});const rel=pathname.replace(/^\//,''),file=path.resolve(PUBLIC_DIR,rel);if(!file.startsWith(PUBLIC_DIR+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile())return json(res,404,{error:'Not found'});const st=fs.statSync(file),ext=path.extname(file).toLowerCase();res.writeHead(200,{'Content-Type':MIME[ext]||'application/octet-stream','Content-Length':st.size,'Cache-Control':ext==='.html'?'no-cache':'public, max-age=3600','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'self'; connect-src 'self' https: http://127.0.0.1:* http://localhost:*; img-src 'self' data: https:; style-src 'self' 'unsafe-inline'; script-src 'self' https://telegram.org; object-src 'none'; base-uri 'self'; frame-ancestors 'self' https://web.telegram.org https://*.telegram.org"});fs.createReadStream(file).pipe(res);
}

const server=http.createServer(async(req,res)=>{try{pruneSessions();const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(url.pathname==='/health'||url.pathname.startsWith('/api/'))await apiRoute(req,res,url);else staticRoute(req,res,url);}catch(e){console.error(e);if(!res.headersSent)json(res,e.status||500,{error:e.status?e.message:'خطای داخلی Server'});else res.end();}});
server.listen(PORT,HOST,()=>console.log(`ContactFlow Professional 1.2 http://${HOST}:${PORT} | data=${DATA_DIR}`));

let workerBusy=false;
setInterval(async()=>{if(workerBusy)return;const rec=db.prepare(`SELECT cr.id,cr.chat_id chatId,c.id campaignId,c.user_id userId,c.text,c.link_text linkText,c.link_url linkUrl FROM campaign_recipients cr JOIN campaigns c ON c.id=cr.campaign_id WHERE cr.status='queued' AND c.status IN ('queued','running') ORDER BY cr.id LIMIT 1`).get();if(!rec)return;workerBusy=true;try{db.prepare("UPDATE campaigns SET status='running' WHERE id=? AND status='queued'").run(rec.campaignId);const sub=db.prepare('SELECT opted_in optedIn,suppressed FROM telegram_subscribers WHERE user_id=? AND chat_id=?').get(rec.userId,rec.chatId);if(!sub||!sub.optedIn||sub.suppressed){db.prepare("UPDATE campaign_recipients SET status='skipped',error='suppressed_or_opted_out' WHERE id=?").run(rec.id);}else{await telegram(rec.userId,'sendMessage',{chat_id:rec.chatId,text:rec.text,reply_markup:inlineKeyboard({link_url:rec.linkUrl,link_text:rec.linkText})});db.prepare("UPDATE campaign_recipients SET status='sent' WHERE id=?").run(rec.id);db.prepare('UPDATE campaigns SET sent=sent+1 WHERE id=?').run(rec.campaignId);}}catch(e){db.prepare("UPDATE campaign_recipients SET status='failed',error=? WHERE id=?").run(String(e.message).slice(0,500),rec.id);db.prepare('UPDATE campaigns SET failed=failed+1 WHERE id=?').run(rec.campaignId);}finally{const left=db.prepare("SELECT count(*) c FROM campaign_recipients WHERE campaign_id=? AND status='queued'").get(rec.campaignId).c;if(!left)db.prepare("UPDATE campaigns SET status='done',finished_at=? WHERE id=?").run(now(),rec.campaignId);workerBusy=false;}},120);
