<?php
require __DIR__.'/lib.php'; cf_cors();
$action=$_GET['action']??'info'; $cfg=cf_config();
if($action==='info') cf_json(['ok'=>true,'version'=>CF_VERSION,'configured'=>(bool)$cfg,'botUsername'=>$cfg['bot_username']??'','miniAppUrl'=>cf_base_url().'/miniapp.html','gatewayUrl'=>cf_base_url(),'mode'=>'telegram_business_bot']);
if($action==='health'){ $cs=cf_read_json('connections',[]);$enabled=0;foreach($cs as $c)if(!empty($c['enabled']))$enabled++;cf_json(['ok'=>true,'configured'=>(bool)$cfg,'connections'=>$enabled,'version'=>CF_VERSION]); }
if(!$cfg) cf_json(['ok'=>false,'error'=>'gateway_not_configured'],503);
if($action==='pair'){
  $b=cf_body();$code=preg_replace('/\D/','',(string)($b['code']??''));$codes=cf_read_json('pair_codes',[]);$r=$codes[$code]??null;if(!$r||($r['expires']??0)<time())cf_json(['ok'=>false,'error'=>'pair_code_invalid_or_expired'],400);unset($codes[$code]);cf_write_json('pair_codes',$codes);$raw=cf_token();$clients=cf_read_json('clients',[]);$clients[hash('sha256',$raw)]=['user_id'=>(string)$r['user_id'],'chat_id'=>(string)$r['chat_id'],'user'=>$r['user'],'created_at'=>time(),'last_seen'=>time()];cf_write_json('clients',$clients);cf_json(['ok'=>true,'token'=>$raw,'user'=>$r['user'],'botUsername'=>$cfg['bot_username']]);
}
if(strpos($action,'miniapp_')===0){
  $raw=$_SERVER['HTTP_X_TELEGRAM_INIT_DATA']??'';$user=cf_validate_init_data($raw);if(!$user)cf_json(['ok'=>false,'error'=>'invalid_telegram_init_data'],401);$sub=cf_upsert_subscriber($user,null);
  if($action==='miniapp_profile'){$cs=cf_read_json('connections',[]);$connections=[];foreach($cs as $c)if((string)($c['user_id']??'')===(string)$user['id'])$connections[]=$c;cf_json(['ok'=>true,'user'=>$user,'subscriber'=>$sub,'businessConnections'=>$connections]);}
  if($action==='miniapp_consent'){$b=cf_body();$sub=cf_upsert_subscriber($user,!empty($b['optin']));cf_json(['ok'=>true,'subscriber'=>$sub]);}
  cf_json(['ok'=>false,'error'=>'unknown_action'],404);
}
$client=cf_auth_client();$clients=cf_read_json('clients',[]);if(isset($clients[$client['_token_hash']])){$clients[$client['_token_hash']]['last_seen']=time();cf_write_json('clients',$clients);}
if($action==='connections'){$xs=cf_read_json('connections',[]);$out=[];foreach($xs as $c)if((string)($c['user_id']??'')===(string)$client['user_id'])$out[]=$c;usort($out,fn($a,$b)=>($b['updated_at']??0)<=>($a['updated_at']??0));cf_json(['ok'=>true,'connections'=>$out,'user'=>$client['user']??[]]);}
if($action==='chats'){$cid=(string)($_GET['connection_id']??'');cf_scoped_connection($client,$cid);$ch=cf_read_json('business_chats',[]);$subs=cf_read_json('subscribers',[]);$out=[];foreach($ch as $r)if((string)$r['connection_id']===$cid){$r['optin']=!empty($subs[(string)$r['chat_id']]['optin']);$out[]=$r;}usort($out,fn($a,$b)=>($b['last_message_at']??0)<=>($a['last_message_at']??0));cf_json(['ok'=>true,'chats'=>$out]);}
if($action==='set_label'){$b=cf_body();$cid=(string)($b['connection_id']??'');cf_scoped_connection($client,$cid);$xs=cf_read_json('connections',[]);$label=trim((string)($b['label']??''));$xs[$cid]['label']=function_exists('mb_substr')?mb_substr($label,0,50,'UTF-8'):substr($label,0,50);$xs[$cid]['updated_at']=time();cf_write_json('connections',$xs);cf_json(['ok'=>true,'connection'=>$xs[$cid]]);}
if($action==='stats'){$cs=cf_read_json('connections',[]);$ch=cf_read_json('business_chats',[]);$jobs=cf_read_json('jobs',[]);$n=0;$m=0;foreach($cs as $c)if((string)($c['user_id']??'')===(string)$client['user_id'])$n++;foreach($ch as $r){$c=$cs[$r['connection_id']]??null;if($c&&(string)$c['user_id']===(string)$client['user_id'])$m++;}cf_json(['ok'=>true,'connections'=>$n,'knownChats'=>$m,'jobs'=>count($jobs)]);}
function cf_eligible_for($cid,$purpose,$requested=[]){$ch=cf_read_json('business_chats',[]);$subs=cf_read_json('subscribers',[]);$req=array_flip(array_map('strval',$requested));$out=[];foreach($ch as $r){if((string)$r['connection_id']!==$cid)continue;$id=(string)$r['chat_id'];if($requested&&!isset($req[$id]))continue;$opt=!empty($subs[$id]['optin']);if($purpose==='promotional'&&!$opt)continue;$out[$id]=['chat_id'=>$id,'optin'=>$opt,'name'=>trim(($r['first_name']??'').' '.($r['last_name']??'')),'username'=>$r['username']??''];}return array_values($out);}
function cf_send_business_text($cid,$chatId,$text){return cf_tg('sendMessage',['business_connection_id'=>$cid,'chat_id'=>(string)$chatId,'text'=>$text,'disable_web_page_preview'=>'true']);}
if($action==='send_test'){$b=cf_body();$cid=(string)($b['connection_id']??'');cf_scoped_connection($client,$cid);$purpose=($b['purpose']??'service')==='promotional'?'promotional':'service';$targets=cf_eligible_for($cid,$purpose,[(string)($b['chat_id']??'')]);if(!$targets)cf_json(['ok'=>false,'error'=>'target_not_eligible'],403);$r=cf_send_business_text($cid,$targets[0]['chat_id'],cf_safe_text($b['text']??'ContactFlow test'));cf_json(['ok'=>!empty($r['ok']),'telegram'=>$r]);}
if($action==='campaign_enqueue'){$b=cf_body();$cid=(string)($b['connection_id']??'');cf_scoped_connection($client,$cid);$purpose=($b['purpose']??'promotional')==='service'?'service':'promotional';$text=cf_safe_text($b['text']??'');if(!$text)cf_json(['ok'=>false,'error'=>'message_required'],400);$requested=is_array($b['chat_ids']??null)?$b['chat_ids']:[];$targets=cf_eligible_for($cid,$purpose,$requested);$cap=max(1,min(500,(int)($b['cap']??80)));$targets=array_slice($targets,0,$cap);if(!$targets)cf_json(['ok'=>false,'error'=>'no_eligible_recipients'],400);$jobs=cf_read_json('jobs',[]);$id='job_'.bin2hex(random_bytes(8));$jobs[$id]=['id'=>$id,'owner_user_id'=>(string)$client['user_id'],'connection_id'=>$cid,'purpose'=>$purpose,'text'=>$text,'targets'=>$targets,'cursor'=>0,'sent'=>0,'failed'=>0,'skipped'=>0,'status'=>'queued','created_at'=>time(),'updated_at'=>time(),'next_run'=>time(),'cancelled'=>false,'errors'=>[]];cf_write_json('jobs',$jobs);cf_json(['ok'=>true,'job'=>$jobs[$id]]);}
if($action==='campaign_status'){$id=(string)($_GET['job_id']??'');$jobs=cf_read_json('jobs',[]);$j=$jobs[$id]??null;if(!$j||(string)$j['owner_user_id']!==(string)$client['user_id'])cf_json(['ok'=>false,'error'=>'job_not_found'],404);unset($j['text']);cf_json(['ok'=>true,'job'=>$j]);}
if($action==='campaign_cancel'){$b=cf_body();$id=(string)($b['job_id']??'');$jobs=cf_read_json('jobs',[]);if(empty($jobs[$id])||(string)$jobs[$id]['owner_user_id']!==(string)$client['user_id'])cf_json(['ok'=>false,'error'=>'job_not_found'],404);$jobs[$id]['cancelled']=true;$jobs[$id]['status']='cancelled';$jobs[$id]['updated_at']=time();cf_write_json('jobs',$jobs);cf_json(['ok'=>true]);}
if($action==='campaign_pump'){$b=cf_body();$id=(string)($b['job_id']??'');$jobs=cf_read_json('jobs',[]);if(empty($jobs[$id])||(string)$jobs[$id]['owner_user_id']!==(string)$client['user_id'])cf_json(['ok'=>false,'error'=>'job_not_found'],404);$j=&$jobs[$id];if(!empty($j['cancelled'])||in_array($j['status'],['done','cancelled'],true)){cf_write_json('jobs',$jobs);$out=$j;unset($out['text']);cf_json(['ok'=>true,'job'=>$out]);}if(($j['next_run']??0)>time()){$out=$j;unset($out['text']);cf_json(['ok'=>true,'job'=>$out,'waiting'=>true]);}$j['status']='running';$limit=3;for($k=0;$k<$limit&&$j['cursor']<count($j['targets']);$k++){$t=$j['targets'][$j['cursor']];$r=cf_send_business_text($j['connection_id'],$t['chat_id'],$j['text']);if(!empty($r['ok'])){$j['sent']++;$j['cursor']++;}else{$err=$r['description']??'Telegram error';$j['errors'][]=['chat_id'=>$t['chat_id'],'error'=>$err,'at'=>time()];if(($r['error_code']??0)==429){$retry=(int)($r['parameters']['retry_after']??30);$j['next_run']=time()+max(1,$retry);$j['status']='waiting';break;}$j['failed']++;$j['cursor']++;}usleep(700000);}if($j['cursor']>=count($j['targets']))$j['status']='done';$j['updated_at']=time();$j['errors']=array_slice($j['errors'],-30);cf_write_json('jobs',$jobs);$out=$j;unset($out['text']);cf_json(['ok'=>true,'job'=>$out]);}
cf_json(['ok'=>false,'error'=>'unknown_action'],404);
