<?php
require __DIR__.'/lib.php';
$existing=cf_config(); $msg=''; $err='';
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
  try{
    if(!$existing){
      $token=trim((string)($_POST['bot_token']??'')); if(!$token) throw new RuntimeException('Bot Token لازم است.');
      $getUrl='https://api.telegram.org/bot'.$token.'/getMe'; $raw=@file_get_contents($getUrl); if($raw===false && function_exists('curl_init')){ $ch=curl_init($getUrl); curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_TIMEOUT=>15]); $raw=curl_exec($ch); curl_close($ch); }
      $me=json_decode((string)$raw,true); if(empty($me['ok'])||empty($me['result']['username'])) throw new RuntimeException('Bot Token معتبر نیست یا getMe در دسترس نیست.');
      $base=cf_base_url(); $cfg=['bot_token'=>$token,'bot_username'=>$me['result']['username'],'bot_id'=>(string)$me['result']['id'],'webhook_secret'=>bin2hex(random_bytes(24)),'cron_key'=>bin2hex(random_bytes(24)),'installed_at'=>time(),'base_url'=>$base];
      $php="<?php\nreturn ".var_export($cfg,true).";\n"; if(file_put_contents(cf_config_path(),$php,LOCK_EX)===false)throw new RuntimeException('نوشتن storage/config.php ممکن نیست. Permission پوشه storage را بررسی کنید.'); @chmod(cf_config_path(),0600); $existing=$cfg;
    }
    $cfg=$existing; $base=cf_base_url(); if(strpos($base,'https://')!==0 && strpos($base,'http://localhost')!==0)throw new RuntimeException('Webhook و Mini App باید روی HTTPS باشند.');
    $wh=$base.'/webhook.php'; $mini=$base.'/miniapp.html';
    $r1=cf_tg('setWebhook',['url'=>$wh,'secret_token'=>$cfg['webhook_secret'],'allowed_updates'=>json_encode(['message','callback_query','business_connection','business_message','edited_business_message','deleted_business_messages'])]); if(empty($r1['ok']))throw new RuntimeException('setWebhook: '.($r1['description']??'Telegram error'));
    $r2=cf_tg('setMyCommands',['commands'=>json_encode([['command'=>'start','description'=>'اتصال ContactFlow'],['command'=>'subscribe','description'=>'اجازه پیام‌های اطلاع‌رسانی/تبلیغاتی'],['command'=>'stop','description'=>'لغو رضایت پیام'],['command'=>'status','description'=>'وضعیت اتصال']])]); if(empty($r2['ok']))throw new RuntimeException('setMyCommands: '.($r2['description']??'Telegram error'));
    $r3=cf_tg('setChatMenuButton',['menu_button'=>json_encode(['type'=>'web_app','text'=>'ContactFlow','web_app'=>['url'=>$mini]])]); if(empty($r3['ok']))throw new RuntimeException('setChatMenuButton: '.($r3['description']??'Telegram error'));
    $msg='Bot Gateway آماده است؛ Webhook، Commandها و Mini App Menu ثبت شدند.';
  }catch(Throwable $e){ $err=$e->getMessage(); }
}
?><!doctype html><html lang="fa" dir="rtl"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ContactFlow Bot Setup</title><style>body{font-family:Tahoma,Arial;background:#0f172a;color:#e5e7eb;max-width:780px;margin:40px auto;padding:20px}.card{background:#111c31;border:1px solid #2b3a55;border-radius:16px;padding:24px}input{width:100%;box-sizing:border-box;padding:12px;border-radius:10px;border:1px solid #3b4a66;background:#0b1220;color:#fff;margin:8px 0 16px}button{padding:12px 18px;border:0;border-radius:10px;background:#6d5dfc;color:#fff;font-weight:700}.ghost{background:#334155;margin-top:12px}code{direction:ltr;display:block;overflow:auto;background:#0b1220;padding:10px;border-radius:8px}.ok{color:#65e6a7}.bad{color:#ff8b8b}</style><body><div class="card"><h1>ContactFlow Telegram Gateway</h1><p>Mini App بدون این مرحله هم با آدرس <code><?=htmlspecialchars(cf_base_url().'/miniapp.html')?></code> باز می‌شود. این Setup فقط برای اتصال Bot/Business و ارسال پیام لازم است.</p><?php if($msg):?><p class="ok"><?=$msg?></p><?php endif;?><?php if($err):?><p class="bad"><?=htmlspecialchars($err)?></p><?php endif;?><?php if($existing):?><h3>Gateway آماده است</h3><p>Bot: @<?=htmlspecialchars($existing['bot_username']??'')?></p><p>Mini App:</p><code><?=htmlspecialchars(cf_base_url().'/miniapp.html')?></code><p>Gateway URL برای ContactFlow:</p><code><?=htmlspecialchars(cf_base_url())?></code><p>برای Pair کردن هر حساب: Bot را با همان حساب Start کنید، کد Pair را در ContactFlow وارد کنید، سپس در Telegram → Settings → Telegram Business → Chatbots همین Bot را متصل کنید.</p><p>اگر Cron می‌خواهید، هر دقیقه اجرا کنید:</p><code>php <?=htmlspecialchars(__DIR__.'/cron.php')?> <?=htmlspecialchars($existing['cron_key']??'')?></code><form method="post"><button name="repair" value="1" class="ghost">تست/تعمیر Webhook و Mini App Menu</button></form><?php else:?><form method="post"><label>Bot Token از BotFather</label><input name="bot_token" dir="ltr" autocomplete="off" required placeholder="123456:ABC..."><button>راه‌اندازی Bot Gateway</button></form><?php endif;?></div></body></html>
