(()=>{'use strict';
const VERSION='2.0.0-alpha.1';
const DB_NAME='contactflow-personal';
const DB_VERSION=1;
const STORES=['contacts','settings','history','projects','imports','exports','templates'];
let db=null, queue=[], page=0, driveToken=null, driveTokenUntil=0;
const $=id=>document.getElementById(id);
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const log=(id,msg,clear=false)=>{const el=$(id);if(!el)return;if(clear)el.textContent='';el.textContent+=(el.textContent?'\n':'')+msg;el.scrollTop=el.scrollHeight};
const status=s=>{$('storageStatus').textContent=s};
const reqP=req=>new Promise((resolve,reject)=>{req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains('contacts')){const s=d.createObjectStore('contacts',{keyPath:'id',autoIncrement:true});s.createIndex('phone','phone',{unique:true});s.createIndex('name','name');s.createIndex('city','city');s.createIndex('section','section')}for(const n of STORES.filter(x=>x!=='contacts'))if(!d.objectStoreNames.contains(n))d.createObjectStore(n,n==='settings'?{keyPath:'key'}:{keyPath:'id',autoIncrement:true})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function getSetting(key,fallback=''){const tx=db.transaction('settings','readonly'),v=await reqP(tx.objectStore('settings').get(key));return v?v.value:fallback}
async function setSetting(key,value){const tx=db.transaction('settings','readwrite');tx.objectStore('settings').put({key,value});return txDone(tx)}
function txDone(tx){return new Promise((resolve,reject)=>{tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('transaction aborted'))})}
function normalizePhone(raw){let s=String(raw??'').trim().replace(/[\u06F0-\u06F9]/g,d=>'0123456789'['۰۱۲۳۴۵۶۷۸۹'.indexOf(d)]).replace(/[\u0660-\u0669]/g,d=>'0123456789'['٠١٢٣٤٥٦٧٨٩'.indexOf(d)]).replace(/\D/g,'');if(s.startsWith('0098'))s='0'+s.slice(4);else if(s.startsWith('98')&&s.length===12)s='0'+s.slice(2);else if(s.length===10&&s.startsWith('9'))s='0'+s;const m=s.match(/09\d{9}/);return m?m[0]:''}
function matchContact(c,q){q=(q||'').trim().toLowerCase();if(!q)return true;return [c.name,c.phone,c.city,c.section].some(v=>String(v||'').toLowerCase().includes(q))}
function csvRow(line){const out=[];let cur='',q=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'){if(q&&line[i+1]==='"'){cur+='"';i++}else q=!q}else if(ch===','&&!q){out.push(cur.trim());cur=''}else cur+=ch}out.push(cur.trim());return out}
function detectCols(row){const h=row.map(x=>String(x||'').trim().toLowerCase());const find=keys=>h.findIndex(v=>keys.some(k=>v.includes(k)));return{phone:find(['phone','mobile','tel','شماره','موبایل','تلفن']),name:find(['name','نام']),city:find(['city','شهر']),section:find(['section','بخش','ناحیه'])}}
function likelyHeader(row){return row.some(v=>/(phone|mobile|tel|name|city|section|شماره|موبایل|نام|شهر|بخش)/i.test(String(v||'')))}
async function addBatch(items){if(!items.length)return{added:0,dup:0};const tx=db.transaction('contacts','readwrite'),s=tx.objectStore('contacts');let added=0,dup=0,fatal=null;for(const item of items){const r=s.add(item);r.onsuccess=()=>added++;r.onerror=e=>{if(r.error&&r.error.name==='ConstraintError'){dup++;e.preventDefault();e.stopPropagation()}else fatal=r.error}}await txDone(tx);if(fatal)throw fatal;return{added,dup}}
async function processRows(rows,cfg,source){if(!rows.length)return{added:0,dup:0,invalid:0};let cols={phone:0,name:1,city:2,section:3},start=0;if(likelyHeader(rows[0])){cols=detectCols(rows[0]);start=1;if(cols.phone<0)cols.phone=0}let serial=Number(cfg.start||1),added=0,dup=0,invalid=0,batch=[];for(let i=start;i<rows.length;i++){const r=rows[i];const phone=normalizePhone(r[cols.phone]);if(!phone){invalid++;continue}const srcName=cols.name>=0?String(r[cols.name]||'').trim():'';const city=String(cfg.city||((cols.city>=0&&r[cols.city])||'')).trim();const section=String(cfg.section||((cols.section>=0&&r[cols.section])||'')).trim();let name=srcName;if(cfg.prefix){name=`${cfg.prefix} ${serial}`.trim();serial++}else if(!name){name=`مخاطب ${serial++}`}batch.push({phone,name,city,section,source,createdAt:new Date().toISOString()});if(batch.length>=2000){const z=await addBatch(batch);added+=z.added;dup+=z.dup;batch=[]}}if(batch.length){const z=await addBatch(batch);added+=z.added;dup+=z.dup}return{added,dup,invalid}}
async function importTextFile(file,cfg,onProgress){const reader=file.stream().getReader(),decoder=new TextDecoder('utf-8');let buf='',rows=[],stats={added:0,dup:0,invalid:0},read=0;while(true){const {value,done}=await reader.read();if(done)break;read+=value.byteLength;buf+=decoder.decode(value,{stream:true});const lines=buf.split(/\r?\n/);buf=lines.pop()||'';for(const line of lines){if(!line.trim())continue;rows.push(file.name.toLowerCase().endsWith('.txt')&&!line.includes(',')?[line]:csvRow(line));if(rows.length>=5000){const r=await processRows(rows,cfg,file.name);stats.added+=r.added;stats.dup+=r.dup;stats.invalid+=r.invalid;rows=[];onProgress(Math.min(99,Math.round(read/file.size*100)));await sleep(0)}}}if(buf.trim())rows.push(file.name.toLowerCase().endsWith('.txt')&&!buf.includes(',')?[buf]:csvRow(buf));if(rows.length){const r=await processRows(rows,cfg,file.name);stats.added+=r.added;stats.dup+=r.dup;stats.invalid+=r.invalid}onProgress(100);return stats}
async function importExcel(file,cfg,onProgress){if(!window.XLSX)throw new Error('موتور XLSX لود نشده؛ اینترنت را بررسی کنید یا CSV وارد کنید.');const ab=await file.arrayBuffer();onProgress(25);const wb=XLSX.read(ab,{type:'array'});let stats={added:0,dup:0,invalid:0},done=0;for(const sn of wb.SheetNames){const rows=XLSX.utils.sheet_to_json(wb.Sheets[sn],{header:1,raw:false,defval:''});const r=await processRows(rows,cfg,`${file.name}:${sn}`);stats.added+=r.added;stats.dup+=r.dup;stats.invalid+=r.invalid;done++;onProgress(25+Math.round(done/wb.SheetNames.length*75))}return stats}
function queueCard(item,i){const d=document.createElement('div');d.className='queue-item';d.innerHTML=`<strong>${escapeHtml(item.file.name)}</strong> <small>(${(item.file.size/1024/1024).toFixed(2)} MB)</small><div class="grid2"><label>پیشوند نام<input data-k="prefix" data-i="${i}" value="${escapeAttr(item.cfg.prefix)}"></label><label>شروع سریال<input data-k="start" data-i="${i}" type="number" min="1" value="${item.cfg.start}"></label><label>شهر<input data-k="city" data-i="${i}" value="${escapeAttr(item.cfg.city)}"></label><label>بخش<input data-k="section" data-i="${i}" value="${escapeAttr(item.cfg.section)}"></label></div><small data-state="${i}">در صف</small>`;return d}
const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const escapeAttr=escapeHtml;
async function renderQueue(){const box=$('importQueue');box.innerHTML='';queue.forEach((x,i)=>box.appendChild(queueCard(x,i)));box.querySelectorAll('input[data-i]').forEach(el=>el.addEventListener('input',()=>{queue[Number(el.dataset.i)].cfg[el.dataset.k]=el.dataset.k==='start'?Number(el.value||1):el.value}))}
async function startImport(){if(!queue.length)return log('importLog','ابتدا فایل انتخاب کنید.',true);$('startImport').disabled=true;log('importLog','شروع Import...',true);let overall=0;try{for(let i=0;i<queue.length;i++){const it=queue[i],state=document.querySelector(`[data-state="${i}"]`);state.textContent='در حال پردازش';const progress=p=>{$('importProgress').style.width=`${Math.round((i+p/100)/queue.length*100)}%`};let r;if(/\.xlsx?$/i.test(it.file.name))r=await importExcel(it.file,it.cfg,progress);else r=await importTextFile(it.file,it.cfg,progress);overall+=r.added;state.textContent=`تمام شد: ${r.added} جدید، ${r.dup} تکراری، ${r.invalid} نامعتبر`;log('importLog',`${it.file.name}: +${r.added} | تکراری ${r.dup} | نامعتبر ${r.invalid}`);await addHistory('import',{file:it.file.name,...r})}$('importProgress').style.width='100%';log('importLog',`پایان صف. ${overall} مخاطب جدید.`);await refreshCounts()}catch(e){log('importLog','خطا: '+e.message)}finally{$('startImport').disabled=false}}
async function addHistory(action,data){const tx=db.transaction('history','readwrite');tx.objectStore('history').add({action,data,at:new Date().toISOString()});await txDone(tx)}
async function countContacts(){return reqP(db.transaction('contacts','readonly').objectStore('contacts').count())}
async function filteredList(q,limit=200,skip=0){return new Promise((resolve,reject)=>{const out=[];let matched=0,passed=0;const tx=db.transaction('contacts','readonly'),r=tx.objectStore('contacts').openCursor();r.onerror=()=>reject(r.error);r.onsuccess=()=>{const c=r.result;if(!c){resolve({rows:out,matched});return}if(matchContact(c.value,q)){if(passed>=skip&&out.length<limit)out.push(c.value);passed++;matched++}c.continue()}})}
async function filteredCount(q){return new Promise((resolve,reject)=>{let n=0;const r=db.transaction('contacts','readonly').objectStore('contacts').openCursor();r.onerror=()=>reject(r.error);r.onsuccess=()=>{const c=r.result;if(!c)return resolve(n);if(matchContact(c.value,q))n++;c.continue()}})}
async function refreshCounts(){const total=await countContacts();$('totalContacts').textContent=total.toLocaleString('fa-IR');const q=$('contactSearch').value;const n=await filteredCount(q);$('filteredContacts').textContent=n.toLocaleString('fa-IR');return n}
async function renderContacts(){status('در حال خواندن');const q=$('contactSearch').value,n=await refreshCounts(),res=await filteredList(q,200,page*200);$('contactRows').innerHTML=res.rows.map((c,i)=>`<tr><td>${page*200+i+1}</td><td>${escapeHtml(c.name||'')}</td><td dir="ltr">${escapeHtml(c.phone)}</td><td>${escapeHtml(c.city||'')}</td><td>${escapeHtml(c.section||'')}</td></tr>`).join('');$('pageLabel').textContent=`صفحه ${page+1} از ${Math.max(1,Math.ceil(n/200))}`;$('prevPage').disabled=page===0;$('nextPage').disabled=(page+1)*200>=n;status('آماده')}
async function deleteFiltered(){const q=$('contactSearch').value;if(!confirm(q?`همه مخاطبین منطبق با «${q}» حذف شوند؟`:'همه مخاطبین حذف شوند؟'))return;status('در حال حذف');const tx=db.transaction('contacts','readwrite'),s=tx.objectStore('contacts');await new Promise((resolve,reject)=>{const r=s.openCursor();r.onerror=()=>reject(r.error);r.onsuccess=()=>{const c=r.result;if(!c)return resolve();if(matchContact(c.value,q))c.delete();c.continue()}});await txDone(tx);page=0;await renderContacts();status('آماده')}
async function runBulk(){const q=$('bulkFilter').value,prefix=$('bulkName').value.trim(),city=$('bulkCity').value.trim(),section=$('bulkSection').value.trim();let serial=Number($('bulkStart').value||1),n=0;log('bulkLog','شروع...',true);const tx=db.transaction('contacts','readwrite'),s=tx.objectStore('contacts');await new Promise((resolve,reject)=>{const r=s.openCursor();r.onerror=()=>reject(r.error);r.onsuccess=()=>{const c=r.result;if(!c)return resolve();if(matchContact(c.value,q)){const v=c.value;if(prefix)v.name=`${prefix} ${serial++}`;if(city)v.city=city;if(section)v.section=section;c.update(v);n++}c.continue()}});await txDone(tx);log('bulkLog',`${n.toLocaleString('fa-IR')} رکورد ویرایش شد.`);await addHistory('bulk',{filter:q,count:n,prefix,city,section})}
function csvEscape(v){v=String(v??'');return /[",\n\r]/.test(v)?'"'+v.replace(/"/g,'""')+'"':v}
function vcard(c){const esc=s=>String(s||'').replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/;/g,'\\;').replace(/,/g,'\\,');return `BEGIN:VCARD\r\nVERSION:3.0\r\nFN:${esc(c.name||c.phone)}\r\nTEL;TYPE=CELL:${c.phone}\r\n${c.city?`ADR;TYPE=HOME:;;;${esc(c.city)};;;;\r\n`:''}${c.section?`NOTE:${esc(c.section)}\r\n`:''}END:VCARD\r\n`}
async function getAllFiltered(q){return new Promise((resolve,reject)=>{const out=[];const r=db.transaction('contacts','readonly').objectStore('contacts').openCursor();r.onerror=()=>reject(r.error);r.onsuccess=()=>{const c=r.result;if(!c)return resolve(out);if(matchContact(c.value,q))out.push(c.value);c.continue()}})}
async function blobToBase64(blob){const ab=await blob.arrayBuffer(),bytes=new Uint8Array(ab);let binary='';const step=0x8000;for(let i=0;i<bytes.length;i+=step)binary+=String.fromCharCode(...bytes.subarray(i,i+step));return btoa(binary)}
async function saveBlob(blob,name){if(window.ContactFlowAndroid&&typeof window.ContactFlowAndroid.saveBase64File==='function'){const b64=await blobToBase64(blob);window.ContactFlowAndroid.saveBase64File(name,blob.type||'application/octet-stream',b64);return}if('showSaveFilePicker'in window){try{const h=await showSaveFilePicker({suggestedName:name});const w=await h.createWritable();await w.write(blob);await w.close();return}catch(e){if(e.name==='AbortError')return}}const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),10000)}
async function runExport(){const q=$('exportFilter').value,chunk=Math.max(100,Number($('exportChunk').value||5000)),fmt=$('exportFormat').value,useZip=$('exportZip').checked;log('exportLog','در حال خواندن...',true);const rows=await getAllFiltered(q);if(!rows.length)return log('exportLog','رکوردی برای خروجی نیست.');const groups=[];for(let i=0;i<rows.length;i+=chunk)groups.push(rows.slice(i,i+chunk));const files=[];groups.forEach((g,i)=>{const num=String(i+1).padStart(4,'0');let text,mime,ext;if(fmt==='vcf'){text=g.map(vcard).join('');mime='text/vcard;charset=utf-8';ext='vcf'}else{text='name,phone,city,section\r\n'+g.map(c=>[c.name,c.phone,c.city,c.section].map(csvEscape).join(',')).join('\r\n');mime='text/csv;charset=utf-8';ext='csv'}files.push({name:`ContactFlow_${num}.${ext}`,blob:new Blob([text],{type:mime})})});if(useZip&&window.JSZip){log('exportLog',`ساخت ZIP شامل ${files.length} فایل...`);const z=new JSZip();for(const f of files)z.file(f.name,f.blob);const blob=await z.generateAsync({type:'blob',compression:'DEFLATE',compressionOptions:{level:6}},m=>log('exportLog',`ZIP ${Math.round(m.percent)}%`,true));await saveBlob(blob,`ContactFlow_Export_${stamp()}.zip`)}else{for(const f of files){await saveBlob(f.blob,f.name);await sleep(150)}}log('exportLog',`${rows.length.toLocaleString('fa-IR')} مخاطب در ${files.length} فایل خروجی شد.`);await addHistory('export',{count:rows.length,files:files.length,format:fmt})}
const b64=u=>{let s='';for(let i=0;i<u.length;i+=0x8000)s+=String.fromCharCode(...u.subarray(i,i+0x8000));return btoa(s)};const unb64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
async function exportDatabase(){const data={format:'ContactFlowPersonalBackupData',version:2,appVersion:VERSION,createdAt:new Date().toISOString(),stores:{}};for(const n of STORES)data.stores[n]=await reqP(db.transaction(n,'readonly').objectStore(n).getAll());return data}
async function deriveKey(password,salt){const base=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:250000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function makeBackupText(password=''){const data=await exportDatabase(),plain=new TextEncoder().encode(JSON.stringify(data));if(password){if(password.length<8)throw new Error('رمز Backup حداقل 8 کاراکتر باشد.');const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await deriveKey(password,salt),cipher=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},key,plain));return JSON.stringify({format:'ContactFlowBackup',version:2,encrypted:true,kdf:'PBKDF2-SHA256',iterations:250000,cipher:'AES-GCM',salt:b64(salt),iv:b64(iv),data:b64(cipher)})}return JSON.stringify({format:'ContactFlowBackup',version:2,encrypted:false,data:JSON.parse(new TextDecoder().decode(plain))})}
async function parseBackupText(text,password=''){let wrap;try{wrap=JSON.parse(text)}catch{throw new Error('فایل Backup JSON معتبر نیست.')}if(wrap.format!=='ContactFlowBackup'||Number(wrap.version)!==2)throw new Error('این فایل Backup متعلق به ContactFlow Personal 2 نیست.');let data;if(wrap.encrypted){if(!password)throw new Error('این Backup رمزگذاری شده؛ رمز را وارد کنید.');const salt=unb64(wrap.salt),iv=unb64(wrap.iv),cipher=unb64(wrap.data),key=await deriveKey(password,salt);let plain;try{plain=await crypto.subtle.decrypt({name:'AES-GCM',iv},key,cipher)}catch{throw new Error('رمز اشتباه است یا Backup آسیب دیده.')}data=JSON.parse(new TextDecoder().decode(plain))}else data=wrap.data;if(!data||data.format!=='ContactFlowPersonalBackupData'||!data.stores)throw new Error('ساختار داخلی Backup معتبر نیست.');return data}
async function restoreData(data){for(const n of STORES){const tx=db.transaction(n,'readwrite'),s=tx.objectStore(n);s.clear();for(const row of(data.stores[n]||[]))s.put(row);await txDone(tx)}await refreshCounts()}
function stamp(){const d=new Date(),p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}${p(d.getMonth()+1)}${p(d.getDate())}_${p(d.getHours())}${p(d.getMinutes())}${p(d.getSeconds())}`}
async function manualBackup(){const p=$('backupPassword').value,p2=$('backupPassword2').value;if(p!==p2)return log('backupLog','تکرار رمز یکسان نیست.',true);status('ساخت Backup');try{const text=await makeBackupText(p);await saveBlob(new Blob([text],{type:'application/vnd.contactflow.backup+json'}),`ContactFlow_Backup_${stamp()}.cfbackup`);log('backupLog','Backup ساخته شد.',true);await addHistory('backup',{encrypted:!!p})}catch(e){log('backupLog','خطا: '+e.message,true)}finally{status('آماده')}}
async function restoreFile(file){if(!file)return;const p=$('backupPassword').value;status('Restore');try{const data=await parseBackupText(await file.text(),p);const counts=Object.fromEntries(Object.entries(data.stores).map(([k,v])=>[k,v.length]));if(!confirm(`Backup معتبر است. ${counts.contacts||0} مخاطب جایگزین داده فعلی شود؟`))return;await restoreData(data);log('backupLog','Restore با موفقیت انجام شد.',true);await addHistory('restore',{contacts:counts.contacts||0})}catch(e){log('backupLog','خطا: '+e.message,true)}finally{status('آماده')}}
async function saveGoogleClient(){await setSetting('googleClientId',$('googleClientId').value.trim());log('backupLog','Client ID ذخیره شد.',true)}
async function ensureDriveToken(force=false){if(!force&&driveToken&&Date.now()<driveTokenUntil-60000)return driveToken;const clientId=$('googleClientId').value.trim();if(!clientId)throw new Error('Google OAuth Client ID را وارد و ذخیره کنید.');if(!window.google?.accounts?.oauth2)throw new Error('Google Identity Services هنوز لود نشده است.');return new Promise((resolve,reject)=>{const c=google.accounts.oauth2.initTokenClient({client_id:clientId,scope:'https://www.googleapis.com/auth/drive.file',callback:r=>{if(r.error)return reject(new Error(r.error));driveToken=r.access_token;driveTokenUntil=Date.now()+Number(r.expires_in||3600)*1000;$('driveState').value='متصل';resolve(driveToken)},error_callback:e=>reject(new Error(e?.type||'Google OAuth error'))});c.requestAccessToken({prompt:force?'consent':''})})}
async function driveFetch(url,opt={}){const token=await ensureDriveToken(false);const headers=new Headers(opt.headers||{});headers.set('Authorization','Bearer '+token);let r=await fetch(url,{...opt,headers});if(r.status===401){driveToken=null;const t=await ensureDriveToken(true);headers.set('Authorization','Bearer '+t);r=await fetch(url,{...opt,headers})}if(!r.ok)throw new Error(`Google Drive HTTP ${r.status}: ${await r.text()}`);return r}
async function backupToDrive(){const p=$('backupPassword').value,p2=$('backupPassword2').value;if(p!==p2)return log('backupLog','تکرار رمز یکسان نیست.',true);status('Google Drive');try{await ensureDriveToken(false);const text=await makeBackupText(p),blob=new Blob([text],{type:'application/vnd.contactflow.backup+json'}),name=`ContactFlow_Backup_${stamp()}.cfbackup`;const init=await driveFetch('https://www.googleapis.com/upload/drive/v3/files?uploadType=resumable',{method:'POST',headers:{'Content-Type':'application/json; charset=UTF-8','X-Upload-Content-Type':blob.type,'X-Upload-Content-Length':String(blob.size)},body:JSON.stringify({name,mimeType:blob.type,appProperties:{contactflow:'personal2'}})});const location=init.headers.get('Location');if(!location)throw new Error('Google Drive آدرس Resumable Upload نداد.');const up=await driveFetch(location,{method:'PUT',headers:{'Content-Type':blob.type,'Content-Length':String(blob.size)},body:blob});const meta=await up.json();log('backupLog',`Backup روی Google Drive ذخیره شد: ${name}\nID: ${meta.id}`,true);await listDriveFiles()}catch(e){log('backupLog','خطا: '+e.message,true)}finally{status('آماده')}}
async function listDriveFiles(){status('Drive list');try{const q=encodeURIComponent("appProperties has { key='contactflow' and value='personal2' } and trashed=false"),fields=encodeURIComponent('files(id,name,modifiedTime,size,mimeType)');const r=await driveFetch(`https://www.googleapis.com/drive/v3/files?q=${q}&fields=${fields}&orderBy=modifiedTime desc&pageSize=100`),j=await r.json(),box=$('driveFiles');box.innerHTML='';if(!j.files?.length)box.textContent='Backupی پیدا نشد.';for(const f of j.files){const d=document.createElement('div');d.className='queue-item';d.innerHTML=`<strong>${escapeHtml(f.name)}</strong><br><small>${escapeHtml(f.modifiedTime||'')} • ${f.size?Math.round(Number(f.size)/1024)+' KB':''}</small> <button data-drive="${escapeAttr(f.id)}">Restore</button>`;box.appendChild(d)}box.querySelectorAll('[data-drive]').forEach(b=>b.addEventListener('click',()=>restoreFromDrive(b.dataset.drive)));return j.files||[]}catch(e){log('backupLog','خطا: '+e.message,true);return[]}finally{status('آماده')}}
async function restoreFromDrive(id){status('Drive Restore');try{const r=await driveFetch(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(id)}?alt=media`),text=await r.text(),data=await parseBackupText(text,$('backupPassword').value);const n=data.stores.contacts?.length||0;if(!confirm(`Backup Google Drive معتبر است و ${n} مخاطب دارد. داده فعلی جایگزین شود؟`))return;await restoreData(data);log('backupLog',`Restore از Google Drive انجام شد: ${n} مخاطب`,true)}catch(e){log('backupLog','خطا: '+e.message,true)}finally{status('آماده')}}
async function loadSettings(){const prefix=await getSetting('defaultPrefix','مخاطب'),city=await getSetting('defaultCity',''),section=await getSetting('defaultSection',''),gid=await getSetting('googleClientId','');$('defaultPrefix').value=prefix;$('defaultCity').value=city;$('defaultSection').value=section;$('googleClientId').value=gid}
async function saveSettings(){await setSetting('defaultPrefix',$('defaultPrefix').value);await setSetting('defaultCity',$('defaultCity').value);await setSetting('defaultSection',$('defaultSection').value);await setSetting('autoDedupe',$('autoDedupe').checked);status('تنظیمات ذخیره شد');setTimeout(()=>status('آماده'),1200)}
async function wipeLocal(){if(!confirm('همه داده‌های محلی ContactFlow روی این دستگاه پاک شود؟'))return;if(!confirm('این کار قابل برگشت نیست مگر Backup داشته باشید. ادامه؟'))return;db.close();await new Promise((resolve,reject)=>{const r=indexedDB.deleteDatabase(DB_NAME);r.onsuccess=resolve;r.onerror=()=>reject(r.error);r.onblocked=()=>reject(new Error('دیتابیس در تب دیگری باز است'))});location.reload()}
function setupTabs(){document.querySelectorAll('.tabs button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));$(`tab-${b.dataset.tab}`).classList.add('active');if(b.dataset.tab==='contacts'){page=0;renderContacts()}}))}
function setupEvents(){$('importFiles').addEventListener('change',async e=>{const prefix=await getSetting('defaultPrefix','مخاطب'),city=await getSetting('defaultCity',''),section=await getSetting('defaultSection','');queue=[...e.target.files].map(f=>({file:f,cfg:{prefix,city,section,start:1}}));renderQueue()});$('startImport').onclick=startImport;$('clearQueue').onclick=()=>{queue=[];$('importFiles').value='';renderQueue();$('importProgress').style.width='0'};$('refreshContacts').onclick=()=>{page=0;renderContacts()};$('contactSearch').addEventListener('keydown',e=>{if(e.key==='Enter'){page=0;renderContacts()}});$('prevPage').onclick=()=>{if(page>0){page--;renderContacts()}};$('nextPage').onclick=()=>{page++;renderContacts()};$('deleteFiltered').onclick=deleteFiltered;$('runBulk').onclick=runBulk;$('runExport').onclick=runExport;$('makeBackup').onclick=manualBackup;$('restoreFile').addEventListener('change',e=>restoreFile(e.target.files[0]));$('saveGoogleId').onclick=saveGoogleClient;$('connectDrive').onclick=async()=>{try{await ensureDriveToken(true);log('backupLog','Google Drive متصل شد.',true)}catch(e){log('backupLog','خطا: '+e.message,true)}};$('backupDrive').onclick=backupToDrive;$('listDrive').onclick=listDriveFiles;$('saveSettings').onclick=saveSettings;$('wipeLocal').onclick=wipeLocal}
async function init(){try{db=await openDB();setupTabs();setupEvents();await loadSettings();await refreshCounts();status('Local DB آماده');if(window.Telegram?.WebApp){document.body.classList.add('telegram');Telegram.WebApp.ready();Telegram.WebApp.expand()}if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(()=>{})}catch(e){status('خطا');console.error(e);alert('خطای راه‌اندازی ContactFlow: '+e.message)}}
window.ContactFlow={version:VERSION,makeBackupText,parseBackupText,restoreData};document.addEventListener('DOMContentLoaded',init);
})();
