import fs from 'node:fs';
import path from 'node:path';

const root=path.resolve(new URL('..',import.meta.url).pathname);
const read=file=>fs.readFileSync(path.join(root,file),'utf8');
const required=['web/index.html','web/app.js','web/bulk-vcf-export.js','web/import-merge.js','web/location-operator.js','web/channel-handoff.js','web/name-engine.js','web/telegram-export.js','web/legacy-tools.js','web/backup-engine.js','web/file-save.js','web/v34.js','web/v35.js','web/v36.js','web/v36.css','web/sw.js','scripts/stress-bulk-vcf.mjs','extensions/sequential-file-renamer/SequentialFileRenamer.csproj','extensions/sequential-file-renamer/MainForm.cs','android/messengercontacts/build.gradle','android/messengercontacts/src/main/AndroidManifest.xml','android/messengercontacts/src/main/java/com/contactflow/messengercontacts/MainActivity.java','android/sequentialrenamer/build.gradle','android/sequentialrenamer/src/main/AndroidManifest.xml','android/sequentialrenamer/src/main/java/com/contactflow/sequentialrenamer/MainActivity.java','.github/workflows/release-all.yml'];
for(const file of required)if(!fs.existsSync(path.join(root,file)))throw new Error(`missing ${file}`);
const html=read('web/index.html');
for(const asset of ['name-engine.js','telegram-export.js','legacy-tools.js','backup-engine.js','file-save.js','bulk-vcf-export.js','v36.js','v36.css'])if(!html.includes(asset))throw new Error(`index missing ${asset}`);
for(const marker of ['export-extra','export-max-total','export-offline','export-online-fallback','export-split-city','cancel-export','تهران ایرانسل_0001.vcf'])if(!html.includes(marker))throw new Error(`million VCF UI missing ${marker}`);
for(const marker of ['MAX_TOTAL=1_000_000','makeVcfBlob','composeBaseName','partName','resolveEngine'])if(!read('web/bulk-vcf-export.js').includes(marker))throw new Error(`million VCF engine missing ${marker}`);
for(const marker of ['listExportScopes','exportAbort','offlineActive','splitByCity','maxTotal'])if(!read('web/app.js').includes(marker))throw new Error(`million VCF integration missing ${marker}`);
const v34=read('web/v34.js'),v36=read('web/v36.js');
for(const marker of ['cf34-dry" type="checkbox"','تحلیل و ثبت در مخاطبین','skipConfirm:true','ثبت و راستی‌آزمایی شد'])if(!v34.includes(marker))throw new Error(`atomic import missing ${marker}`);
for(const marker of ['data-page="insights"','data-page="telegram-offline"','data-page="legacy-tools"','repairContactData','Telegram Desktop Export','ContactFlowFileSave','واتساپ، روبیکا، بله و سروش'])if(!v36.includes(marker))throw new Error(`v36 UI missing ${marker}`);
for(const marker of ['whatsapp','rubika','bale','soroush'])if(!read('web/channel-handoff.js').includes(marker))throw new Error(`channel missing ${marker}`);
if(read('web/config.js').includes("telegramMode:'user_session_optional'"))throw new Error('API-dependent Telegram mode must not be primary');
if(!read('web/config.js').includes("telegramMode:'desktop_export_offline'"))throw new Error('offline Telegram export mode missing');
if(read('VERSION').trim()!=='3.6.0')throw new Error('VERSION must be 3.6.0');
for(const [file,marker] of [['desktop/main.go','appVersion = "3.6.0"'],['android/app/build.gradle',"versionName '3.6.0'"],['telegram-miniapp/lib.php',"CF_VERSION = '3.6.0'"],['.github/workflows/release-all.yml','VERSION: 3.6.0']])if(!read(file).includes(marker))throw new Error(`${file} is not on 3.6.0`);
for(const marker of ['SCHEMA_VERSION=9','SHA-256','restoreDatabase','durability:\'strict\'','blobCount','createController'])if(!read('web/backup-engine.js').includes(marker))throw new Error(`backup reliability marker missing ${marker}`);
for(const marker of ['verifyVcfSource','setPositiveButton("ورود سریع"','setNeutralButton("ورود به گوشی"'])if(!read('android/messengercontacts/src/main/java/com/contactflow/messengercontacts/MainActivity.java').includes(marker))throw new Error(`VCF chooser reliability marker missing ${marker}`);
for(const marker of ['beginDocumentSave','appendDocumentChunk','finishDocumentSave'])if(!read('android/app/src/main/java/com/contactflow/pro/MainActivity.java').includes(marker))throw new Error(`Android streaming save marker missing ${marker}`);
for(const asset of ["'./v36.js'","'./v36.css'","'./telegram-export.js'","'./legacy-tools.js'","'./backup-engine.js'","'./file-save.js'","'./bulk-vcf-export.js'"])if(!read('web/sw.js').includes(asset))throw new Error(`service worker missing ${asset}`);
for(const asset of ['ContactFlow_3.6_Sequential_File_Renamer_Windows_x64.exe','ContactFlow_3.6_Sequential_File_Renamer_Android.apk','ContactFlow_3.6_Messenger_Contacts_Android.apk'])if(!read('.github/workflows/release-all.yml').includes(asset))throw new Error(`release workflow missing extension ${asset}`);
for(const marker of ['suppressUiEvents','RefreshDraftCell','RenameCurrentAsync','MoveFileWithRetryAsync','ReportUnexpectedError'])if(!read('extensions/sequential-file-renamer/MainForm.cs').includes(marker))throw new Error(`sequential renamer hotfix missing ${marker}`);
if(!read('extensions/sequential-file-renamer/SequentialFileRenamer.csproj').includes('<FileVersion>3.6.0.3</FileVersion>'))throw new Error('sequential renamer hotfix file version missing');
if(read('android/messengercontacts/src/main/AndroidManifest.xml').includes('android.permission.INTERNET'))throw new Error('messenger contacts extension must remain offline');
if(read('android/sequentialrenamer/src/main/AndroidManifest.xml').includes('android.permission.INTERNET'))throw new Error('Android sequential renamer must remain offline');
for(const marker of ['Intent.ACTION_OPEN_DOCUMENT','Intent.ACTION_OPEN_DOCUMENT_TREE','EditorInfo.IME_ACTION_NEXT','suppressTextEvents','undoLast'])if(!read('android/sequentialrenamer/src/main/java/com/contactflow/sequentialrenamer/MainActivity.java').includes(marker))throw new Error(`Android sequential renamer missing ${marker}`);
JSON.parse(read('web/manifest.webmanifest'));
console.log('ContactFlow 3.6 source verification PASS');
