(() => {
'use strict';
const VERSION='3.2.0-business-hotfix';
const MAX_PAIRS=10;
const LS_GATEWAY='cf_business_gateway_url';
const LS_PAIRS='cf_business_pairs_v1';
const LS_ACTIVE='cf_business_active_v1';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function toast2(m,t='good'){try{if(typeof toast==='function')toast(m,t,5000);else console.log(m)}catch{console.log(m)}}
function base(){let b=String(localStorage.getItem(LS_GATEWAY)||'').trim().replace(/\/+$/,'');if(b)return b;try{const mini=String(localStorage.getItem('cf_mini_url')||'').trim();if(mini){const u=new URL(mini);u.pathname=u.pathname.replace(/\/[^/]*$/,'');return u.toString().replace(/\/+$/,'')}}catch{}return ''}
function setBase(v){v=String(v||'').trim().replace(/\/+$/,'');if(v&&!/^https:\/\//i.test(v)&&!/^http:\/\/localhost(?::\d+)?$/i.test(v))throw new Error('Gateway باید HTTPS باشد.');localStorage.setItem(LS_GATEWAY,v);return v}
function pairs(){try{const x=JSON.parse(localStorage.getItem(LS_PAIRS)||'[]');return Array.isArray(x)?x.slice(0,MAX_PAIRS):[]}catch{return []}}
function savePairs(x){localStorage.setItem(LS_PAIRS,JSON.stringify(x.slice(0,MAX_PAIRS)))}
function active(){try{return JSON.parse(localStorage.getItem(LS_ACTIVE)||'null')}catch{return null}}
function saveActive(x){localStorage.setItem(LS_ACTIVE,JSON.stringify(x||null))}
async function request(action,{pair=null,method='GET',body=null,query={}}={}){
  const b=base();if(!b)throw new Error('ابتدا Gateway URL را ثبت کنید.');const u=new URL(b+'/gateway.php');u.searchParams.set('action',action);Object.entries(query).forEach(([k,v])=>u.searchParams.set(k,v));
  const headers={'Accept':'application/json'};if(pair?.token)headers.Authorization='Bearer '+pair.token;if(body!==null)headers['Content-Type']='application/json';
  const r=await fetch(u,{method,headers,body:body===null?undefined:JSON.stringify(body)});let j;try{j=await r.json()}catch{throw new Error('پاسخ Gateway معتبر نیست.')}if(!r.ok||j.ok===false)throw new Error(j.error||`Gateway HTTP ${r.status}`);return j;
}
async function info(){return request('info')}
async function pairCode(code){const ps=pairs();if(ps.length>=MAX_PAIRS)throw new Error('حداکثر ۱۰ حساب Pair شده است.');const j=await request('pair',{method:'POST',body:{code}});ps.push({token:j.token,user:j.user||{},botUsername:j.botUsername||'',pairedAt:Date.now()});savePairs(ps);return j}
async function listAllConnections(){const ps=pairs(),out=[];for(let i=0;i<ps.length;i++){try{const j=await request('connections',{pair:ps[i]});for(const c of j.connections||[])out.push({...c,_pair:i,_pairUser:ps[i].user})}catch(e){out.push({_pair:i,_pairUser:ps[i].user,_pairError:e.message,id:''})}}return out}
function selectedValue(pairIndex,cid){return `${pairIndex}|${cid}`}
function accountLabel(c){const label=String(c.label||'').trim();if(label)return label;const un=String(c.username||'').trim();if(un)return '@'+un;return [c.first_name,c.last_name].filter(Boolean).join(' ')||String(c.user_id||'Business Account')}
function parseSelected(v){const [i,cid]=String(v||'').split('|');return {pairIndex:+i,connectionId:cid||''}}
async function chats(pairIndex,cid){return (await request('chats',{pair:pairs()[pairIndex],query:{connection_id:cid}})).chats||[]}
function gatewayPanel(){
  const p=document.querySelector('.page[data-page="telegram"]');if(!p)return null;
  let box=$('cf-business-box');if(box)return box;box=document.createElement('article');box.className='panel form-panel';box.id='cf-business-box';box.innerHTML=`<div class="panel-head"><div><h2>Telegram Business Bot Connector</h2><p>بدون TELEGRAM_API_ID / TELEGRAM_API_HASH — Pair با Bot و Business Connection رسمی</p></div><span id="cf-business-pill" class="pill queued">Gateway</span></div>
  <label><span>Gateway URL</span><input id="cf-business-url" dir="ltr" placeholder="https://domain/contactflow"></label>
  <div class="button-row"><button id="cf-business-save" class="primary-soft">ذخیره و تست Gateway</button><button id="cf-business-open-bot" class="primary-btn">Start Bot / افزودن حساب</button><button id="cf-business-refresh" class="ghost-btn">بروزرسانی اتصال‌ها</button></div>
  <div id="cf-pair-row" class="form-grid hidden"><label><span>Pair Code شش‌رقمی</span><input id="cf-pair-code" inputmode="numeric" dir="ltr" maxlength="6" placeholder="123456"></label><label><span>&nbsp;</span><button id="cf-pair-submit" class="primary-btn">Pair این حساب</button></label></div>
  <div id="cf-business-state" class="hint">Gateway را ثبت کنید. Mini App می‌تواند مستقل با miniapp.html باز شود.</div>`;
  const old=p.querySelector('.callout');old?.after(box);return box;
}
function capabilityPanel(){
  const p=document.querySelector('.page[data-page="telegram"]');if(!p||$('cf-business-features'))return;const a=document.createElement('article');a.id='cf-business-features';a.className='panel';a.innerHTML=`<div class="panel-head"><div><h2>۱۲+ قابلیت حرفه‌ای Connector</h2><p>برای کار روزانه و چند حساب، بدون App API credentials</p></div><span class="pill active">READY</span></div><div class="feature-grid">${[
  'Pair امن با کد ۶ رقمی از خود Bot','نگهداری تا ۱۰ Pair محلی','تشخیص خودکار Business Connection','انتخاب دستی حساب فرستنده','Health/Permission Status هر اتصال','لیست چت‌های Business دیده‌شده','Opt‑in اجباری برای تبلیغات','صف ارسال با Progress واقعی','توقف و Cancel کمپین','احترام به retry_after تلگرام','Mini App مستقل روی miniapp.html','VCF چندبخشی برای Import مخاطبین','ارسال تست قبل از کمپین','Label برای هر Connection','Diagnostics بدون QR/Google Secret'
].map(x=>`<div class="feature-item"><span>✓</span><div><strong>${x}</strong><small>active</small></div></div>`).join('')}</div>`;p.appendChild(a)
}
function patchTelegramStatic(){
  const p=document.querySelector('.page[data-page="telegram"]');if(!p)return;const call=p.querySelector('.callout');if(call)call.innerHTML='<div><strong>Telegram Business Bot — بدون QR Credential</strong><p>حساب با Bot Pair می‌شود و سپس از Telegram Business → Chatbots به همین Bot دسترسی می‌دهد. ContactFlow می‌تواند چند Business Connection از چند حساب را نگه دارد و حساب فرستنده را دستی انتخاب کند.</p></div><span id="tg-native-pill" class="pill active">Business Bot</span>';
  const add=$('tg-add-account');if(add)add.textContent='+ اتصال با Bot';const wrap=$('tg-qr-wrap');if(wrap){wrap.classList.add('hidden');wrap.innerHTML=''}
  const caps=$('tg-native-caps');if(caps)caps.innerHTML='<li><b>✓ Bot Pair</b><span>بدون API ID/Hash</span></li><li><b>✓ Business Connection</b><span>ارسال از حساب متصل با دسترسی رسمی</span></li><li><b>✓ Multi Pair</b><span>تا ۱۰ حساب در ContactFlow</span></li>';
  const panel=caps?.closest('article');if(panel){panel.querySelector('h2')&&(panel.querySelector('h2').textContent='وضعیت Business Gateway');const hint=panel.querySelector('.hint');if(hint)hint.textContent='شروع Bot به‌تنهایی حساب را متصل نمی‌کند؛ بعد از Pair باید همان Bot را در Telegram Business → Chatbots وصل کنید.'}
  const checker=$('cf-tg-run-check');if(checker){checker.textContent='ساخت VCF برای Import Contacts';checker.title='Bot API امکان ImportContacts به حساب کاربر را ندارد؛ VCF برای Contacts سیستم ساخته می‌شود.'}
  const clear=$('cf-tg-clear-check');if(clear)clear.style.display='none';document.querySelectorAll('[data-cf-check-export]').forEach(x=>x.style.display='none');
  const st=$('cf-check-state');if(st)st.textContent='Business Bot شماره تلفن را اسکن نمی‌کند؛ از VCF/Contacts Sync استفاده کنید.';
}
async function render(){
  const box=gatewayPanel();if(!box)return;const url=$('cf-business-url');if(url&&!url.value)url.value=base();
  let inf=null;try{if(base())inf=await info()}catch(e){$('cf-business-state').textContent='Gateway: '+e.message;$('cf-business-pill').textContent='Offline';$('cf-business-pill').className='pill danger'}
  if(inf){$('cf-business-pill').textContent=inf.configured?'Gateway Ready':'Mini App Only';$('cf-business-pill').className='pill '+(inf.configured?'active':'queued');$('cf-business-state').textContent=inf.configured?`Bot @${inf.botUsername} آماده است. برای هر حساب Start Bot → Pair Code → Telegram Business → Chatbots.`:'Mini App روی هاست آماده است؛ برای ارسال پیام setup.php را یک‌بار اجرا کنید.'}
  const xs=await listAllConnections();const ps=pairs(),list=$('tg-account-list');if(list){let html='';for(let i=0;i<ps.length;i++){const p=ps[i],cs=xs.filter(x=>x._pair===i&&x.id);const err=xs.find(x=>x._pair===i&&x._pairError);if(!cs.length)html+=`<div class="export-row"><div><strong>${esc(p.user?.first_name||p.user?.username||'Telegram')}</strong><small dir="ltr">${p.user?.username?'@'+esc(p.user.username)+' • ':''}${esc(p.user?.id||'')} • ${err?'PAIR ERROR':'Pair OK / منتظر Business Connection'}</small></div><div class="button-row"><button class="ghost-btn" data-cf-pair-remove="${i}">حذف Pair</button></div></div>`;for(const c of cs){const a=active(),isActive=a&&a.pairIndex===i&&a.connectionId===c.id;html+=`<div class="export-row ${isActive?'active-row':''}"><div><strong>${esc(accountLabel(c))}</strong><small dir="ltr">${c.username?'@'+esc(c.username)+' • ':''}${esc(c.user_id)} • ${c.enabled?'CONNECTED':'DISABLED'}</small></div><div class="button-row"><button class="ghost-btn" data-cf-business-active="${i}|${esc(c.id)}">انتخاب</button><button class="ghost-btn" data-cf-business-chats="${i}|${esc(c.id)}">چت‌ها</button><button class="ghost-btn" data-cf-business-test="${i}|${esc(c.id)}">ارسال تست</button><button class="ghost-btn" data-cf-business-label="${i}|${esc(c.id)}">Label</button><button class="danger-btn" data-cf-pair-remove="${i}">حذف Pair</button></div></div>`}}
    list.innerHTML=html||'<div class="empty-state compact">هنوز حسابی Pair نشده است. «Start Bot / افزودن حساب» را بزنید.</div>';
  }
  const sel=$('cf-camp-account');if(sel){const opts=xs.filter(x=>x.id&&x.enabled).map(c=>`<option value="${selectedValue(c._pair,c.id)}">${esc(accountLabel(c))}</option>`);sel.innerHTML=opts.join('');const a=active(),v=a&&selectedValue(a.pairIndex,a.connectionId);if(v&&[...sel.options].some(o=>o.value===v))sel.value=v}
  const caps=$('tg-native-caps');if(caps)caps.innerHTML=`<li><b>✓ Bot Gateway</b><span>${inf?.configured?'@'+esc(inf.botUsername):'setup.php هنوز اجرا نشده'}</span></li><li><b>✓ Pairهای محلی</b><span>${ps.length}/${MAX_PAIRS}</span></li><li><b>✓ Business Connection</b><span>${xs.filter(x=>x.id&&x.enabled).length} فعال</span></li><li><b>✓ ارسال امن</b><span>Promotional فقط Opt-in</span></li>`;
  loadMiniFromGateway(inf);
}
function loadMiniFromGateway(inf){const u=$('cf-mini-url');if(!u)return;const current=localStorage.getItem('cf_mini_url')||'';if(!current&&base()){const x=(inf?.miniAppUrl)||base()+'/miniapp.html';u.value=x;localStorage.setItem('cf_mini_url',x)}const b=$('cf-bot-user');if(b&&inf?.botUsername&&!b.value){b.value=inf.botUsername;localStorage.setItem('cf_bot_user',inf.botUsername)}}
async function openBot(){if(!base())return toast2('ابتدا Gateway URL یا Mini App URL را ثبت کنید.','bad');try{const i=await info();if(!i.configured)return toast2('Mini App آماده است؛ برای ارسال پیام setup.php را روی همان هاست یک‌بار اجرا کنید.','bad');$('cf-pair-row')?.classList.remove('hidden');window.open(`https://t.me/${i.botUsername}?start=pair`,'_blank');$('cf-business-state').textContent='Bot باز شد. کد ۶ رقمی دریافتی را اینجا وارد کنید، سپس Bot را در Telegram Business → Chatbots متصل کنید.'}catch(e){toast2(e.message,'bad')}}
async function submitPair(){const code=String($('cf-pair-code')?.value||'').replace(/\D/g,'');if(code.length!==6)return toast2('کد Pair باید ۶ رقم باشد.','bad');try{const j=await pairCode(code);$('cf-pair-code').value='';$('cf-pair-row').classList.add('hidden');toast2(`Pair شد: ${j.user?.username?'@'+j.user.username:j.user?.first_name||j.user?.id}`);await render()}catch(e){toast2(e.message,'bad')}}
async function showChats(v){const {pairIndex,connectionId}=parseSelected(v);try{const xs=await chats(pairIndex,connectionId),list=$('tg-chat-list');if(list)list.innerHTML=xs.map(x=>`<div class="export-row"><div><strong>${esc([x.first_name,x.last_name].filter(Boolean).join(' ')||x.title||'Chat')}</strong><small dir="ltr">${x.username?'@'+esc(x.username)+' • ':''}${esc(x.chat_id)} • ${x.optin?'OPT-IN':'existing chat'}</small></div><div class="button-row"><button class="ghost-btn" data-cf-chat-test="${pairIndex}|${esc(connectionId)}|${esc(x.chat_id)}">تست</button></div></div>`).join('')||'<div class="empty-state compact">هنوز Business Chat دیده نشده است.</div>'}catch(e){toast2(e.message,'bad')}}
async function sendTest(v,chatId=''){const {pairIndex,connectionId}=parseSelected(v),p=pairs()[pairIndex];if(!p)return toast2('Pair پیدا نشد.','bad');try{let id=chatId;if(!id){const xs=await chats(pairIndex,connectionId);if(!xs.length)return toast2('برای این Connection هنوز چت شناخته‌شده‌ای نیست.','bad');id=xs[0].chat_id}const text=prompt('پیام تست:','✅ پیام تست ContactFlow');if(text===null||!text.trim())return;await request('send_test',{pair:p,method:'POST',body:{connection_id:connectionId,chat_id:id,purpose:'service',text:text.trim()}});toast2('پیام تست با موفقیت ارسال شد.')}catch(e){toast2(e.message,'bad')}}
async function setLabel(v){const {pairIndex,connectionId}=parseSelected(v),label=prompt('نام دلخواه این Connection:','');if(label===null)return;try{await request('set_label',{pair:pairs()[pairIndex],method:'POST',body:{connection_id:connectionId,label}});await render()}catch(e){toast2(e.message,'bad')}}
function removePair(i){const ps=pairs();if(!ps[i])return;if(!confirm('Pair این حساب فقط از ContactFlow محلی حذف شود؟ اتصال Business داخل Telegram تغییر نمی‌کند.'))return;ps.splice(i,1);savePairs(ps);saveActive(null);render()}
async function prepareVcf(){
  try{if(typeof window.setPage==='function')window.setPage('exports');await sleep(120);const f=$('export-format'),c=$('export-chunk'),n=$('export-name'),z=$('export-zip');if(f)f.value='vcf';if(c)c.value='25000';if(n)n.value='telegram_contacts';if(z)z.checked=true;const go=$('start-export');if(go&&confirm('VCF همه مخاطبان مطابق فیلتر فعلی، در قطعه‌های ۲۵هزارتایی ساخته شود؟ بعد از Import در Contacts سیستم، در صورت فعال بودن Contact Sync تلگرام آن‌ها را می‌بیند.')){go.click();toast2('ساخت VCF شروع شد؛ فایل‌ها و ZIP در بخش خروجی ظاهر می‌شوند.')}else toast2('تنظیمات VCF آماده است؛ «ساخت همین خروجی» را بزنید.');}catch(e){toast2(e.message,'bad')}
}
async function dryRunBusiness(){const v=$('cf-camp-account')?.value;if(!v)return toast2('Business Connection انتخاب نشده.','bad');const {pairIndex,connectionId}=parseSelected(v);try{const xs=await chats(pairIndex,connectionId),purpose=$('cf-camp-purpose')?.value||'promotional',eligible=xs.filter(x=>purpose==='service'||x.optin);$('cf-camp-run-state').textContent=`Dry Run Business: چت‌های شناخته‌شده ${xs.length} • قابل ارسال ${eligible.length} • ${purpose==='promotional'?'فقط Opt-in':'Opt-in + Existing Chat'}`;}catch(e){toast2(e.message,'bad')}}
async function sendCampaign(){const v=$('cf-camp-account')?.value;if(!v)return toast2('Business Connection انتخاب نشده.','bad');const {pairIndex,connectionId}=parseSelected(v),ps=pairs(),p=ps[pairIndex];if(!p)return toast2('Pair پیدا نشد.','bad');const purpose=$('cf-camp-purpose')?.value||'promotional',text=String($('camp-text')?.value||'').trim(),cap=Math.max(1,Math.min(500,+$('cf-camp-cap')?.value||80));if(!text)return toast2('متن کمپین خالی است.','bad');if(purpose==='promotional'&&!confirm('ارسال تبلیغاتی فقط به Opt-inهای صریح این Business Connection انجام شود؟'))return;try{const en=await request('campaign_enqueue',{pair:p,method:'POST',body:{connection_id:connectionId,purpose,text,cap}}),jobId=en.job.id;localStorage.setItem('cf_business_job',JSON.stringify({jobId,pairIndex}));$('cf-camp-run-state').textContent=`صف ساخته شد: ${en.job.targets.length} گیرنده`;await pumpJob(p,jobId)}catch(e){$('cf-camp-run-state').textContent=e.message;toast2(e.message,'bad')}}
async function pumpJob(p,jobId){for(let loops=0;loops<10000;loops++){const x=await request('campaign_pump',{pair:p,method:'POST',body:{job_id:jobId}}),j=x.job,total=(j.targets||[]).length||1,done=(j.sent||0)+(j.failed||0)+(j.skipped||0),pct=Math.min(100,Math.round(done/total*100));if($('cf-camp-run-bar'))$('cf-camp-run-bar').style.width=pct+'%';if($('cf-camp-run-state'))$('cf-camp-run-state').textContent=`${j.status} • موفق ${j.sent||0} • خطا ${j.failed||0} • ${done}/${total}${j.next_run>Date.now()/1000?' • در انتظار retry':''}`;if(['done','cancelled'].includes(j.status)){localStorage.removeItem('cf_business_job');toast2('کمپین پایان یافت.');return j}await sleep(x.waiting?3000:900)}}
async function cancelJob(){try{const x=JSON.parse(localStorage.getItem('cf_business_job')||'null');if(!x)return toast2('Job فعالی نیست.','bad');const p=pairs()[x.pairIndex];await request('campaign_cancel',{pair:p,method:'POST',body:{job_id:x.jobId}});localStorage.removeItem('cf_business_job');$('cf-camp-run-state').textContent='کمپین لغو شد.'}catch(e){toast2(e.message,'bad')}}
function bind(){
  gatewayPanel();capabilityPanel();patchTelegramStatic();
  $('cf-business-url')&&($('cf-business-url').value=base());$('cf-business-save')&&($('cf-business-save').onclick=async()=>{try{setBase($('cf-business-url').value);const i=await info();toast2(i.configured?`Gateway @${i.botUsername} آماده است.`:'Mini App URL درست است؛ setup.php برای Bot هنوز اجرا نشده.');await render()}catch(e){toast2(e.message,'bad')}});
  $('cf-business-open-bot')&&($('cf-business-open-bot').onclick=openBot);$('tg-add-account')&&($('tg-add-account').onclick=openBot);$('cf-business-refresh')&&($('cf-business-refresh').onclick=render);$('tg-native-check')&&($('tg-native-check').onclick=render);$('cf-account-refresh')&&($('cf-account-refresh').onclick=render);$('cf-pair-submit')&&($('cf-pair-submit').onclick=submitPair);
  $('tg-account-list')&&($('tg-account-list').onclick=e=>{const a=e.target.closest('[data-cf-business-active]');if(a){const x=parseSelected(a.dataset.cfBusinessActive);saveActive(x);render();return}const c=e.target.closest('[data-cf-business-chats]');if(c){showChats(c.dataset.cfBusinessChats);return}const t=e.target.closest('[data-cf-business-test]');if(t){sendTest(t.dataset.cfBusinessTest);return}const l=e.target.closest('[data-cf-business-label]');if(l){setLabel(l.dataset.cfBusinessLabel);return}const r=e.target.closest('[data-cf-pair-remove]');if(r)removePair(+r.dataset.cfPairRemove)});
  $('cf-load-dialogs')&&($('cf-load-dialogs').onclick=()=>{const a=active();if(a)showChats(selectedValue(a.pairIndex,a.connectionId));else toast2('ابتدا Connection را انتخاب کنید.','bad')});$('tg-chat-list')&&($('tg-chat-list').onclick=e=>{const t=e.target.closest('[data-cf-chat-test]');if(!t)return;const [i,cid,chatId]=String(t.dataset.cfChatTest||'').split('|');sendTest(selectedValue(+i,cid),chatId)});
  $('cf-tg-run-check')&&($('cf-tg-run-check').onclick=prepareVcf);$('cf-camp-dry')&&($('cf-camp-dry').onclick=dryRunBusiness);$('cf-camp-send')&&($('cf-camp-send').onclick=sendCampaign);$('cf-camp-stop')&&($('cf-camp-stop').onclick=cancelJob);
  const old=window.setPage;if(typeof old==='function'&&!old.__cfBusiness){const f=function(p){old(p);if(p==='telegram')setTimeout(()=>{patchTelegramStatic();bindTransient();render()},350);if(p==='miniapp')setTimeout(()=>loadMiniFromGateway(null),200)};f.__cfBusiness=true;window.setPage=f}
}
function bindTransient(){$('tg-add-account')&&($('tg-add-account').onclick=openBot);$('tg-native-check')&&($('tg-native-check').onclick=render);$('cf-tg-run-check')&&($('cf-tg-run-check').onclick=prepareVcf);$('cf-camp-dry')&&($('cf-camp-dry').onclick=dryRunBusiness);$('cf-camp-send')&&($('cf-camp-send').onclick=sendCampaign);$('cf-camp-stop')&&($('cf-camp-stop').onclick=cancelJob)}
async function init(){for(let i=0;i<100;i++){if(document.querySelector('.page[data-page="telegram"]'))break;await sleep(50)}bind();await render();setInterval(()=>{if(document.visibilityState==='visible'&&base())render().catch(()=>{})},15000);console.info('ContactFlow Business Connector ready',VERSION)}
window.ContactFlowBusiness={info,pairCode,listAllConnections,chats,render,diagnostics:()=>({version:VERSION,gateway:base(),pairs:pairs().length,active:active(),mode:'telegram_business_bot'})};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(()=>init().catch(console.error),700));else setTimeout(()=>init().catch(console.error),700);
})();
