(() => {
'use strict';
const VERSION='3.6.0';
const SYNC_NAME='ContactFlow-Ultimate-sync.cfbackup';
const MANIFEST_NAME='ContactFlow-Ultimate-sync.json';
const VISIBLE_PREFIX='ContactFlow-Ultimate-Backup';
const DIR_DB='contactflow_drive_dir_v1';
const DIR_STORE='handles';
const DIR_KEY='backup-dir';
const S={token:null,expiresAt:0,autoTimer:null,lastMeta:null,dir:null};
const q=id=>document.getElementById(id);
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function cfg(){return window.CONTACTFLOW_CONFIG||{}}
function stateText(s){const e=q('drive-state');if(e)e.textContent=s;const m=q('cf-drive-meta');if(m)m.textContent=s}
function pill(ok,text){const e=q('drive-pill');if(e){e.textContent=text||(ok?'Backup Ready':'Backup');e.className='pill '+(ok?'active':'queued')}}
function hasAndroidPicker(){return !!(window.ContactFlowAndroid?.saveDocument)}
function hasDirectoryPicker(){return typeof window.showDirectoryPicker==='function'}
function hasGoogleOAuth(){return !!String(cfg().googleClientId||'').trim()}
async function backupBlob(){for(let i=0;i<120;i++){if(window.ContactFlowFullBackup?.create){const d=await window.ContactFlowFullBackup.create();return new Blob([JSON.stringify(d)],{type:'application/x-contactflow-backup'})}await sleep(50)}throw new Error('Backup engine آماده نشد.')}
async function sha256(blob){const b=await blob.arrayBuffer(),d=await crypto.subtle.digest('SHA-256',b);return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function blobToBase64(blob){return blob.arrayBuffer().then(ab=>{const u=new Uint8Array(ab);let out='';for(let i=0;i<u.length;i+=0x8000)out+=String.fromCharCode(...u.subarray(i,i+0x8000));return btoa(out)})}
async function restoreBlob(blob){if(!window.ContactFlowFullBackup?.restoreBlob)throw new Error('Restore engine آماده نیست.');return window.ContactFlowFullBackup.restoreBlob(blob)}
function idb(){return new Promise((res,rej)=>{const r=indexedDB.open(DIR_DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(DIR_STORE))r.result.createObjectStore(DIR_STORE)};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function saveDirHandle(h){const db=await idb();await new Promise((res,rej)=>{const tx=db.transaction(DIR_STORE,'readwrite');tx.objectStore(DIR_STORE).put(h,DIR_KEY);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});db.close();S.dir=h}
async function loadDirHandle(){if(S.dir)return S.dir;try{const db=await idb();const h=await new Promise((res,rej)=>{const r=db.transaction(DIR_STORE).objectStore(DIR_STORE).get(DIR_KEY);r.onsuccess=()=>res(r.result||null);r.onerror=()=>rej(r.error)});db.close();S.dir=h;return h}catch{return null}}
async function dirPermission(h,ask=false){if(!h)return false;const opts={mode:'readwrite'};if((await h.queryPermission?.(opts))==='granted')return true;if(ask&&(await h.requestPermission?.(opts))==='granted')return true;return false}
async function chooseFolder(){if(!hasDirectoryPicker())throw new Error('انتخاب پوشه دائمی در این مرورگر پشتیبانی نمی‌شود؛ از Backup فایل استفاده کنید.');const h=await showDirectoryPicker({id:'contactflow-backup',mode:'readwrite'});if(!await dirPermission(h,true))throw new Error('مجوز نوشتن پوشه داده نشد.');await saveDirHandle(h);pill(true,'Sync Folder');stateText(`پوشه Backup انتخاب شد: ${h.name}. اگر Google Drive for Desktop دارید، یک پوشه داخل Drive انتخاب کنید.`);return h}
async function getFolder(ask=false){let h=await loadDirHandle();if(!h&&ask)h=await chooseFolder();if(!h)return null;if(!await dirPermission(h,ask))return null;return h}
async function readFileFromDir(h,name){try{const fh=await h.getFileHandle(name);return await fh.getFile()}catch{return null}}
async function writeFileToDir(h,name,blob){const fh=await h.getFileHandle(name,{create:true});const w=await fh.createWritable();await w.write(blob);await w.close();return fh}
async function folderMeta(h){const f=await readFileFromDir(h,MANIFEST_NAME);if(!f)return null;try{return JSON.parse(await f.text())}catch{return null}}
async function folderSync({force=false}={}){
  const h=await getFolder(true);if(!h)throw new Error('ابتدا پوشه Backup را انتخاب کنید.');stateText('در حال ساخت و مقایسه Backup…');const blob=await backupBlob(),hash=await sha256(blob),meta=await folderMeta(h),lastHash=localStorage.getItem('cf_drive_last_hash')||'';
  if(meta?.sha256===hash){pill(true,'Synced');stateText(`Sync کامل است • ${meta.updatedAt||''}`);return meta}
  if(!force&&meta?.sha256&&lastHash&&lastHash!==hash&&meta.sha256!==lastHash){pill(false,'Conflict');stateText('Conflict: هم نسخه محلی و هم فایل پوشه تغییر کرده‌اند. ابتدا Restore یا Backup اجباری را انتخاب کنید.');throw new Error('Backup conflict detected')}
  await writeFileToDir(h,SYNC_NAME,blob);const out={version:VERSION,sha256:hash,size:blob.size,updatedAt:new Date().toISOString(),folder:h.name};await writeFileToDir(h,MANIFEST_NAME,new Blob([JSON.stringify(out,null,2)],{type:'application/json'}));localStorage.setItem('cf_drive_last_hash',hash);localStorage.setItem('cf_drive_last_modified',out.updatedAt);S.lastMeta=out;pill(true,'Synced');stateText(`Backup در پوشه ${h.name} ذخیره شد • ${out.updatedAt}`);return out
}
async function folderRestore(){const h=await getFolder(true);if(!h)throw new Error('پوشه Backup انتخاب نشده است.');const f=await readFileFromDir(h,SYNC_NAME);if(!f)throw new Error(`${SYNC_NAME} در پوشه پیدا نشد.`);await restoreBlob(f);const hash=await sha256(f);localStorage.setItem('cf_drive_last_hash',hash);stateText(`Restore از پوشه ${h.name} انجام شد.`);return true}
async function nativeBackup(){const blob=await backupBlob(),b64=await blobToBase64(blob),name=`${VISIBLE_PREFIX}-${new Date().toISOString().replace(/[:.]/g,'-')}.cfbackup`;window.ContactFlowAndroid.saveDocument(name,blob.type,b64);pill(true,'System Drive');stateText('پنجره ذخیره باز شد؛ Google Drive یا هر Provider دیگر را انتخاب کنید.');return {native:true,name}}
async function downloadBackup(){const blob=await backupBlob(),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${VISIBLE_PREFIX}-${new Date().toISOString().replace(/[:.]/g,'-')}.cfbackup`;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1500);pill(true,'File Backup');stateText('Backup دانلود شد. می‌توانید آن را داخل Google Drive ذخیره کنید.');return {download:true,name:a.download}}
async function pickRestoreFile(){return new Promise((res,rej)=>{const i=document.createElement('input');i.type='file';i.accept='.cfbackup,application/json,application/x-contactflow-backup';i.onchange=async()=>{try{const f=i.files?.[0];if(!f)return res(false);await restoreBlob(f);stateText(`Restore انجام شد: ${f.name}`);res(true)}catch(e){rej(e)}};i.click()})}
async function loadGIS(){if(window.google?.accounts?.oauth2)return;await new Promise((res,rej)=>{const old=document.querySelector('script[data-cf-gis]');if(old){if(window.google?.accounts?.oauth2)return res();old.addEventListener('load',res,{once:true});return}const s=document.createElement('script');s.dataset.cfGis='1';s.src='https://accounts.google.com/gsi/client';s.async=true;s.defer=true;s.onload=res;s.onerror=()=>rej(new Error('Google Identity Services بارگذاری نشد.'));document.head.appendChild(s)})}
async function oauthConnect(interactive=true){const cid=String(cfg().googleClientId||'').trim();if(!cid)throw new Error('Direct Google OAuth اختیاری است و Client ID ندارد. از «انتخاب پوشه Drive» یا Backup فایل استفاده کنید.');if(S.token&&Date.now()<S.expiresAt-60000)return {token:S.token};await loadGIS();return new Promise((res,rej)=>{const c=google.accounts.oauth2.initTokenClient({client_id:cid,scope:'https://www.googleapis.com/auth/drive.appdata https://www.googleapis.com/auth/drive.file',include_granted_scopes:true,callback:r=>{if(r.error)return rej(new Error(r.error_description||r.error));S.token=r.access_token;S.expiresAt=Date.now()+(Number(r.expires_in)||3600)*1000;pill(true,'Drive OAuth');stateText('Google Drive OAuth متصل است.');res({token:S.token})}});c.requestAccessToken({prompt:interactive?'consent':''})})}
async function token(){if(S.token&&Date.now()<S.expiresAt-60000)return S.token;throw new Error('Google OAuth نیاز به اتصال مجدد دارد.')}
async function driveFetch(url,opts={}){const t=await token();const r=await fetch(url,{...opts,headers:{...(opts.headers||{}),Authorization:`Bearer ${t}`}});if(r.status===401){S.token=null;S.expiresAt=0;pill(false,'Reconnect')}return r}
function multipart(meta,blob){const boundary='cf_'+crypto.getRandomValues(new Uint32Array(2)).join('_');return {body:new Blob([`--${boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n${JSON.stringify(meta)}\r\n--${boundary}\r\nContent-Type: ${blob.type||'application/octet-stream'}\r\n\r\n`,blob,`\r\n--${boundary}--`]),type:`multipart/related; boundary=${boundary}`}}
async function listAppData(){const params=new URLSearchParams({spaces:'appDataFolder',q:`name='${SYNC_NAME}' and trashed=false`,fields:'files(id,name,modifiedTime,size,version,appProperties)',orderBy:'modifiedTime desc',pageSize:'10'});const r=await driveFetch('https://www.googleapis.com/drive/v3/files?'+params);if(!r.ok)throw new Error(`Drive list HTTP ${r.status}`);const j=await r.json();S.lastMeta=j.files?.[0]||null;return j.files||[]}
async function oauthUpload(blob,{appData=false,existingId=null}={}){const hash=await sha256(blob),meta={name:appData?SYNC_NAME:`${VISIBLE_PREFIX}-${new Date().toISOString().replace(/[:.]/g,'-')}.cfbackup`,mimeType:'application/x-contactflow-backup',appProperties:{cfSha256:hash,cfVersion:VERSION}};if(appData&&!existingId)meta.parents=['appDataFolder'];const mp=multipart(meta,blob),url=existingId?`https://www.googleapis.com/upload/drive/v3/files/${existingId}?uploadType=multipart&fields=id,name,modifiedTime,size,version,appProperties`:'https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name,modifiedTime,size,version,appProperties';const r=await driveFetch(url,{method:existingId?'PATCH':'POST',headers:{'Content-Type':mp.type},body:mp.body});if(!r.ok)throw new Error(`Drive upload HTTP ${r.status}`);const out=await r.json();localStorage.setItem('cf_drive_last_hash',hash);S.lastMeta=out;return out}
async function oauthSync(){await oauthConnect(false).catch(()=>{});if(!S.token)throw new Error('ابتدا اتصال Google OAuth را بزنید.');const blob=await backupBlob(),hash=await sha256(blob),files=await listAppData(),cloud=files[0]||null,lastHash=localStorage.getItem('cf_drive_last_hash')||'';if(cloud?.appProperties?.cfSha256===hash){pill(true,'Synced');stateText('Drive Sync کامل است.');return cloud}if(cloud&&lastHash&&lastHash!==hash&&cloud.appProperties?.cfSha256!==lastHash){pill(false,'Conflict');throw new Error('Drive conflict detected')}const out=await oauthUpload(blob,{appData:true,existingId:cloud?.id||null});pill(true,'Synced');stateText(`Drive Sync شد • ${out.modifiedTime||''}`);return out}
async function oauthRestore(){await oauthConnect(false).catch(()=>{});if(!S.token)throw new Error('ابتدا Google OAuth را متصل کنید.');const files=await listAppData(),f=files[0];if(!f)throw new Error('Cloud Backup پیدا نشد.');const r=await driveFetch(`https://www.googleapis.com/drive/v3/files/${f.id}?alt=media`);if(!r.ok)throw new Error(`Drive download HTTP ${r.status}`);return restoreBlob(await r.blob())}
async function connect(interactive=true){
  if(hasAndroidPicker()){pill(true,'System Drive');stateText('Android: Backup/Restore با System Document Picker انجام می‌شود؛ Google Drive را از Provider سیستم انتخاب کنید.');return {mode:'android-picker'}}
  if(hasGoogleOAuth()){try{return await oauthConnect(interactive)}catch(e){stateText('OAuth: '+e.message+' — می‌توانید به‌جای آن پوشه Drive را انتخاب کنید.');if(!hasDirectoryPicker())throw e}}
  if(hasDirectoryPicker())return {mode:'sync-folder',handle:await getFolder(interactive)};
  pill(true,'File Backup');stateText('Client ID لازم نیست: Backup فایل دانلود می‌شود و می‌توانید آن را در Google Drive نگه دارید.');return {mode:'file-backup'}
}
async function syncNow(){if(hasAndroidPicker())return nativeBackup();if(S.token&&hasGoogleOAuth())return oauthSync();if(hasDirectoryPicker())return folderSync();return downloadBackup()}
async function backupVisible(){if(hasAndroidPicker())return nativeBackup();if(S.token&&hasGoogleOAuth()){const blob=await backupBlob(),out=await oauthUpload(blob,{appData:false});stateText(`Backup قابل مشاهده در Drive ذخیره شد: ${out.name}`);return out}if(hasDirectoryPicker())return folderSync({force:true});return downloadBackup()}
async function restoreLatest(){if(window.ContactFlowAndroid?.openBackupDocument){window.ContactFlowAndroid.openBackupDocument();stateText('فایل .cfbackup را از Google Drive یا حافظه انتخاب کنید.');return}if(S.token&&hasGoogleOAuth())return oauthRestore();if(hasDirectoryPicker()){const h=await getFolder(false);if(h)return folderRestore()}return pickRestoreFile()}
async function inspectCloud(){if(S.token&&hasGoogleOAuth()){const xs=await listAppData();stateText(xs.length?`Google Cloud: ${xs[0].modifiedTime} • ${xs[0].size||'?'} bytes`:'Google Cloud Backup پیدا نشد.');return xs}if(hasDirectoryPicker()){const h=await getFolder(false);if(!h){stateText('پوشه Sync هنوز انتخاب نشده است.');return []}const m=await folderMeta(h);stateText(m?`Sync Folder: ${h.name} • ${m.updatedAt} • SHA ${(m.sha256||'').slice(0,12)}…`:`Sync Folder: ${h.name} • هنوز Backup ندارد.`);return m?[m]:[]}stateText('حالت File Backup فعال است؛ Cloud API استفاده نمی‌شود.');return []}
function auto(on){localStorage.setItem('cf_drive_auto',on?'1':'0');clearInterval(S.autoTimer);S.autoTimer=null;if(on)S.autoTimer=setInterval(()=>syncNow().catch(e=>stateText('Auto Backup: '+e.message)),15*60*1000)}
function diagnostics(){return {version:VERSION,ready:true,googleOAuthOptional:true,googleClientIdPresent:hasGoogleOAuth(),connectedOAuth:!!S.token,auto:localStorage.getItem('cf_drive_auto')==='1',mode:hasAndroidPicker()?'android-system-picker':S.token?'google-oauth':hasDirectoryPicker()?'sync-folder':'file-backup',folder:S.dir?.name||'',last:S.lastMeta}}
function relabel(){const c=q('drive-connect');if(c)c.textContent=hasGoogleOAuth()?'اتصال Google / انتخاب پوشه':'انتخاب پوشه Drive / Backup';const st=q('drive-state');if(st&&!hasGoogleOAuth())st.textContent=hasAndroidPicker()?'بدون Client ID: از System Picker و Google Drive Provider استفاده می‌شود.':hasDirectoryPicker()?'بدون Client ID: یک پوشه Google Drive for Desktop یا Backup انتخاب کنید.':'بدون Client ID: Backup فایل آماده دانلود/Restore است.'}
function bind(){relabel();const c=q('drive-connect');if(c)c.onclick=async()=>{try{if(!hasGoogleOAuth()&&hasDirectoryPicker())await chooseFolder();else await connect(true)}catch(e){stateText(e.message)}};const b=q('drive-backup');if(b)b.onclick=()=>backupVisible().catch(e=>stateText(e.message));const r=q('drive-restore');if(r)r.onclick=()=>restoreLatest().catch(e=>stateText(e.message));const s=q('cf-drive-auto');if(s)s.onclick=()=>syncNow().catch(e=>stateText(e.message));const cr=q('cf-drive-cloud-restore');if(cr)cr.onclick=()=>restoreLatest().catch(e=>stateText(e.message));const l=q('cf-drive-list');if(l)l.onclick=()=>inspectCloud().catch(e=>stateText(e.message));const t=q('cf-drive-auto-toggle');if(t){t.checked=localStorage.getItem('cf_drive_auto')==='1';t.onchange=()=>auto(t.checked);if(t.checked)auto(true)}}
window.ContactFlowDrive={connect,chooseFolder,syncNow,backupVisible,restoreLatest,inspectCloud,diagnostics};
window.ContactFlowDriveNative={onRestoreFile:async(name,mime,base64)=>{try{const bin=atob(base64),u8=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)u8[i]=bin.charCodeAt(i);await restoreBlob(new Blob([u8],{type:mime||'application/x-contactflow-backup'}));stateText(`Restore انجام شد: ${name||''}`)}catch(e){stateText(e.message)}}};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(bind,350));else setTimeout(bind,350);
})();
