(() => {
'use strict';

const VERSION='3.6.0',MAX_IMPORT_ROWS=500000,MAX_ZIP_BYTES=300*1024*1024,MAX_CHECK_PER_RUN=500;
const E=window.ContactFlowImportMerge;
const FMT=new Intl.NumberFormat('fa-IR');
const S={jobs:[],records:[],photos:[],plan:null,decisions:{},entries:[],busy:false,watchTimer:null,watchHandle:null,lastTelegram:[],deletePreview:null};
const q=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const id=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;
const FEATURES=[
  'تشخیص شهر از نام فایل و فرهنگ شهرهای فارسی','ترانویسی آفلاین نام لاتین به فارسی','Import هم‌زمان چند فایل','Merge خودکار یکپارچه','گزارش جداگانه هر فایل',
  'گزارش تکراری بر اساس شهر','گزارش تکراری نام خانوادگی','گزارش تکراری دامنه ایمیل','ثبت اتمیک و پیش‌نمایش اختیاری','انتخاب نسخه قدیم/جدید/هوشمند برای تعارض',
  'پرکردن فیلد خالی بدون Overwrite','شماره‌گذاری مجدد پس از پاک‌سازی','Undo مستقل هر Import','Rollback کامل آخرین Merge','برچسب منبع و فایل روی مخاطب',
  'تشخیص شهر تلفن ثابت ایران','تشخیص کشور از Calling Code','استانداردسازی E.164','پاک‌سازی فاصله و کاراکتر شماره','تفکیک نام شرکت',
  'نمودار تعداد مخاطب هر شهر','مقایسه قبل از Merge','خروجی فقط رکوردهای جدید','جستجو بر اساس Import/منبع','حذف گروهی امن یک منبع',
  'یادداشت خودکار تاریخ و فایل','تفکیک موبایل/تلفن ثابت','اعتبارسنجی طول شماره بر اساس کشور','ZIP مخاطب و عکس','OCR کارت ویزیت با قابلیت دستگاه',
  'نمایش اختیاری اعداد فارسی','مرتب‌سازی پیش‌فرض بر اساس شهر','گزارش Excel و چاپ PDF','Watch Folder با اجازه کاربر هنگام اجرای اپ','هشدار فایل خراب یا نامعتبر',
  'XLS/XLSX کامل با Parser سبک و SheetJS','Drag & Drop چندفایلی','Progress زنده فایل بزرگ','Contact Picker انتخابی وب','دفترچه کامل Android با مجوز صریح',
  'Telegram Desktop Export بدون API','خروجی Telegram VCF و CSV','برچسب وضعیت Telegram در دیتابیس','جستجوی مخاطبین Export تلگرام','Import محلی Telegram',
  'هسته مشترک Mini App/PWA/Desktop/Android','Web Share مستقیم روی گوشی','همگام‌سازی وضعیت Telegram داخل Backup محلی','بروزرسانی یک‌کلیک دسته بعدی','سقف خودکار ۵۰۰ بررسی در اجرا',
  'گزارش نهایی یک‌صفحه‌ای','محافظت Formula Injection خروجی','محدودیت ZIP Bomb و فایل حجیم','ثبت Audit محلی','Diagnostics قابلیت هر دستگاه'
];

function notify(message,type='good',timeout=5200){try{return toast(message,type,timeout)}catch{console[type==='bad'?'error':'info'](message)}}
async function waitCore(){for(let i=0;i<300;i++){try{if(state?.db&&E)return}catch{}await sleep(50)}throw new Error('هسته مشترک ۳.۶ آماده نشد.')}
function txStore(name,mode='readonly'){return state.db.transaction(name,mode).objectStore(name)}
function request(req){return new Promise((resolve,reject)=>{req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
function all(name){return request(txStore(name).getAll()).then(rows=>rows||[])}
function cleanRecord(row){const out={};for(const [key,value] of Object.entries(row||{}))if(!key.startsWith('_'))out[key]=value;return out}
function runtimeKind(){if(window.Telegram?.WebApp?.initData)return 'telegram-miniapp';if(window.ContactFlowAndroid)return 'android';if(location.hostname==='localhost'||location.hostname==='127.0.0.1')return 'desktop';return matchMedia('(display-mode: standalone)').matches?'pwa':'web'}
function reportLine(label,value){return `<div class="cf34-report-line"><span>${esc(label)}</span><strong>${esc(value)}</strong></div>`}
function formatStatus(status){return ({matched:'تلگرام‌دار ✓',not_returned:'برنگشته/نامشخص',retry:'نیازمند تلاش دوباره',unchecked:'بررسی‌نشده'})[status]||status||'بررسی‌نشده'}

function addNavigation(){
  const nav=q('nav');if(nav&&!q('cf34-nav')){const b=document.createElement('button');b.id='cf34-nav';b.className='nav-item';b.dataset.page='smart-import';b.innerHTML='⌁ <span>Import اتمیک ۳.۶</span>';nav.insertBefore(b,nav.querySelector('[data-page="contacts"]'))}
  const bottom=q('bottom-nav');if(bottom&&!bottom.querySelector('[data-page="smart-import"]')){const b=document.createElement('button');b.dataset.page='smart-import';b.innerHTML='⌁<span>Merge</span>';bottom.appendChild(b)}
  try{pageMeta['smart-import']=['Import و Merge هوشمند','تحلیل، مقایسه، پاک‌سازی، Telegram Check و خروجی یکپارچه']}catch{}
}
function pageMarkup(){return `
<section class="page cf34-page" data-page="smart-import">
  <article class="panel callout"><div><strong>مرکز یکپارچه Import و Merge نسخه ۳.۶</strong><p>حالت پیش‌فرض اتمیک است: تحلیل، Merge، ثبت و راستی‌آزمایی مخاطبین با یک دکمه. برای دیدن گزارش بدون ثبت، «فقط پیش‌نمایش» را روشن کنید.</p></div><span class="pill active">${esc(runtimeKind())} • Local-First</span></article>
  <div class="layout-2 wide-left">
    <article class="panel form-panel"><div class="panel-head"><div><h2>۱. منابع ورودی</h2><p>CSV / TSV / TXT / VCF / JSON / XLS / XLSX / ZIP + عکس</p></div><span id="cf34-file-count" class="pill queued">۰ فایل</span></div>
      <label id="cf34-drop" class="dropzone cf34-drop"><input id="cf34-files" type="file" multiple accept=".csv,.tsv,.txt,.vcf,.json,.xls,.xlsx,.zip"><strong>فایل‌ها را بکشید یا انتخاب کنید</strong><span>۲، ۳، ۴ فایل یا بیشتر؛ Merge در یک فهرست</span></label>
      <div class="button-row"><button id="cf34-contact-picker" class="ghost-btn">انتخاب مخاطب گوشی (وب)</button><button id="cf34-android-contacts" class="ghost-btn">دفترچه Android</button><button id="cf34-ocr" class="ghost-btn">OCR کارت ویزیت</button><input id="cf34-ocr-file" class="hidden" type="file" accept="image/*"><button id="cf34-watch" class="ghost-btn">انتخاب Watch Folder</button><button id="cf34-watch-scan" class="ghost-btn">اسکن پوشه</button></div>
      <p id="cf34-device-note" class="hint"></p><div id="cf34-queue" class="cf34-queue"><div class="empty-state compact">هنوز منبعی انتخاب نشده است.</div></div>
    </article>
    <article class="panel form-panel"><div class="panel-head"><div><h2>۲. سیاست Merge</h2><p>تصمیم پیش‌فرض برای شماره یا ایمیل تکراری</p></div><span class="pill active">Dry-run</span></div>
      <div class="form-grid"><label><span>حالت تعارض</span><select id="cf34-mode"><option value="smart">هوشمند: فقط فیلد خالی تکمیل شود</option><option value="old">نسخه قدیمی حفظ شود</option><option value="new">نسخه جدید جایگزین شود</option><option value="manual">انتخاب دستی هر تعارض</option></select></label><label><span>کشور پیش‌فرض شماره محلی</span><select id="cf34-country"><option value="IR">ایران (+98)</option><option value="">فقط کد بین‌المللی</option></select></label></div>
      <label class="switch-row"><input id="cf34-dry" type="checkbox"><span class="switch"></span><div><strong>فقط پیش‌نمایش (بدون ثبت)</strong><small>خاموش = تحلیل و ثبت مستقیم در مخاطبین؛ روشن = فقط گزارش.</small></div></label>
      <label class="switch-row"><input id="cf34-fa-digits" type="checkbox"><span class="switch"></span><div><strong>نمایش شماره با اعداد فارسی</strong><small>مقدار ذخیره‌شده همیشه E.164 لاتین می‌ماند.</small></div></label>
      <div class="button-row"><button id="cf34-analyze" class="primary-btn">تحلیل و ثبت در مخاطبین</button><button id="cf34-commit" class="primary-soft" disabled>ثبت نتیجه پیش‌نمایش</button><button id="cf34-reset" class="danger-btn">پاک‌کردن صف</button></div>
      <div class="progress-block"><div class="progress-line"><span id="cf34-progress-label">آماده</span><strong id="cf34-progress-pct">۰٪</strong></div><div class="progress-track"><i id="cf34-progress-bar"></i></div><small id="cf34-progress-detail"></small></div>
    </article>
  </div>
  <div id="cf34-result" class="hidden">
    <div class="metrics-grid cf34-metrics"><article class="metric-card"><span>ورودی</span><strong id="cf34-total">۰</strong></article><article class="metric-card"><span>جدید</span><strong id="cf34-added">۰</strong></article><article class="metric-card"><span>تکراری</span><strong id="cf34-duplicates">۰</strong></article><article class="metric-card"><span>تکمیل فیلد</span><strong id="cf34-updated">۰</strong></article><article class="metric-card"><span>نامعتبر</span><strong id="cf34-invalid">۰</strong></article><article class="metric-card"><span>فارسی‌سازی</span><strong id="cf34-persianized">۰</strong></article></div>
    <div class="layout-2"><article class="panel"><div class="panel-head"><div><h2>مقایسه و تعارض‌ها</h2><p id="cf34-compare-summary"></p></div></div><div class="table-wrap"><table><thead><tr><th>شماره</th><th>نسخه قدیم</th><th>نسخه جدید</th><th>تصمیم</th></tr></thead><tbody id="cf34-conflicts"></tbody></table></div></article><article class="panel"><div class="panel-head"><div><h2>نمودار شهرها</h2><p>خروجی نهایی پس از Merge</p></div></div><div id="cf34-city-chart" class="cf34-chart"></div></article></div>
    <div class="layout-2"><article class="panel"><div class="panel-head"><div><h2>گزارش به‌تفکیک فایل</h2><p>جدید، بروزرسانی، تکراری و نامعتبر</p></div></div><div id="cf34-source-report"></div></article><article class="panel"><div class="panel-head"><div><h2>گزارش تکراری‌ها</h2><p>شهر / نام خانوادگی / دامنه ایمیل</p></div></div><div id="cf34-duplicate-report"></div></article></div>
    <article id="cf34-print-report" class="panel"><div class="panel-head"><div><h2>گزارش نهایی یک‌صفحه‌ای</h2><p id="cf34-final-time"></p></div></div><div id="cf34-final-report" class="cf34-report-grid"></div><div class="button-row cf34-no-print"><button id="cf34-export-new" class="primary-soft">خروجی فقط جدیدها</button><button id="cf34-report-xls" class="ghost-btn">گزارش Excel</button><button id="cf34-report-pdf" class="ghost-btn">چاپ / ذخیره PDF</button><button id="cf34-share-report" class="ghost-btn">Web Share گزارش</button><button id="cf34-renumber" class="ghost-btn">شماره‌گذاری مجدد</button><button id="cf34-rollback" class="danger-btn">Rollback آخرین Merge</button></div></article>
  </div>
  <div class="layout-2">
    <article class="panel form-panel"><div class="panel-head"><div><h2>بررسی وضعیت Telegram</h2><p>User Session رسمی؛ هر اجرا حداکثر ۵۰۰ شماره و پاک‌سازی Contact موقت</p></div><span id="cf34-tg-percent" class="pill queued">۰٪ matched</span></div><div class="form-grid"><label><span>سقف این اجرا</span><input id="cf34-tg-cap" type="number" min="10" max="500" value="200"></label><label><span>اندازه Batch</span><input id="cf34-tg-batch" type="number" min="10" max="500" value="100"></label></div><div class="button-row"><button id="cf34-tg-check" class="primary-btn">بروزرسانی دسته بعدی</button><button id="cf34-tg-matched" class="ghost-btn">خروجی تلگرام‌دار</button><button id="cf34-tg-unmatched" class="ghost-btn">خروجی برنگشته/نامشخص</button></div><div id="cf34-tg-state" class="hint">Not-returned به‌دلیل تنظیمات Privacy الزاماً اثبات «نداشتن تلگرام» نیست.</div></article>
    <article class="panel form-panel"><div class="panel-head"><div><h2>پاک‌سازی منبع</h2><p>پیش‌نمایش قبل از حذف و Undo هر Import</p></div></div><label><span>فایل/منبع</span><select id="cf34-source-select"><option value="">انتخاب کنید</option></select></label><div class="button-row"><button id="cf34-preview-delete" class="ghost-btn">پیش‌نمایش حذف</button><button id="cf34-delete-source" class="danger-btn" disabled>حذف موارد پیش‌نمایش</button></div><div id="cf34-delete-state" class="hint"></div></article>
  </div>
  <article class="panel"><div class="panel-head"><div><h2>تاریخچه Import و Merge</h2><p>Undo مستقل فایل و وضعیت Rollback</p></div><button id="cf34-history-refresh" class="ghost-btn">بروزرسانی</button></div><div class="table-wrap"><table><thead><tr><th>فایل</th><th>جدید</th><th>تکراری</th><th>زمان</th><th>وضعیت</th><th>عملیات</th></tr></thead><tbody id="cf34-history"></tbody></table></div></article>
  <details class="panel"><summary>قابلیت‌های مشترک فعال نسخه ۳.۶ (${FEATURES.length})</summary><div class="feature-grid">${FEATURES.map(name=>`<div class="feature-item"><span>✓</span><div><strong>${esc(name)}</strong><small>shared core / capability-gated</small></div></div>`).join('')}</div></details>
</section>`}
function addPage(){if(!document.querySelector('.page[data-page="smart-import"]'))document.querySelector('main.main')?.insertAdjacentHTML('beforeend',pageMarkup())}

function patchRouting(){
  const previous=window.setPage;if(typeof previous==='function'&&!previous.__cf34){const wrapped=function(page){previous(page);document.querySelectorAll('.page').forEach(el=>el.classList.toggle('active',el.dataset.page===page));document.querySelectorAll('[data-page]').forEach(el=>el.classList.toggle('active',el.dataset.page===page));if(page==='smart-import'){refreshHistory();refreshTelegramStats()}};wrapped.__cf34=true;window.setPage=wrapped}
  document.addEventListener('click',event=>{const b=event.target.closest?.('[data-page="smart-import"]');if(b){event.preventDefault();window.setPage('smart-import')}});
}
function progress(percent,label,detail=''){q('cf34-progress-bar').style.width=`${Math.max(0,Math.min(100,percent))}%`;q('cf34-progress-pct').textContent=`${FMT.format(Math.round(percent))}٪`;q('cf34-progress-label').textContent=label;q('cf34-progress-detail').textContent=detail}
function setBusy(value){S.busy=value;['cf34-analyze','cf34-reset','cf34-contact-picker','cf34-android-contacts','cf34-ocr','cf34-watch'].forEach(key=>{if(q(key))q(key).disabled=value});updateCommitState()}
function updateCommitState(){if(!q('cf34-commit'))return;q('cf34-commit').disabled=S.busy||!S.plan||q('cf34-dry').checked}

async function validateFile(file){
  if(!file||!file.name)throw new Error('فایل بدون نام است.');if(!file.size)throw new Error(`${file.name}: فایل خالی است.`);if(file.size>250*1024*1024)throw new Error(`${file.name}: بیش از سقف امن ۲۵۰MB است.`);
  const ext=file.name.split('.').pop().toLowerCase(),allowed=['csv','tsv','txt','vcf','json','xls','xlsx','zip'];if(!allowed.includes(ext))throw new Error(`${file.name}: فرمت ${ext} در صف داده پشتیبانی نمی‌شود؛ برای تصویر از دکمه OCR استفاده کنید.`);
  const sig=new Uint8Array(await file.slice(0,8).arrayBuffer());if(['xlsx','zip'].includes(ext)&&!(sig[0]===0x50&&sig[1]===0x4b))throw new Error(`${file.name}: ساختار ZIP/XLSX خراب یا نامعتبر است.`);
  return ext;
}
function makeJob(file,overrides={}){const city=E.inferCityFromFilename(file.name);return {id:id(),file,name:file.name,size:file.size,city,source:file.name,section:'',status:'queued',rows:0,error:'',...overrides}}
async function addFiles(files,{silent=false}={}){for(const file of [...(files||[])]){try{await validateFile(file);S.jobs.push(makeJob(file))}catch(error){notify(error.message,'bad',8000)}}renderQueue();if(!silent&&S.jobs.length)notify(`${FMT.format(S.jobs.length)} فایل در صف تحلیل است.`)}
function renderQueue(){
  q('cf34-file-count').textContent=`${FMT.format(S.jobs.length)} منبع`;if(!S.jobs.length){q('cf34-queue').innerHTML='<div class="empty-state compact">هنوز منبعی انتخاب نشده است.</div>';return}
  q('cf34-queue').innerHTML=S.jobs.map(job=>`<div class="queue-card" data-cf34-job="${esc(job.id)}"><div class="queue-head"><div><strong>${esc(job.name)}</strong><small>${esc(formatBytes(job.size||0))}${job.rows?` • ${FMT.format(job.rows)} رکورد`:''}</small></div><span class="pill ${job.status==='error'?'danger':job.status==='parsed'?'active':'queued'}">${esc(job.status)}</span><button class="danger-btn" data-cf34-remove>حذف</button></div><div class="form-grid queue-grid"><label><span>شهر تشخیص‌داده‌شده</span><input data-cf34-field="city" value="${esc(job.city)}" placeholder="خودکار از شماره/نام فایل"></label><label><span>منبع</span><input data-cf34-field="source" value="${esc(job.source)}"></label><label><span>بخش</span><input data-cf34-field="section" value="${esc(job.section)}"></label></div>${job.error?`<small class="queue-error">${esc(job.error)}</small>`:''}</div>`).join('');
  q('cf34-queue').querySelectorAll('[data-cf34-job]').forEach(card=>{const job=S.jobs.find(x=>x.id===card.dataset.cf34Job);card.querySelectorAll('[data-cf34-field]').forEach(input=>input.oninput=()=>job[input.dataset.cf34Field]=input.value);card.querySelector('[data-cf34-remove]').onclick=()=>{S.jobs=S.jobs.filter(x=>x.id!==job.id);S.plan=null;renderQueue();updateCommitState()}})
}

async function rowsFromGenerator(generator,job){
  const iterator=generator[Symbol.asyncIterator](),first=await iterator.next();if(first.done)return[];const second=await iterator.next(),header=looksLikeHeader(first.value),headers=header?cleanHeaders(first.value):first.value.map((_,i)=>`col${i+1}`),rows=[];
  async function consume(values){if(rows.length>=MAX_IMPORT_ROWS)throw new Error(`سقف امن ${MAX_IMPORT_ROWS.toLocaleString('en-US')} ردیف در هر تحلیل رد شد.`);let raw=E.rowToObject(headers,values);if(!raw.phone){const index=resolvePhoneIndex(headers,'',values);raw.phone=values[index]??''}if(!raw.name&&values.length>1){const idx=headers.findIndex(h=>/name|نام/i.test(h));if(idx>=0)raw.name=values[idx]}
    const record=E.normalizeRecord(raw,{filename:job.name,source:job.source,city:job.city,section:job.section,importId:job.id,rowNumber:rows.length+1,defaultCountry:q('cf34-country').value||'IR',sourcePolicy:window.ContactFlow35?.sourcePolicy?.()});rows.push(record);if(rows.length%2000===0){progress(Math.min(88,10+Math.log10(rows.length+10)*16),`خواندن ${job.name}`,`${FMT.format(rows.length)} ردیف`);await sleep(0)}}
  if(!header)await consume(first.value);if(!second.done)await consume(second.value);while(true){const next=await iterator.next();if(next.done)break;await consume(next.value)}return rows;
}
async function parseDelimitedJob(job){const delimiter=await detectDelimiter(job.file),gen=parseDelimited(job.file,delimiter,pct=>progress(Math.min(88,pct*.85),`خواندن ${job.name}`,`${FMT.format(job.rows||0)} ردیف`));return rowsFromGenerator(gen,job)}
async function sheetJsRows(job){
  for(let i=0;i<120;i++){
    if(window.ContactFlowSpreadsheet?.readRows){progress(8,`خواندن Excel: ${job.name}`,'راه‌اندازی Parser کامل');return window.ContactFlowSpreadsheet.readRows(await job.file.arrayBuffer(),{maxRows:MAX_IMPORT_ROWS})}
    await sleep(50);
  }
  throw new Error('Parser کامل Excel داخل Bundle در دسترس نیست.');
}
async function parseXlsxJob(job){
  try{return await rowsFromGenerator(parseXlsx(job.file,(pct,count)=>progress(Math.min(90,pct),`خواندن Excel: ${job.name}`,`${FMT.format(count||0)} ردیف`)),job)}
  catch(error){console.warn('Lightweight XLSX parser fallback:',error);return rowsFromArray(await sheetJsRows(job),job)}
}
function htmlTableRows(text){const doc=new DOMParser().parseFromString(text,'text/html');return [...doc.querySelectorAll('tr')].map(tr=>[...tr.querySelectorAll('th,td')].map(td=>td.textContent.trim())).filter(row=>row.length)}
async function rowsFromArray(rawRows,job){if(!rawRows.length)return[];async function* gen(){for(const row of rawRows)yield row}return rowsFromGenerator(gen(),job)}
async function parseJsonJob(job){const data=JSON.parse(await job.file.text()),list=Array.isArray(data)?data:Array.isArray(data.contacts)?data.contacts:[];if(!list.length)throw new Error('JSON باید آرایه مخاطبین یا contacts[] داشته باشد.');return list.slice(0,MAX_IMPORT_ROWS).map((raw,index)=>E.normalizeRecord(raw,{filename:job.name,source:job.source,city:job.city,section:job.section,importId:job.id,rowNumber:index+1,defaultCountry:q('cf34-country').value||'IR',sourcePolicy:window.ContactFlow35?.sourcePolicy?.()}))}
async function parseVcfJob(job){return E.parseVCard(await job.file.text()).map((raw,index)=>E.normalizeRecord(raw,{filename:job.name,source:job.source,city:job.city,section:job.section,importId:job.id,rowNumber:index+1,defaultCountry:q('cf34-country').value||'IR',sourcePolicy:window.ContactFlow35?.sourcePolicy?.()}))}
async function parseXlsJob(job){const sig=new Uint8Array(await job.file.slice(0,8).arrayBuffer());if(sig[0]===0xd0&&sig[1]===0xcf)return rowsFromArray(await sheetJsRows(job),job);const text=await job.file.text(),rows=/<Workbook|<Worksheet|<Row/i.test(text)?E.parseSpreadsheetXml(text):htmlTableRows(text);if(rows.length)return rowsFromArray(rows,job);return rowsFromArray(await sheetJsRows(job),job)}
async function parseZipJob(job){
  const zip=await openZip(job.file),entries=zip.entries.filter(entry=>!entry.name.endsWith('/'));if(entries.length>5000)throw new Error('ZIP بیش از ۵۰۰۰ ورودی دارد.');const total=entries.reduce((sum,e)=>sum+e.uncomp,0);if(total>MAX_ZIP_BYTES)throw new Error('حجم بازشده ZIP بیش از سقف امن ۳۰۰MB است.');if(entries.some(e=>e.comp>0&&e.uncomp/e.comp>120))throw new Error('ZIP مشکوک به Zip Bomb است.');
  const records=[];for(let i=0;i<entries.length;i++){const entry=entries[i],name=entry.name.split('/').pop(),ext=name.split('.').pop().toLowerCase();if(!name)continue;const blob=await new Response(zip.streamEntry(entry)).blob(),file=new File([blob],name,{type:blob.type,lastModified:job.file.lastModified});if(/^(jpg|jpeg|png|webp)$/i.test(ext)){S.photos.push({id:id(),name,blob:file,importId:job.id});continue}if(!['csv','tsv','txt','vcf','json','xls','xlsx'].includes(ext))continue;const child=makeJob(file,{id:job.id,name,source:job.source,city:job.city,section:job.section});records.push(...await parseOne(child,false));progress(10+(i+1)/entries.length*78,`بازکردن ZIP: ${job.name}`,`${i+1}/${entries.length}`)}return records;
}
async function parseOne(job,allowZip=true){const ext=job.name.split('.').pop().toLowerCase();if(['csv','tsv','txt'].includes(ext))return parseDelimitedJob(job);if(ext==='xlsx')return parseXlsxJob(job);if(ext==='xls')return parseXlsJob(job);if(ext==='vcf')return parseVcfJob(job);if(ext==='json')return parseJsonJob(job);if(ext==='zip'&&allowZip)return parseZipJob(job);throw new Error(`Parser برای ${ext} فعال نیست.`)}

async function analyze(){
  if(S.busy)return;if(!S.jobs.length)return notify('ابتدا حداقل یک فایل یا منبع اضافه کنید.','bad');setBusy(true);S.records=[];S.photos=[];S.decisions={};S.plan=null;q('cf34-result').classList.add('hidden');
  try{for(let i=0;i<S.jobs.length;i++){const job=S.jobs[i];job.status='reading';job.error='';renderQueue();progress(i/S.jobs.length*80,`تحلیل ${job.name}`,`${i+1}/${S.jobs.length}`);try{const rows=await parseOne(job);job.rows=rows.length;job.status='parsed';S.records.push(...rows)}catch(error){job.status='error';job.error=error.message;notify(`${job.name}: ${error.message}`,'bad',9000)}renderQueue()}
    if(!S.records.length)throw new Error('هیچ رکورد قابل تحلیلی پیدا نشد.');progress(88,'مقایسه با دیتابیس محلی',`${FMT.format(S.records.length)} رکورد`);const existing=await all('contacts'),mode=q('cf34-mode').value==='manual'?'smart':q('cf34-mode').value;S.plan=E.planMerge(existing,S.records,{defaultMode:mode,decisions:S.decisions,dryRun:true});renderPlan(existing);q('cf34-result').classList.remove('hidden');await audit('import-analysis','تحلیل Merge انجام شد',S.plan.report);if(!q('cf34-dry').checked&&q('cf34-mode').value!=='manual')await commit({skipConfirm:true});else{progress(100,'پیش‌نمایش کامل شد','برای ثبت، حالت پیش‌نمایش را خاموش و دکمه ثبت نتیجه را بزنید.');q('cf34-result').scrollIntoView({behavior:'smooth',block:'start'})}
  }catch(error){notify(error.message,'bad',9000);progress(0,'تحلیل ناموفق',error.message)}finally{setBusy(false)}
}
function renderPlan(existing=[]){
  const r=S.plan.report;q('cf34-total').textContent=FMT.format(r.total);q('cf34-added').textContent=FMT.format(r.added);q('cf34-duplicates').textContent=FMT.format(r.duplicates);q('cf34-updated').textContent=FMT.format(r.updated);q('cf34-invalid').textContent=FMT.format(r.invalid);q('cf34-persianized').textContent=FMT.format(r.persianized);
  q('cf34-compare-summary').textContent=`قدیمی ${FMT.format(existing.length||Math.max(0,S.plan.records.length-r.added))} • ورودی ${FMT.format(r.total)} • جدید ${FMT.format(r.added)} • تعارض ${FMT.format(r.duplicates)}`;
  const conflicts=S.plan.actions.filter(a=>a.before).slice(0,250);q('cf34-conflicts').innerHTML=conflicts.length?conflicts.map(a=>`<tr><td dir="ltr">${esc(a.incoming.phone)}</td><td>${esc(a.before.name||'—')}<small>${esc(a.before.city||'')}</small></td><td>${esc(a.incoming.name||'—')}<small>${esc(a.incoming.city||'')}</small></td><td><select data-cf34-decision="${esc(a.incoming.phone)}"><option value="smart" ${(S.decisions[a.incoming.phone]||a.mode)==='smart'?'selected':''}>تکمیل هوشمند</option><option value="old" ${(S.decisions[a.incoming.phone]||a.mode)==='old'?'selected':''}>قدیمی</option><option value="new" ${(S.decisions[a.incoming.phone]||a.mode)==='new'?'selected':''}>جدید</option></select></td></tr>`).join(''):'<tr><td colspan="4">تعارضی پیدا نشد.</td></tr>';
  q('cf34-conflicts').querySelectorAll('[data-cf34-decision]').forEach(select=>select.onchange=async()=>{S.decisions[select.dataset.cf34Decision]=select.value;const old=await all('contacts');S.plan=E.planMerge(old,S.records,{defaultMode:q('cf34-mode').value==='manual'?'smart':q('cf34-mode').value,decisions:S.decisions,dryRun:true});renderPlan(old)});
  const cities={};for(const row of S.plan.records)cities[row.city]=(cities[row.city]||0)+1;const ordered=Object.entries(cities).sort((a,b)=>b[1]-a[1]).slice(0,18),max=ordered[0]?.[1]||1;q('cf34-city-chart').innerHTML=ordered.map(([city,count])=>`<div class="cf34-bar"><span>${esc(city)}</span><i><b style="width:${Math.max(2,count/max*100)}%"></b></i><strong>${FMT.format(count)}</strong></div>`).join('')||'<div class="empty-state compact">داده‌ای نیست.</div>';
  q('cf34-source-report').innerHTML=Object.entries(r.bySource).map(([source,s])=>`<div class="cf34-source"><strong>${esc(source)}</strong><small>ورودی ${FMT.format(s.rows)} • جدید ${FMT.format(s.added)} • تکمیل ${FMT.format(s.updated)} • تکراری ${FMT.format(s.duplicates)} • نامعتبر ${FMT.format(s.invalid)}</small></div>`).join('');
  const group=(title,obj)=>`<div class="cf34-dups"><strong>${title}</strong>${Object.entries(obj||{}).sort((a,b)=>b[1]-a[1]).slice(0,12).map(([key,n])=>`<span>${esc(key)} <b>${FMT.format(n)}</b></span>`).join('')||'<small>موردی نیست</small>'}</div>`;q('cf34-duplicate-report').innerHTML=group('شهر',r.duplicatesByCity)+group('نام خانوادگی',r.duplicatesBySurname)+group('دامنه ایمیل',r.duplicatesByEmailDomain);
  q('cf34-final-time').textContent=`${new Date().toLocaleString('fa-IR')} • ${runtimeKind()}`;q('cf34-final-report').innerHTML=reportLine('فایل‌ها',S.jobs.length)+reportLine('ردیف ورودی',FMT.format(r.total))+reportLine('افزوده',FMT.format(r.added))+reportLine('فیلد تکمیل‌شده',FMT.format(r.updated))+reportLine('تکراری',FMT.format(r.duplicates))+reportLine('نامعتبر',FMT.format(r.invalid))+reportLine('فارسی‌سازی',FMT.format(r.persianized))+reportLine('موبایل',FMT.format(r.phoneTypes.mobile||0))+reportLine('تلفن ثابت',FMT.format(r.phoneTypes.landline||0))+reportLine('عکس ZIP',FMT.format(S.photos.length));updateCommitState()
}

async function photoRows(mergeId){const rows=[];for(const photo of S.photos){const base=photo.name.replace(/\.[^.]+$/,''),phone=E.normalizePhone(base)?.e164,key=E.keyText(base),contact=S.plan.records.find(row=>phone?row.phone===phone:E.keyText(row.name)===key);rows.push({...photo,phone:contact?.phone||'',mergeId,createdAt:Date.now()})}return rows}
async function commit({skipConfirm=false}={}){
  if(!S.plan||q('cf34-dry').checked)return notify('برای ثبت، گزینه «فقط پیش‌نمایش» را خاموش کنید.','bad');if(!skipConfirm&&!confirm(`Merge ثبت شود؟ جدید ${S.plan.report.added} • تکمیل ${S.plan.report.updated} • تکراری ${S.plan.report.duplicates}`))return;setBusy(true);const mergeId=`merge-${id()}`,now=Date.now();
  try{const images=await photoRows(mergeId),stores=['contacts','merge_runs','imports',...(images.length?['contact_images']:[])],tx=state.db.transaction(stores,'readwrite'),contacts=tx.objectStore('contacts');for(const action of S.plan.actions){if(action.type==='add')contacts.put(cleanRecord(action.after));if(action.type==='update'){if(action.before.phone!==action.after.phone)contacts.delete(action.before.phone);contacts.put(cleanRecord(action.after))}}
    const run={id:mergeId,version:VERSION,type:'merge',status:'committed',createdAt:now,files:S.jobs.map(j=>({id:j.id,name:j.name,source:j.source,rows:j.rows})),report:S.plan.report,actions:S.plan.actions.filter(a=>['add','update','skip'].includes(a.type)),undoneImportIds:[]};tx.objectStore('merge_runs').put(run);
    for(const job of S.jobs){const xs=S.plan.actions.filter(a=>a.incoming?.importIds?.includes(job.id)),row={id:job.id,filename:job.name,city:job.city||'خودکار',section:job.section,source:job.source,rows:job.rows,added:xs.filter(a=>a.type==='add').length,updated:xs.filter(a=>a.type==='update').length,duplicates:xs.filter(a=>a.before).length,invalid:S.records.filter(x=>x.importIds?.includes(job.id)&&!x._valid).length,mergeId,status:'committed',createdAt:now};tx.objectStore('imports').put(row)}
    if(images.length){const imageStore=tx.objectStore('contact_images');for(const row of images)imageStore.put(row)}await txDone(tx);await rebuildStats();await fillCitySelects();touchRevision();const saved=(await all('contacts')).length;progress(100,'ثبت و راستی‌آزمایی شد',`${FMT.format(saved)} مخاطب اکنون در دیتابیس`);notify(`نسخه ۳.۶: ${FMT.format(S.plan.report.added)} مخاطب افزوده و ثبت آن راستی‌آزمایی شد.`);await audit('merge-commit','Merge اتمیک و راستی‌آزمایی شد',{mergeId,saved,...S.plan.report});await refreshHistory();await refreshTelegramStats();if(typeof refreshContacts==='function')await refreshContacts();if(skipConfirm)setTimeout(()=>window.setPage?.('contacts'),650)
  }catch(error){notify(`ثبت Merge ناموفق: ${error.message}`,'bad',9000)}finally{setBusy(false)}
}

async function latestRun(){const rows=await all('merge_runs');return rows.filter(r=>r.status==='committed').sort((a,b)=>b.createdAt-a.createdAt)[0]||null}
async function rollbackLast(){const run=await latestRun();if(!run)return notify('Merge ثبت‌شده‌ای برای Rollback وجود ندارد.','bad');if(!confirm(`Rollback کامل ${run.files.map(x=>x.name).join('، ')} انجام شود؟`))return;setBusy(true);try{const names=['contacts','merge_runs','imports','contact_images'],tx=state.db.transaction(names,'readwrite'),contacts=tx.objectStore('contacts');for(const action of [...run.actions].reverse()){if(action.type==='add')contacts.delete(action.after.phone);if(action.type==='update'){contacts.delete(action.after.phone);contacts.put(cleanRecord(action.before))}}run.status='rolled_back';run.rolledBackAt=Date.now();tx.objectStore('merge_runs').put(run);for(const file of run.files){const req=tx.objectStore('imports').get(file.id);req.onsuccess=()=>{if(req.result)tx.objectStore('imports').put({...req.result,status:'rolled_back',rolledBackAt:Date.now()})}}const imageStore=tx.objectStore('contact_images'),idx=imageStore.index('importId');for(const file of run.files){const cursor=idx.openCursor(IDBKeyRange.only(file.id));cursor.onsuccess=()=>{const c=cursor.result;if(c){c.delete();c.continue()}}}await txDone(tx);await rebuildStats();await fillCitySelects();touchRevision();await audit('merge-rollback','آخرین Merge بازگردانی شد',{mergeId:run.id});notify('Rollback کامل انجام شد.');await refreshHistory();if(typeof refreshContacts==='function')refreshContacts()}catch(error){notify(error.message,'bad')}finally{setBusy(false)}}
async function undoImport(importId){const runs=(await all('merge_runs')).filter(r=>r.status==='committed'&&r.files?.some(f=>f.id===importId)).sort((a,b)=>b.createdAt-a.createdAt),run=runs[0];if(!run)return notify('Delta این Import برای Undo پیدا نشد.','bad');if(run.undoneImportIds?.includes(importId))return notify('این Import قبلاً Undo شده است.','bad');const file=run.files.find(f=>f.id===importId);if(!confirm(`Undo امن فایل ${file.name} انجام شود؟`))return;const tx=state.db.transaction(['contacts','merge_runs','imports','contact_images'],'readwrite'),contacts=tx.objectStore('contacts'),actions=run.actions.filter(a=>a.incoming?.importIds?.includes(importId)).reverse();for(const action of actions){const current=await request(contacts.get(action.after?.phone||action.incoming.phone));if(action.type==='add'&&current){const remaining=(current.importIds||[]).filter(x=>x!==importId);if(remaining.length)contacts.put({...current,importIds:remaining,sourceFiles:(current.sourceFiles||[]).filter(x=>x!==file.name)});else contacts.delete(current.phone)}else if(action.type==='update'&&current){if(current.updatedAt===action.after.updatedAt){contacts.delete(current.phone);contacts.put(cleanRecord(action.before))}else contacts.put({...current,importIds:(current.importIds||[]).filter(x=>x!==importId),sourceFiles:(current.sourceFiles||[]).filter(x=>x!==file.name)})}}run.undoneImportIds=[...(run.undoneImportIds||[]),importId];tx.objectStore('merge_runs').put(run);const imp=await request(tx.objectStore('imports').get(importId));if(imp)tx.objectStore('imports').put({...imp,status:'undone',undoneAt:Date.now()});const images=tx.objectStore('contact_images').index('importId').openCursor(IDBKeyRange.only(importId));images.onsuccess=()=>{const c=images.result;if(c){c.delete();c.continue()}};await txDone(tx);await rebuildStats();touchRevision();await audit('import-undo','Import مستقل Undo شد',{importId,file:file.name});notify(`Undo فایل ${file.name} انجام شد.`);await refreshHistory();if(typeof refreshContacts==='function')refreshContacts()}

async function renumberAll(){if(!confirm('شماره ردیف همه مخاطبین بر اساس شهر و نام بازسازی شود؟'))return;const rows=(await all('contacts')).sort((a,b)=>String(a.city).localeCompare(String(b.city),'fa')||String(a.name).localeCompare(String(b.name),'fa')),tx=state.db.transaction('contacts','readwrite'),store=tx.objectStore('contacts');rows.forEach((row,index)=>store.put({...row,rowNumber:index+1,updatedAt:Date.now()}));await txDone(tx);touchRevision();await audit('contacts-renumber','شماره‌گذاری مجدد انجام شد',{count:rows.length});notify(`${FMT.format(rows.length)} ردیف شماره‌گذاری شد.`);if(typeof refreshContacts==='function')refreshContacts()}
async function previewDelete(){const source=q('cf34-source-select').value;if(!source)return notify('منبع را انتخاب کنید.','bad');const rows=(await all('contacts')).filter(row=>row.source===source||row.sourceFiles?.includes(source));S.deletePreview={source,phones:rows.map(x=>x.phone),count:rows.length};q('cf34-delete-state').textContent=`Dry-run: ${FMT.format(rows.length)} مخاطب به منبع «${source}» مرتبط است؛ رکورد چندمنبعی حفظ و فقط برچسب منبع حذف می‌شود.`;q('cf34-delete-source').disabled=!rows.length}
async function deleteSource(){const p=S.deletePreview;if(!p||p.source!==q('cf34-source-select').value)return notify('ابتدا پیش‌نمایش حذف را اجرا کنید.','bad');if(!confirm(`${p.count} ارتباط منبع پاک‌سازی شود؟ این عملیات مستقل از Merge است.`))return;const tx=state.db.transaction('contacts','readwrite'),store=tx.objectStore('contacts');for(const phone of p.phones){const row=await request(store.get(phone));if(!row)continue;const files=(row.sourceFiles||[]).filter(x=>x!==p.source),ids=row.importIds||[];if(files.length)store.put({...row,sourceFiles:files,source:row.source===p.source?files[0]:row.source,updatedAt:Date.now()});else store.delete(phone)}await txDone(tx);await rebuildStats();touchRevision();await audit('source-delete','منبع پاک‌سازی شد',{source:p.source,count:p.count});notify('پاک‌سازی منبع انجام شد.');S.deletePreview=null;q('cf34-delete-source').disabled=true;await refreshHistory();if(typeof refreshContacts==='function')refreshContacts()}

async function exportRows(rows,name,format='csv'){if(!rows.length)return notify('رکوردی برای خروجی وجود ندارد.','bad');if(window.ContactFlowContactExport){const plan=window.ContactFlowContactExport.buildExportPlan(rows,{format,chunkSize:100000,baseName:name,fields:['name','phone','email','city','province','country','phoneType','operator','company','source','telegramStatus'],includeWithoutPhone:false,sortBy:'city'});for(const entry of plan)await deliverFile(entry.blob,entry.name,entry.count);return}const blob=makeExportBlob(format,rows);if(blob)await deliverFile(blob,`${name}.${format==='xls'?'xls':format}`,rows.length)}
async function deliverFile(blob,name,count,{share=false}={}){if(window.ContactFlowFileSave)return window.ContactFlowFileSave.save(blob,name,{share});if(typeof appendExport==='function'){appendExport(blob,name,count);window.setPage?.('exports');return}const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),3000)}
function reportBlob(){const rows=E.reportRows(S.plan?.report||{bySource:{}}),safe=v=>/^[=+\-@\t\r]/.test(String(v??''))?`'${v}`:v,html=`<html dir="rtl"><meta charset="utf-8"><table border="1"><tbody>${rows.map(row=>`<tr>${row.map(v=>`<td>${esc(safe(v))}</td>`).join('')}</tr>`).join('')}</tbody></table></html>`;return new Blob(['\ufeff'+html],{type:'application/vnd.ms-excel'})}
function printReport(){document.body.classList.add('cf34-printing');window.print();setTimeout(()=>document.body.classList.remove('cf34-printing'),1000)}
async function shareReport(){if(!S.plan)return notify('ابتدا گزارش بسازید.','bad');const blob=new Blob([E.reportCsv(S.plan.report)],{type:'text/csv;charset=utf-8'});try{await deliverFile(blob,'ContactFlow_3.6_Merge_Report.csv',E.reportRows(S.plan.report).length,{share:true})}catch(error){if(error.name!=='AbortError')notify(error.message,'bad')}}

async function telegramConnector(){for(let i=0;i<160;i++){if(window.ContactFlowTelegramWeb)return window.ContactFlowTelegramWeb;await sleep(50)}throw new Error('Telegram User Session Connector آماده نیست.')}
async function refreshTelegramStats(){const rows=await all('contacts'),matched=rows.filter(x=>x.telegramStatus==='matched').length,checked=rows.filter(x=>x.telegramStatus&&x.telegramStatus!=='unchecked').length,pct=rows.length?Math.round(matched/rows.length*100):0;if(q('cf34-tg-percent'))q('cf34-tg-percent').textContent=`${FMT.format(pct)}٪ matched • ${FMT.format(checked)}/${FMT.format(rows.length)}`}
async function checkTelegram(){
  const tg=await telegramConnector(),account=await tg.activeAccountId();if(!account)return notify('ابتدا در بخش مخاطبین تلگرام یک User Session رسمی با QR متصل کنید.','bad');const cap=Math.max(10,Math.min(MAX_CHECK_PER_RUN,Number(q('cf34-tg-cap').value)||200)),batch=Math.max(10,Math.min(500,Number(q('cf34-tg-batch').value)||100)),allRows=await all('contacts'),candidates=allRows.filter(x=>x.phone&&x.phoneType!=='landline').sort((a,b)=>(a.telegramStatus==='unchecked'||!a.telegramStatus?-1:1)-(b.telegramStatus==='unchecked'||!b.telegramStatus?-1:1)).slice(0,cap);if(!candidates.length)return notify('شماره موبایلی برای بررسی وجود ندارد.','bad');q('cf34-tg-check').disabled=true;
  try{const results=await tg.checkContacts(account,candidates.map(x=>x.phone),{batchSize:batch,cleanup:true,onProgress:p=>{q('cf34-tg-state').textContent=`${FMT.format(p.done)}/${FMT.format(p.total)} • matched ${FMT.format(p.matched)} • retry ${FMT.format(p.retry)}`}});S.lastTelegram=results;const tx=state.db.transaction('contacts','readwrite'),store=tx.objectStore('contacts');for(const result of results){const row=await request(store.get(result.phone));if(row)store.put({...row,telegramStatus:result.status,telegramLabel:formatStatus(result.status),telegramUserId:result.userId||'',telegramUsername:result.username||'',telegramCheckedAt:result.updatedAt||Date.now(),updatedAt:Date.now()})}await txDone(tx);touchRevision();const matched=results.filter(x=>x.status==='matched').length;q('cf34-tg-state').textContent=`پایان اجرا: ${FMT.format(matched)} matched • ${FMT.format(results.length-matched)} برنگشته/retry • سقف اجرا ${FMT.format(cap)}`;await audit('telegram-check','وضعیت Telegram بروزرسانی شد',{checked:results.length,matched,cap});notify('وضعیت Telegram در دیتابیس و Backup محلی ثبت شد.');await refreshTelegramStats();if(typeof refreshContacts==='function')refreshContacts()}catch(error){notify(error.message,'bad',9000);q('cf34-tg-state').textContent=error.message}finally{q('cf34-tg-check').disabled=false}
}
async function exportTelegram(status){const rows=(await all('contacts')).filter(x=>x.telegramStatus===status);exportRows(rows,status==='matched'?'telegram_matched':'telegram_not_returned','csv')}

async function contactPicker(){if(!navigator.contacts?.select)return notify('Contact Picker در این مرورگر/Mini App موجود نیست؛ از VCF یا نسخه Android استفاده کنید.','bad');try{const contacts=await navigator.contacts.select(['name','tel','email'],{multiple:true}),job={id:id(),name:`Device-Contacts-${new Date().toISOString().slice(0,10)}.vcf`,source:'Contact Picker',city:'',section:'',status:'parsed',size:0,rows:0},raw=[];for(const c of contacts)for(const phone of c.tel||[])raw.push({name:c.name?.[0]||'',phone,email:c.email?.[0]||''});job.rows=raw.length;job._nativeRows=raw;S.jobs.push(job);renderQueue();notify(`${FMT.format(raw.length)} مخاطب انتخابی اضافه شد؛ «تحلیل و مقایسه» را بزنید.`)}catch(error){if(error.name!=='AbortError')notify(error.message,'bad')}}
function requestAndroidContacts(){if(!window.ContactFlowAndroid?.requestDeviceContacts)return notify('دسترسی کامل دفترچه فقط در APK اندروید و پس از مجوز صریح فعال است.','bad');window.ContactFlowAndroid.requestDeviceContacts()}
function addNativeContacts(rows){const job={id:id(),name:`Android-Contacts-${new Date().toISOString().slice(0,10)}.vcf`,source:'دفترچه Android',city:'',section:'',status:'parsed',size:0,rows:rows.length};job._nativeRows=rows;S.jobs.push(job);renderQueue();notify(`${FMT.format(rows.length)} شماره از دفترچه Android دریافت شد؛ تحلیل را بزنید.`)}
async function ocrFile(file){try{let text='';if(window.ContactFlowAndroid?.recognizeBusinessCard){window.ContactFlowAndroid.recognizeBusinessCard();return}if('TextDetector'in window){const detector=new TextDetector(),bitmap=await createImageBitmap(file),blocks=await detector.detect(bitmap);text=blocks.map(x=>x.rawValue).join('\n')}else throw new Error('OCR محلی در این مرورگر موجود نیست؛ در APK Android از ML Kit استفاده کنید.');onOcrText(text)}catch(error){notify(error.message,'bad')}}
function onOcrText(text){const phones=String(text||'').match(/(?:\+|00)?[\d۰-۹٠-٩][\d۰-۹٠-٩\s().-]{7,18}/g)||[],email=String(text||'').match(/[\w.+-]+@[\w.-]+\.[a-z]{2,}/i)?.[0]||'',lines=String(text||'').split(/\r?\n/).map(E.cleanText).filter(Boolean),name=lines.find(x=>!x.includes('@')&&!/\d/.test(E.latinDigits(x)))||'کارت ویزیت',job={id:id(),name:`Business-Card-${Date.now()}.jpg`,source:'OCR کارت ویزیت',city:'',section:'',status:'parsed',size:0,rows:phones.length};job._nativeRows=phones.map(phone=>({name,phone,email,note:'OCR: '+lines.slice(0,6).join(' | ')}));S.jobs.push(job);renderQueue();notify(`${FMT.format(phones.length)} شماره از کارت ویزیت تشخیص داده شد؛ تحلیل را بزنید.`)}

async function chooseWatchFolder(){if(!window.showDirectoryPicker)return notify('Watch Folder در این محیط موجود نیست؛ Desktop/PWA پشتیبانی‌شده را استفاده کنید.','bad');try{const handle=await showDirectoryPicker({id:'contactflow-import',mode:'read'});S.watchHandle=handle;const tx=state.db.transaction('watch_state','readwrite');tx.objectStore('watch_state').put({key:'import-folder',handle,seen:{},updatedAt:Date.now()});await txDone(tx);q('cf34-device-note').textContent=`Watch Folder: ${handle.name} • فقط هنگام باز بودن برنامه هر ۶۰ ثانیه بررسی می‌شود.`;startWatch();await scanWatch()}catch(error){if(error.name!=='AbortError')notify(error.message,'bad')}}
async function restoreWatch(){try{const row=await request(txStore('watch_state').get('import-folder'));if(row?.handle?.kind==='directory'&&typeof row.handle.entries==='function'){S.watchHandle=row.handle;q('cf34-device-note').textContent=`Watch Folder ذخیره‌شده: ${row.handle.name} • برای ادامه ممکن است اجازه دوباره لازم باشد.`}}catch{}}
async function scanWatch(){const handle=S.watchHandle;if(!handle)return notify('ابتدا پوشه را انتخاب کنید.','bad');const permission=await handle.queryPermission?.({mode:'read'});if(permission!=='granted'&&await handle.requestPermission?.({mode:'read'})!=='granted')throw new Error('مجوز خواندن پوشه داده نشد.');const row=await request(txStore('watch_state').get('import-folder')),seen=row?.seen||{},fresh=[];for await(const [name,entry] of handle.entries()){if(entry.kind!=='file')continue;const file=await entry.getFile(),mark=`${file.size}:${file.lastModified}`;if(seen[name]!==mark){seen[name]=mark;fresh.push(file)}}if(fresh.length)await addFiles(fresh,{silent:true});const tx=state.db.transaction('watch_state','readwrite');tx.objectStore('watch_state').put({key:'import-folder',handle,seen,updatedAt:Date.now()});await txDone(tx);q('cf34-device-note').textContent=`Watch Folder ${handle.name}: ${FMT.format(fresh.length)} فایل جدید • ${new Date().toLocaleTimeString('fa-IR')}`}
function startWatch(){clearInterval(S.watchTimer);S.watchTimer=setInterval(()=>{if(document.visibilityState==='visible')scanWatch().catch(error=>q('cf34-device-note').textContent=error.message)},60000)}

async function audit(type,message,meta={}){try{const tx=state.db.transaction('activity','readwrite');tx.objectStore('activity').put({id:id(),type,message,meta,createdAt:Date.now()});await txDone(tx)}catch{}}
async function refreshHistory(){
  const imports=(await all('imports')).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0)).slice(0,60);if(q('cf34-history'))q('cf34-history').innerHTML=imports.length?imports.map(row=>`<tr><td>${esc(row.filename||'Legacy Import')}<small>${esc(row.source||'')}</small></td><td>${FMT.format(row.added||0)}</td><td>${FMT.format(row.duplicates||0)}</td><td>${row.createdAt?new Date(row.createdAt).toLocaleString('fa-IR'):'—'}</td><td><span class="pill ${row.status==='committed'?'active':row.status?'danger':'queued'}">${esc(row.status||'legacy')}</span></td><td>${typeof row.id==='string'&&row.status==='committed'?`<button class="ghost-btn" data-cf34-undo="${esc(row.id)}">Undo فایل</button>`:'—'}</td></tr>`).join(''):'<tr><td colspan="6">تاریخچه‌ای نیست.</td></tr>';
  q('cf34-history')?.querySelectorAll('[data-cf34-undo]').forEach(button=>button.onclick=()=>undoImport(button.dataset.cf34Undo).catch(error=>notify(error.message,'bad')));const sources=[...new Set(imports.map(x=>x.source||x.filename).filter(Boolean))];if(q('cf34-source-select'))q('cf34-source-select').innerHTML='<option value="">انتخاب کنید</option>'+sources.map(source=>`<option>${esc(source)}</option>`).join('')
}

function patchContactPage(){
  const panel=document.querySelector('.page[data-page="contacts"] .panel');if(!panel||q('contact-source34'))return;const filters=panel.querySelector('.filters');filters?.insertAdjacentHTML('beforeend','<input id="contact-source34" placeholder="فایل/منبع/یادداشت"><select id="contact-telegram34"><option value="">همه وضعیت‌های تلگرام</option><option value="matched">تلگرام‌دار ✓</option><option value="not_returned">برنگشته/نامشخص</option><option value="unchecked">بررسی‌نشده</option></select><select id="contact-phone-type34"><option value="">موبایل و ثابت</option><option value="mobile">موبایل</option><option value="landline">تلفن ثابت</option></select>');
  const head=panel.querySelector('thead tr');if(head)head.innerHTML='<th>#</th><th>نام</th><th>شماره استاندارد</th><th>شهر/کشور</th><th>نوع</th><th>منبع</th><th>Telegram</th>';
  const priorGet=window.getContactPage;window.getContactPage=async function(city,section,search,page,size){const sourceFilter=E.keyText(q('contact-source34')?.value||''),tg=q('contact-telegram34')?.value||'',phoneType=q('contact-phone-type34')?.value||'',query=E.keyText(search),rows=(await all('contacts')).filter(row=>(!city||row.city===city)&&(!section||row.section===section)&&(!sourceFilter||E.keyText([row.source,...(row.sourceFiles||[]),row.importNote].join(' ')).includes(sourceFilter))&&(!tg||(tg==='unchecked'?(!row.telegramStatus||row.telegramStatus==='unchecked'):row.telegramStatus===tg))&&(!phoneType||row.phoneType===phoneType)&&(!query||E.keyText([row.name,row.phone,row.email,row.company,row.city,row.source].join(' ')).includes(query))).sort((a,b)=>String(a.city||'').localeCompare(String(b.city||''),'fa')||String(a.name||'').localeCompare(String(b.name||''),'fa'));const start=(page-1)*size,out=rows.slice(start,start+size);out.total=rows.length;return out};
  window.refreshContacts=async function(){const city=q('contact-city').value,section=q('contact-section')?.value||'',search=q('contact-search').value,rows=await window.getContactPage(city,section,search,state.page,PAGE_SIZE),fa=q('cf34-fa-digits')?.checked||localStorage.getItem('cf34_fa_digits')==='1';q('contacts-count').textContent=`${FMT.format(rows.total||0)} نتیجه`;q('contacts-table').innerHTML=rows.length?rows.map(row=>`<tr><td>${FMT.format(row.rowNumber||'—')}</td><td>${esc(row.name)}${row.company?`<small>${esc(row.company)}</small>`:''}</td><td dir="ltr">${esc(fa?E.persianDigits(row.phone):row.phone)}</td><td>${esc(row.city||'—')}<small>${esc(row.country||'')}</small></td><td>${esc(row.phoneType==='mobile'?'موبایل':row.phoneType==='landline'?'ثابت':'نامشخص')}</td><td>${esc(row.source||'—')}</td><td><span class="pill ${row.telegramStatus==='matched'?'active':row.telegramStatus==='retry'?'danger':'queued'}">${esc(formatStatus(row.telegramStatus))}</span></td></tr>`).join(''):'<tr><td colspan="7">موردی پیدا نشد.</td></tr>';q('page-indicator').textContent=`صفحه ${FMT.format(state.page)}`;q('prev-page').disabled=state.page<=1;q('next-page').disabled=rows.length<PAGE_SIZE};
  ['contact-source34','contact-telegram34','contact-phone-type34'].forEach(key=>q(key).oninput=q(key).onchange=()=>{state.page=1;window.refreshContacts()});void priorGet;
}

function diagnostics(){return {version:VERSION,runtime:runtimeKind(),features:FEATURES.length,dbVersion:5,contactPicker:!!navigator.contacts?.select,androidContacts:!!window.ContactFlowAndroid?.requestDeviceContacts,webOcr:'TextDetector'in window,androidOcr:!!window.ContactFlowAndroid?.recognizeBusinessCard,watchFolder:!!window.showDirectoryPicker,webShare:!!navigator.share,telegramUserSession:!!window.ContactFlowTelegramWeb,checkCap:MAX_CHECK_PER_RUN}}
function resetQueue(){if(S.busy)return;S.jobs=[];S.records=[];S.photos=[];S.plan=null;S.decisions={};q('cf34-result').classList.add('hidden');renderQueue();progress(0,'آماده','');updateCommitState()}
function bind(){
  q('cf34-files').onchange=event=>addFiles(event.target.files);const drop=q('cf34-drop');drop.ondragover=event=>{event.preventDefault();drop.classList.add('drag')};drop.ondragleave=()=>drop.classList.remove('drag');drop.ondrop=event=>{event.preventDefault();drop.classList.remove('drag');addFiles(event.dataTransfer.files)};
  q('cf34-analyze').onclick=()=>{for(const job of S.jobs.filter(j=>j._nativeRows)){job.file=new File([JSON.stringify(job._nativeRows)],job.name.replace(/\.[^.]+$/,'.json'),{type:'application/json'});job.name=job.file.name}analyze()};q('cf34-commit').onclick=commit;q('cf34-reset').onclick=resetQueue;q('cf34-dry').onchange=updateCommitState;q('cf34-mode').onchange=()=>{S.plan=null;updateCommitState()};q('cf34-fa-digits').checked=localStorage.getItem('cf34_fa_digits')==='1';q('cf34-fa-digits').onchange=()=>{localStorage.setItem('cf34_fa_digits',q('cf34-fa-digits').checked?'1':'0');if(typeof refreshContacts==='function')refreshContacts()};
  q('cf34-export-new').onclick=()=>exportRows(S.plan?.newRecords||[],'contactflow_merge_new','csv');q('cf34-report-xls').onclick=()=>S.plan&&deliverFile(reportBlob(),'ContactFlow_3.6_Merge_Report.xls',E.reportRows(S.plan.report).length);q('cf34-report-pdf').onclick=printReport;q('cf34-share-report').onclick=shareReport;q('cf34-renumber').onclick=renumberAll;q('cf34-rollback').onclick=rollbackLast;
  q('cf34-tg-check').onclick=checkTelegram;q('cf34-tg-matched').onclick=()=>exportTelegram('matched');q('cf34-tg-unmatched').onclick=()=>exportTelegram('not_returned');q('cf34-contact-picker').onclick=contactPicker;q('cf34-android-contacts').onclick=requestAndroidContacts;q('cf34-ocr').onclick=()=>window.ContactFlowAndroid?.recognizeBusinessCard?window.ContactFlowAndroid.recognizeBusinessCard():q('cf34-ocr-file').click();q('cf34-ocr-file').onchange=e=>e.target.files?.[0]&&ocrFile(e.target.files[0]);q('cf34-watch').onclick=chooseWatchFolder;q('cf34-watch-scan').onclick=()=>scanWatch().catch(error=>notify(error.message,'bad'));
  q('cf34-preview-delete').onclick=previewDelete;q('cf34-delete-source').onclick=deleteSource;q('cf34-history-refresh').onclick=refreshHistory;
}
function updateVersion(){document.title='ContactFlow Personal Ultimate 3.6';document.querySelectorAll('.setting-box code,.brand span').forEach(el=>{el.textContent=el.textContent.replace(/3\.[345](?:\.0)?/g,'3.6.0')});document.body.dataset.cfVersion=VERSION}
async function init(){await waitCore();addNavigation();addPage();patchRouting();patchContactPage();bind();updateVersion();renderQueue();await restoreWatch();if(S.watchHandle)startWatch();await refreshHistory();await refreshTelegramStats();q('cf34-device-note').textContent=Object.entries(diagnostics()).filter(([,v])=>v===true).map(([k])=>k).join(' • ');window.ContactFlow34={VERSION,FEATURES,diagnostics,addFiles,analyze,commit,rollbackLast,undoImport,checkTelegram,onDeviceContacts:addNativeContacts,onOcrText};window.dispatchEvent(new CustomEvent('contactflow:3.4-ready',{detail:diagnostics()}))}

if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>init().catch(error=>{console.error(error);notify(error.message,'bad',10000)}));else init().catch(error=>{console.error(error);notify(error.message,'bad',10000)});
})();
