(() => {
'use strict';
const VERSION='3.6.0',L=window.ContactFlowLocationOperator,H=window.ContactFlowChannelHandoff,F=new Intl.NumberFormat('fa-IR');
const q=id=>document.getElementById(id),esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
function notice(message,type='good'){try{toast(message,type,6000)}catch{console[type==='bad'?'error':'info'](message)}}
function req(request){return new Promise((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function waitCore(){for(let i=0;i<300;i++){if(window.ContactFlow34&&state?.db&&L&&H)return;await sleep(50)}throw new Error('هسته کانال‌های نسخه ۳.۶ آماده نشد.')}
function store(name,mode='readonly'){return state.db.transaction(name,mode).objectStore(name)}
async function all(name){return (await req(store(name).getAll()))||[]}
async function setting(key,fallback=''){return (await req(store('settings').get(key)))?.value??fallback}
async function saveSetting(key,value){const tx=state.db.transaction('settings','readwrite');tx.objectStore('settings').put({key,value,updatedAt:Date.now()});return new Promise((resolve,reject)=>{tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}
async function migrateContacts(){if(await setting('cf35-location-migration','')===VERSION)return 0;const tx=state.db.transaction('contacts','readwrite'),contacts=tx.objectStore('contacts'),done=new Promise((resolve,reject)=>{tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)});let changed=0;await new Promise((resolve,reject)=>{const cursor=contacts.openCursor();cursor.onsuccess=()=>{const item=cursor.result;if(!item)return resolve();const row=item.value,province=row.province||L.provinceForCity(row.city),detected=L.detectOperator(row.phone),operator=row.operator||detected.operator;if(province!==row.province||operator!==row.operator){item.update({...row,province,operator,operatorPrefix:row.operatorPrefix||detected.prefix,operatorNote:row.operatorNote||detected.note,updatedAt:row.updatedAt||Date.now()});changed++}item.continue()};cursor.onerror=()=>reject(cursor.error)});await done;await saveSetting('cf35-location-migration',VERSION);return changed}

let policy={mode:'auto',fixedSource:'همراه اول',fallback:'Import'};
function sourcePolicy(){return {...policy}}
function addPolicyControls(){const target=q('cf34-mode')?.closest('.form-grid');if(!target||q('cf35-source-mode'))return;target.insertAdjacentHTML('beforeend',`<label><span>تنظیم منبع برای همه ورودی‌ها</span><select id="cf35-source-mode"><option value="auto">خودکار از پیش‌شماره</option><option value="fixed">یک منبع ثابت برای همه</option><option value="keep">حفظ منبع فایل</option></select></label><label><span>منبع ثابت</span><select id="cf35-fixed-source"><option>همراه اول</option><option>ایرانسل</option><option>رایتل</option><option>شاتل موبایل</option><option>سایر</option></select></label>`);q('cf35-source-mode').value=policy.mode;q('cf35-fixed-source').value=policy.fixedSource;q('cf35-source-mode').onchange=q('cf35-fixed-source').onchange=async()=>{policy={...policy,mode:q('cf35-source-mode').value,fixedSource:q('cf35-fixed-source').value};await saveSetting('cf35-source-policy',policy);window.dispatchEvent(new CustomEvent('contactflow:source-policy-changed',{detail:sourcePolicy()}));notice('تنظیم منبع ذخیره شد و روی همه مخاطبین و Importهای بعدی اعمال می‌شود.')}}

function addNavigation(){const nav=q('nav');if(nav&&!q('cf35-nav')){const b=document.createElement('button');b.id='cf35-nav';b.className='nav-item';b.dataset.page='channels';b.innerHTML='◉ <span>کانال‌های ارتباطی</span>';nav.insertBefore(b,nav.querySelector('[data-page="backup"]'))}try{pageMeta.channels=['کانال‌های ارتباطی','جستجوی شهر/استان، صف رضایت‌محور و تحویل به پیام‌رسان‌ها']}catch{}}
function pageMarkup(){const options=Object.entries(H.CHANNELS).map(([key,item])=>`<option value="${key}">${esc(item.label)}</option>`).join('');return `
<section class="page cf35-page" data-page="channels">
 <article class="panel callout"><div><strong>مرکز ارتباطی ContactFlow 3.6</strong><p>جستجوی آفلاین شهر/استان، تشخیص اپراتور اولیه و صف خروجی برای تلگرام، واتساپ، روبیکا، بله و سروش. ارسال نهایی همیشه با تأیید کاربر یا API رسمی و مخاطب رضایت‌داده انجام می‌شود.</p></div><span class="pill active">Local-First</span></article>
 <div class="layout-2"><article class="panel form-panel"><div class="panel-head"><div><h2>شهر و استان از متن</h2><p>فارسی، انگلیسی یا فینگلیش؛ قابل استفاده در جستجوی مخاطبین</p></div></div><label><span>نام شهر، استان، آدرس یا نام فایل</span><input id="cf35-location-query" placeholder="مثلاً customers_BandarAbbas_02.csv"></label><div id="cf35-location-result" class="cf35-location-result">متنی وارد کنید.</div><button id="cf35-search-contacts" class="primary-soft full-btn">جستجو در مخاطبین همین استان</button></article>
 <article class="panel form-panel"><div class="panel-head"><div><h2>تشخیص اپراتور</h2><p>بر پایه پیش‌شماره اولیه؛ ترابردپذیری ممکن است اپراتور فعلی را تغییر داده باشد</p></div></div><label><span>شماره موبایل</span><input id="cf35-operator-phone" dir="ltr" placeholder="0912…"></label><div id="cf35-operator-result" class="cf35-location-result">شماره‌ای وارد کنید.</div></article></div>
 <div class="layout-2 wide-left"><article class="panel form-panel"><div class="panel-head"><div><h2>صف کمپین رضایت‌محور</h2><p>فقط Opt-in برای تبلیغ؛ Opt-in + Existing Chat برای پیام خدماتی</p></div><span id="cf35-eligible-count" class="pill queued">۰ مخاطب</span></div><div class="form-grid"><label><span>کانال</span><select id="cf35-channel">${options}</select></label><label><span>نوع پیام</span><select id="cf35-purpose"><option value="promotional">تبلیغاتی — فقط Opt-in</option><option value="service">خدماتی — Opt-in + Existing Chat</option></select></label><label class="full"><span>قالب پیام</span><textarea id="cf35-message" rows="7" placeholder="سلام {name}، …"></textarea></label><label class="full"><span>قالب URL اختیاری برای روبیکا/بله/سروش</span><input id="cf35-url-template" dir="ltr" placeholder="https://…/{phone}?text={text}"></label></div><div class="button-row"><button id="cf35-preview" class="primary-btn">ساخت پیش‌نمایش</button><button id="cf35-export-queue" class="ghost-btn">خروجی CSV صف</button><button id="cf35-export-vcf" class="ghost-btn">ذخیره مخاطبین VCF</button></div><p class="hint">قالب URL سفارشی فقط روی همین دستگاه ذخیره می‌شود. برای پیام‌رسان‌هایی که لینک رسمی قابل اتکا ندارند، متن کپی و خود اپ باز می‌شود.</p></article>
 <article class="panel"><div class="panel-head"><div><h2>تحویل به اپ</h2><p>یک مخاطب در هر بار با تأیید دستی</p></div></div><div id="cf35-handoff" class="empty-state compact">پیش‌نمایش را بسازید.</div></article></div>
</section>`}
function addPage(){if(!document.querySelector('.page[data-page="channels"]'))document.querySelector('main.main')?.insertAdjacentHTML('beforeend',pageMarkup())}

function renderLocation(){const result=L.inferLocation(q('cf35-location-query').value);q('cf35-location-result').innerHTML=result.province?`<strong>${esc(result.city||'استان')}</strong><span>${esc(result.province)} • اطمینان ${F.format(Math.round(result.confidence*100))}٪</span>`:'<span>شهر یا استان شناخته نشد.</span>';q('cf35-search-contacts').disabled=!result.province;return result}
function renderOperator(){const result=L.detectOperator(q('cf35-operator-phone').value);q('cf35-operator-result').innerHTML=`<strong>${esc(result.operator)}</strong><span>${esc(result.prefix||'—')} • ${esc(result.note)}</span>`}
async function searchProvince(){const result=renderLocation();if(!result.province)return;window.setPage('contacts');q('contact-search').value=result.province;state.page=1;await window.refreshContacts?.()}
async function eligible(){const contacts=await all('contacts'),flags=await all('contact_flags');return H.eligibleContacts(contacts,flags,{purpose:q('cf35-purpose').value})}
async function renderPreview(){const rows=await eligible(),channel=q('cf35-channel').value,message=q('cf35-message').value,template=q('cf35-url-template').value.trim();q('cf35-eligible-count').textContent=`${F.format(rows.length)} مخاطب`;if(!rows.length){q('cf35-handoff').className='empty-state compact';q('cf35-handoff').textContent='مخاطب مجاز پیدا نشد؛ وضعیت Opt-in را در بخش Audience ثبت کنید.';return}await saveSetting(`cf35-url-template-${channel}`,template);const first=rows[0],handoff=H.buildHandoff(channel,first,message,{urlTemplate:template,shareUrl:location.href});q('cf35-handoff').className='';q('cf35-handoff').innerHTML=`<div class="export-row"><div><strong>${esc(first.name||first.phone)}</strong><small>${esc(first.phone)} • ${esc(first.city||'')} ${esc(first.province||'')} • ${esc(first.consentStatus)}</small></div></div><div class="message-preview">${esc(handoff.text)}</div><div class="button-row"><button id="cf35-copy" class="ghost-btn">کپی متن</button><a id="cf35-open" class="primary-btn cf35-link" target="_blank" rel="noopener noreferrer">بازکردن ${esc(H.CHANNELS[channel].label)}</a></div><p class="hint">حالت: ${esc(handoff.mode)} • ارسال بدون تأیید انجام نمی‌شود.</p>`;q('cf35-open').href=handoff.url;q('cf35-copy').onclick=async()=>{await navigator.clipboard.writeText(handoff.text);notice('متن کپی شد.')}}
async function download(blob,name,count){if(typeof appendExport==='function'){appendExport(blob,name,count);window.setPage('exports');return}const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),3000)}
async function exportQueue(){const rows=await eligible();if(!rows.length)return notice('مخاطب مجاز برای خروجی وجود ندارد.','bad');const channel=q('cf35-channel').value,csv=H.queueCsv(rows,channel,q('cf35-message').value);await download(new Blob([csv],{type:'text/csv;charset=utf-8'}),`ContactFlow_3.6_${channel}_queue.csv`,rows.length)}
async function exportVcf(){const rows=await eligible();if(!rows.length)return notice('مخاطب مجاز برای خروجی وجود ندارد.','bad');const channel=q('cf35-channel').value,plan=window.ContactFlowContactExport.buildExportPlan(rows,{format:'vcf',chunkSize:5000,baseName:`ContactFlow_3.6_${channel}_contacts`,includeWithoutPhone:false});for(const item of plan)await download(item.blob,item.name,item.count)}

function patchContacts(){const panel=document.querySelector('.page[data-page="contacts"] .panel'),head=panel?.querySelector('thead tr');if(!panel||!head)return;head.innerHTML='<th>#</th><th>نام</th><th>شماره استاندارد</th><th>شهر / استان</th><th>اپراتور</th><th>منبع</th><th>Telegram</th>';window.refreshContacts=async function(){const city=q('contact-city').value,section=q('contact-section')?.value||'',query=L.text(q('contact-search').value).toLowerCase(),sourceFilter=L.text(q('contact-source34')?.value||'').toLowerCase(),tg=q('contact-telegram34')?.value||'',phoneType=q('contact-phone-type34')?.value||'',allRows=await all('contacts'),rows=allRows.filter(row=>{const province=row.province||L.provinceForCity(row.city);return (!city||row.city===city)&&(!section||row.section===section)&&(!sourceFilter||L.text([row.source,...(row.sourceFiles||[]),row.importNote].join(' ')).toLowerCase().includes(sourceFilter))&&(!tg||(tg==='unchecked'?(!row.telegramStatus||row.telegramStatus==='unchecked'):row.telegramStatus===tg))&&(!phoneType||row.phoneType===phoneType)&&(!query||L.text([row.name,row.phone,row.email,row.company,row.city,province,row.operator,row.source].join(' ')).toLowerCase().includes(query))}).sort((a,b)=>String(a.province||'').localeCompare(String(b.province||''),'fa')||String(a.city||'').localeCompare(String(b.city||''),'fa'));const total=rows.length,pageRows=rows.slice((state.page-1)*PAGE_SIZE,state.page*PAGE_SIZE);q('contacts-count').textContent=`${F.format(total)} نتیجه`;q('contacts-table').innerHTML=pageRows.length?pageRows.map(row=>`<tr><td>${F.format(row.rowNumber||'—')}</td><td>${esc(row.name)}</td><td dir="ltr">${esc(row.phone)}</td><td>${esc(row.city||'—')}<small>${esc(row.province||L.provinceForCity(row.city)||'')}</small></td><td>${esc(row.operator||L.detectOperator(row.phone).operator)}</td><td>${esc(row.source||'—')}</td><td>${esc(row.telegramLabel||row.telegramStatus||'unchecked')}</td></tr>`).join(''):'<tr><td colspan="7">موردی پیدا نشد.</td></tr>';q('page-indicator').textContent=`صفحه ${F.format(state.page)}`;q('prev-page').disabled=state.page<=1;q('next-page').disabled=pageRows.length<PAGE_SIZE}}
function patchRouting(){const old=window.setPage;if(old&&!old.__cf35){const wrapped=function(page){const target=page==='import'?'smart-import':page;old(target);document.querySelectorAll('.page').forEach(el=>el.classList.toggle('active',el.dataset.page===target));document.querySelectorAll('[data-page]').forEach(el=>el.classList.toggle('active',el.dataset.page===target));if(target==='channels')renderPreview().catch(console.error)};wrapped.__cf35=true;window.setPage=wrapped;document.querySelectorAll('[data-page="import"],[data-go="import"]').forEach(el=>{el.dataset.page='smart-import';el.dataset.go='smart-import';const label=el.querySelector('span');if(label)label.textContent='Import یکپارچه'})}}
function bind(){q('cf35-location-query').oninput=renderLocation;q('cf35-search-contacts').onclick=searchProvince;q('cf35-operator-phone').oninput=renderOperator;q('cf35-preview').onclick=()=>renderPreview().catch(error=>notice(error.message,'bad'));q('cf35-export-queue').onclick=()=>exportQueue().catch(error=>notice(error.message,'bad'));q('cf35-export-vcf').onclick=()=>exportVcf().catch(error=>notice(error.message,'bad'));q('cf35-channel').onchange=async()=>{q('cf35-url-template').value=await setting(`cf35-url-template-${q('cf35-channel').value}`,'');renderPreview().catch(console.error)};q('cf35-purpose').onchange=()=>renderPreview().catch(console.error)}
function updateVersion(){document.title='ContactFlow Personal Ultimate 3.6';document.body.dataset.cfVersion=VERSION;document.querySelectorAll('.setting-box code,.brand span').forEach(el=>{el.textContent=el.textContent.replace(/3\.[45](?:\.0)?/g,'3.6.0')})}
async function init(){await waitCore();policy={...policy,...await setting('cf35-source-policy',{})};const migrated=await migrateContacts();addNavigation();addPage();addPolicyControls();patchRouting();patchContacts();bind();q('cf35-url-template').value=await setting('cf35-url-template-telegram','');updateVersion();if(migrated)notice(`${F.format(migrated)} مخاطب قدیمی با استان/اپراتور تکمیل شد.`);window.ContactFlow35={VERSION,sourcePolicy,inferLocation:L.inferLocation,detectOperator:L.detectOperator,eligible,buildHandoff:H.buildHandoff};window.dispatchEvent(new CustomEvent('contactflow:3.5-ready',{detail:{version:VERSION,channels:Object.keys(H.CHANNELS),migrated}}))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>init().catch(error=>notice(error.message,'bad')));else init().catch(error=>notice(error.message,'bad'));
})();
