(() => {
'use strict';
const VERSION='3.6.0',F=new Intl.NumberFormat('fa-IR'),L=window.ContactFlowLocationOperator,T=window.ContactFlowTelegramExport,G=window.ContactFlowLegacyTools;
const q=id=>document.getElementById(id),esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
let telegramRows=[],legacyRows=[],legacyDuplicates=[];
function notice(message,type='good',timeout=6000){try{toast(message,type,timeout)}catch{console[type==='bad'?'error':'info'](message)}}
function request(req){return new Promise((resolve,reject)=>{req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
function done(tx){return new Promise((resolve,reject)=>{tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('Transaction aborted'))})}
async function waitCore(){for(let i=0;i<300;i++){if(window.ContactFlow35&&state?.db&&L&&T&&G)return;await sleep(50)}throw new Error('هسته ContactFlow 3.6 آماده نشد.')}
async function all(storeName){return await request(state.db.transaction(storeName,'readonly').objectStore(storeName).getAll())||[]}
const uid=()=>crypto.randomUUID?.()||`cf36-${Date.now()}-${Math.random().toString(16).slice(2)}`;
function currentPolicy(){return window.ContactFlow35?.sourcePolicy?.()||{mode:'auto',fixedSource:'همراه اول',fallback:'Import'}}
function sourceFor(row,operator){const policy=currentPolicy();if(policy.mode==='fixed')return policy.fixedSource||'همراه اول';if(policy.mode==='auto')return operator&&operator!=='نامشخص'&&operator!=='سایر اپراتورها'?operator:(policy.fallback||row.source||'Import');return row.source||policy.fallback||'Import'}
function canonicalRow(row,importId){
  const phone=T.normalizePhone(row.phone)||normalizePhone(row.phone);if(!phone)return null;
  const location=L.inferLocation([row.city,row.province,row.address,row.sourceFile,row.source].filter(Boolean).join(' ')),detected=L.detectOperator(phone),city=L.text(location.city||row.city||''),province=L.text(location.province||row.province||L.provinceForCity(city)),source=sourceFor(row,detected.operator),name=L.repairLocationSpacing(row.name,city,province)||`مخاطب ${phone.slice(-4)}`;
  return {...row,phone,name,city,province,operator:detected.operator,operatorPrefix:detected.prefix,originalSource:row.originalSource||row.source||'',source,sourceFiles:[...new Set([...(row.sourceFiles||[]),row.sourceFile,row.source,source].filter(Boolean))],importIds:[...new Set([...(row.importIds||[]),importId].filter(Boolean))],updatedAt:Date.now(),createdAt:row.createdAt||Date.now()};
}
async function storeContacts(input,{kind='import',filename='ContactFlow 3.6'}={}){
  const importId=uid(),existing=await all('contacts'),map=new Map(existing.map(row=>[row.phone,row])),prepared=[];
  for(const item of input){const row=canonicalRow(item,importId);if(!row)continue;const old=map.get(row.phone);if(old){const merged={...old};for(const [key,value] of Object.entries(row))if(value!==''&&value!=null&&(!(Array.isArray(value))||value.length))merged[key]=value;merged.createdAt=old.createdAt||row.createdAt;merged.sourceFiles=[...new Set([...(old.sourceFiles||[]),...(row.sourceFiles||[])])];merged.importIds=[...new Set([...(old.importIds||[]),importId])];prepared.push({row:merged,isNew:false})}else{prepared.push({row,isNew:true});map.set(row.phone,row)}}
  if(!prepared.length)throw new Error('شماره معتبر برای ثبت پیدا نشد.');
  const added=prepared.filter(item=>item.isNew).length,updated=prepared.length-added,now=Date.now(),tx=state.db.transaction(['contacts','imports','activity'],'readwrite');
  prepared.forEach(item=>tx.objectStore('contacts').put(item.row));tx.objectStore('imports').put({id:importId,filename,source:kind,rows:input.length,added,updated,duplicates:updated,invalid:input.length-prepared.length,status:'committed',version:VERSION,createdAt:now});tx.objectStore('activity').put({id:uid(),type:`${kind}-import`,message:`${filename} در مخاطبین ثبت شد`,meta:{added,updated,total:prepared.length},createdAt:now});await done(tx);
  await rebuildStats();await fillCitySelects();touchRevision();await refreshDashboard();return {added,updated,total:prepared.length};
}

function addNavigation(){
  const nav=q('nav'),before=nav?.querySelector('[data-page="backup"]');if(!nav||q('cf36-insights-nav'))return;
  nav.querySelectorAll('[data-page="telegram"],[data-page="telegram-contacts"]').forEach(item=>{item.classList.add('hidden');item.setAttribute('aria-hidden','true')});
  const items=[['cf36-insights-nav','insights','◫','هوش شهری'],['cf36-telegram-nav','telegram-offline','↯','تلگرام بدون API'],['cf36-legacy-nav','legacy-tools','⌁','جعبه‌ابزار قدیمی']];
  for(const [id,page,icon,label] of items){const button=document.createElement('button');button.id=id;button.className='nav-item cf36-nav';button.dataset.page=page;button.innerHTML=`${icon} <span>${label}</span>`;button.onclick=()=>window.setPage(page);nav.insertBefore(button,before)}
  Object.assign(pageMeta,{insights:['هوش شهری','تحلیل زنده شهر، استان، اپراتور و کیفیت داده'], 'telegram-offline':['تلگرام بدون API','مشاهده، ورود و خروجی مخاطبین Telegram Desktop'], 'legacy-tools':['جعبه‌ابزار قدیمی','تمام مبدل‌های آفلاین نسخه کلاسیک در یک بخش']});
}
function analyticsMarkup(){return `<section class="page cf36-page" data-page="insights">
 <article class="cf36-hero"><div><span class="cf36-kicker">CITY INTELLIGENCE / LOCAL ONLY</span><h2 id="cf36-city-title">نبض مخاطبین شما</h2><p id="cf36-city-sub">آمار در لحظه از دیتابیس همین دستگاه محاسبه می‌شود.</p></div><div class="cf36-orbit"><strong id="cf36-quality-ring">۰٪</strong><span>کیفیت داده</span></div></article>
 <div id="cf36-insight-metrics" class="metrics-grid"></div>
 <div class="layout-2 wide-left"><article class="panel"><div class="panel-head"><div><h2>رتبه‌بندی شهرها</h2><p>بیشترین تراکم شماره‌ها</p></div><button id="cf36-city-csv" class="primary-soft">ذخیره آمار CSV…</button></div><div id="cf36-city-bars" class="cf36-bars"></div></article>
 <article class="panel"><div class="panel-head"><div><h2>ترکیب اپراتورها</h2><p>بر پایه پیش‌شماره اولیه</p></div></div><div class="cf36-donut-wrap"><div id="cf36-operator-donut" class="cf36-donut"><span>۰</span></div><div id="cf36-operator-legend" class="cf36-legend"></div></div></article></div>
 <div class="layout-2"><article class="panel"><div class="panel-head"><div><h2>سیگنال‌های هوشمند</h2><p>خلاصه‌ای که برای تصمیم‌گیری سریع ساخته می‌شود</p></div></div><div id="cf36-signals" class="cf36-signals"></div></article><article class="panel"><div class="panel-head"><div><h2>استان‌ها و منابع</h2><p>پوشش و کیفیت ورودی</p></div></div><div id="cf36-province-grid" class="cf36-province-grid"></div></article></div>
 <article class="panel"><div class="panel-head"><div><h2>جدول کامل شهری</h2><p id="cf36-city-count-label"></p></div><input id="cf36-city-filter" placeholder="جستجوی شهر یا استان…"></div><div class="table-wrap"><table><thead><tr><th>رتبه</th><th>شهر</th><th>استان</th><th>تعداد</th><th>سهم</th><th>اپراتور غالب</th></tr></thead><tbody id="cf36-city-table"></tbody></table></div></article>
 </section>`}
function telegramMarkup(){return `<section class="page cf36-page" data-page="telegram-offline">
 <article class="panel callout cf36-api-free"><div><strong>تلگرام بدون API ID و API Hash</strong><p>فایل رسمی Telegram Desktop را انتخاب کنید؛ ContactFlow فقط روی همین دستگاه مخاطبین را می‌خواند، نشان می‌دهد، وارد می‌کند یا VCF/CSV می‌سازد. هیچ Session و رمزی ارسال نمی‌شود.</p></div><span class="pill active">API‑FREE • OFFLINE</span></article>
 <div class="layout-2 wide-left"><article class="panel form-panel"><div class="panel-head"><div><h2>ورودی رسمی تلگرام</h2><p>result.json / HTML / VCF</p></div><span id="cf36-tg-count" class="pill queued">۰ مخاطب</span></div><label class="dropzone cf36-drop"><input id="cf36-tg-file" type="file" accept=".json,.html,.htm,.vcf"><strong>فایل Export تلگرام را انتخاب کنید</strong><span>Telegram Desktop → Settings → Advanced → Export Telegram data → Contacts</span></label><div id="cf36-tg-state" class="hint">فایل هنوز انتخاب نشده است.</div><label><span>جستجو در پیش‌نمایش</span><input id="cf36-tg-search" placeholder="نام، شماره یا username"></label><div class="button-row"><button id="cf36-tg-import" class="primary-btn" disabled>ثبت در مخاطبین</button><button id="cf36-tg-vcf" class="primary-soft" disabled>ذخیره VCF…</button><button id="cf36-tg-csv" class="ghost-btn" disabled>ذخیره CSV…</button></div></article>
 <article class="panel"><div class="panel-head"><div><h2>روش کار در Mini App</h2><p>بدون دسترسی پنهان به حساب</p></div></div><ol class="cf36-steps"><li><b>۱</b><span>در Telegram Desktop فقط Contacts را Export کنید.</span></li><li><b>۲</b><span>فایل result.json را از همین صفحه باز کنید.</span></li><li><b>۳</b><span>مخاطبین را ببینید، جستجو کنید و VCF/CSV یا ثبت محلی بگیرید.</span></li></ol><div id="cf36-runtime" class="cf36-runtime"></div></article></div>
 <article class="panel"><div class="panel-head"><div><h2>مخاطبین داخل فایل تلگرام</h2><p>پیش‌نمایش ۵۰۰ ردیف اول؛ خروجی شامل همه است</p></div></div><div class="table-wrap"><table><thead><tr><th>#</th><th>نام</th><th>شماره</th><th>Username</th><th>وضعیت</th></tr></thead><tbody id="cf36-tg-table"><tr><td colspan="5">فایلی باز نشده است.</td></tr></tbody></table></div></article>
 </section>`}
function legacyMarkup(){return `<section class="page cf36-page" data-page="legacy-tools">
 <article class="cf36-hero cf36-legacy-hero"><div><span class="cf36-kicker">MOBILEGENERATE V14 • REBUILT OFFLINE</span><h2>آزمایشگاه تبدیل و پاک‌سازی</h2><p>قابلیت‌های کاربردی فایل قدیمی، بدون لایسنس، FTP و وابستگی شبکه؛ یکپارچه با مخاطبین ContactFlow.</p></div><div class="cf36-tool-count"><strong>۱۲+</strong><span>ابزار آفلاین</span></div></article>
 <div class="layout-2 wide-left"><article class="panel form-panel"><div class="panel-head"><div><h2>ورودی و تبدیل</h2><p>TXT / CSV / VCF / JSON / XLS / XLSX؛ چند فایل هم‌زمان</p></div><span id="cf36-legacy-count" class="pill queued">۰ یکتا</span></div><input id="cf36-legacy-files" type="file" multiple accept=".txt,.csv,.tsv,.vcf,.json,.xls,.xlsx"><label><span>یا متن شماره‌ها</span><textarea id="cf36-legacy-text" rows="10" dir="ltr" placeholder="Ali,09121234567&#10;Sara,09351234567"></textarea></label><div class="form-grid"><label><span>قالب شماره خروجی</span><select id="cf36-prefix-mode"><option value="plus98">+98</option><option value="0098">0098</option><option value="bare98">98</option><option value="local0">09…</option></select></label><label><span>تعداد هر VCF</span><input id="cf36-chunk-size" type="number" min="1" value="1000"></label><label><span>شهر</span><input id="cf36-legacy-city" placeholder="مثلاً Tehran یا تهران"></label><label><span>منبع</span><input id="cf36-legacy-source" value="Legacy V14"></label><label><span>پیشوند نام</span><input id="cf36-name-prefix" value="مخاطب"></label></div><div class="button-row"><button id="cf36-legacy-analyze" class="primary-btn">تحلیل و حذف تکراری</button><button id="cf36-legacy-import" class="primary-soft" disabled>ثبت در مخاطبین</button><button id="cf36-legacy-vcf" class="ghost-btn" disabled>VCF تکی/قطعه‌ای…</button><button id="cf36-legacy-csv" class="ghost-btn" disabled>CSV / Excel…</button><button id="cf36-legacy-dups" class="ghost-btn" disabled>گزارش تکراری‌ها…</button></div><div id="cf36-legacy-state" class="hint">آماده تحلیل.</div></article>
 <article class="panel"><div class="panel-head"><div><h2>ابزارهای کمکی V14</h2><p>تبدیل Unicode/Hex و تصویر Base64</p></div></div><label><span>متن یا Hex</span><textarea id="cf36-codec-input" rows="5" dir="ltr"></textarea></label><div class="button-row"><button id="cf36-to-hex" class="ghost-btn">متن → Hex</button><button id="cf36-from-hex" class="ghost-btn">Hex → متن</button><button id="cf36-copy-codec" class="ghost-btn">کپی نتیجه</button></div><textarea id="cf36-codec-output" rows="5" readonly dir="ltr"></textarea><hr><label><span>تصویر → Base64 Data URL</span><input id="cf36-image-file" type="file" accept="image/*"></label><textarea id="cf36-image-base64" rows="5" readonly dir="ltr"></textarea></article></div>
 <article class="panel"><div class="panel-head"><div><h2>گزارش پردازش</h2><p>نام، شماره، منبع و تکراری‌ها</p></div></div><div id="cf36-legacy-summary" class="metrics-grid mini"></div><div class="table-wrap"><table><thead><tr><th>#</th><th>نام</th><th>شماره</th><th>شهر</th><th>منبع</th></tr></thead><tbody id="cf36-legacy-table"><tr><td colspan="5">هنوز تحلیلی انجام نشده است.</td></tr></tbody></table></div></article>
 </section>`}
function addPages(){const main=document.querySelector('main.main');if(!main||q('cf36-city-bars'))return;main.insertAdjacentHTML('beforeend',analyticsMarkup()+telegramMarkup()+legacyMarkup())}

function addDashboardHub(){const dashboard=document.querySelector('.page[data-page="dashboard"]');if(!dashboard||q('cf36-hub'))return;const icons={telegram:'➤',whatsapp:'◉',rubika:'R',bale:'ب',soroush:'س'};const channels=Object.entries(window.ContactFlowChannelHandoff.CHANNELS).map(([key,item])=>`<button class="cf36-channel-card" data-channel="${key}"><i>${icons[key]}</i><strong>${esc(item.label)}</strong><span>صف، VCF و تحویل امن</span></button>`).join('');dashboard.querySelector('.metrics-grid')?.insertAdjacentHTML('beforebegin',`<article id="cf36-hub" class="cf36-dashboard-hub"><div><span class="cf36-kicker">CONTACT INTELLIGENCE 3.6</span><h2>هر مخاطب، یک داده قابل استفاده</h2><p>ورود اتمیک، نام‌گذاری دقیق، تلگرام بدون API و تحلیل شهری؛ همه روی همین دستگاه.</p><div class="button-row"><button class="primary-btn" data-cf36-go="smart-import">ورود و ثبت مستقیم</button><button class="primary-soft" data-cf36-go="insights">دیدن هوش شهری</button><button class="ghost-btn" data-cf36-go="telegram-offline">تلگرام بدون API</button></div></div><div class="cf36-live"><i></i><strong id="cf36-live-count">۰</strong><span>مخاطب محلی</span></div></article><article class="panel cf36-channel-hub"><div class="panel-head"><div><h2>کانال‌های ارتباطی</h2><p>تلگرام تنها گزینه نیست؛ هر پنج کانال از اینجا دیده می‌شوند.</p></div><button class="ghost-btn" data-cf36-go="channels">مرکز کامل</button></div><div class="cf36-channel-grid">${channels}</div></article>`);
  dashboard.querySelectorAll('[data-cf36-go]').forEach(button=>button.onclick=()=>window.setPage(button.dataset.cf36Go));dashboard.querySelectorAll('[data-channel]').forEach(button=>button.onclick=()=>{window.setPage('channels');setTimeout(()=>{const select=q('cf35-channel');if(select){select.value=button.dataset.channel;select.dispatchEvent(new Event('change'))}},80)})
}
function replaceCredentialPanels(){const panel=q('cf34-tg-check')?.closest('article');if(panel){panel.innerHTML='<div class="panel-head"><div><h2>تلگرام بدون API</h2><p>Checker مبتنی بر API ID/Hash از مسیر اصلی حذف شده است.</p></div><span class="pill active">OFFLINE</span></div><p class="hint">فایل رسمی Telegram Desktop را باز کنید تا مخاطبین را ببینید، جستجو کنید، در دیتابیس ثبت کنید یا VCF/CSV بگیرید.</p><button id="cf36-open-tg-from-import" class="primary-btn full-btn">باز کردن تلگرام بدون API</button>';q('cf36-open-tg-from-import').onclick=()=>window.setPage('telegram-offline')}}
function addCommandPalette(){if(q('cf36-command'))return;const actions=document.querySelector('.top-actions'),button=document.createElement('button');button.id='cf36-command';button.className='ghost-btn cf36-command-button';button.innerHTML='<span>جستجوی امکانات</span><kbd>⌘ K</kbd>';actions?.prepend(button);document.body.insertAdjacentHTML('beforeend',`<div id="cf36-palette" class="cf36-palette hidden" role="dialog" aria-modal="true"><div class="cf36-palette-card"><div class="cf36-palette-search"><span>⌕</span><input id="cf36-palette-input" placeholder="نام قابلیت را بنویسید…" autocomplete="off"><kbd>Esc</kbd></div><div id="cf36-palette-list"></div></div></div>`);const commands=[['dashboard','داشبورد'],['smart-import','Import و ثبت مستقیم'],['contacts','مخاطبین'],['rename','نام‌گذاری دقیق'],['insights','آمار و هوش شهری'],['telegram-offline','تلگرام بدون API'],['channels','واتساپ، روبیکا، بله و سروش'],['legacy-tools','جعبه‌ابزار V14'],['exports','خروجی و ذخیره با نام'],['backup','Backup آفلاین']];
  const palette=q('cf36-palette'),input=q('cf36-palette-input'),render=()=>{const term=(input.value||'').trim();q('cf36-palette-list').innerHTML=commands.filter(([,label])=>!term||label.includes(term)).map(([page,label])=>`<button data-command-page="${page}"><span>${esc(label)}</span><small>باز کردن ←</small></button>`).join('');q('cf36-palette-list').querySelectorAll('button').forEach(item=>item.onclick=()=>{palette.classList.add('hidden');window.setPage(item.dataset.commandPage)})},open=()=>{palette.classList.remove('hidden');input.value='';render();setTimeout(()=>input.focus(),20)};button.onclick=open;palette.onclick=event=>{if(event.target===palette)palette.classList.add('hidden')};input.oninput=render;document.addEventListener('keydown',event=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='k'){event.preventDefault();open()}if(event.key==='Escape')palette.classList.add('hidden')});render();
}

function normalizedLocation(row){const inferred=L.inferLocation([row.city,row.province,row.source,...(row.sourceFiles||[])].join(' '));return {city:inferred.city||row.city||'نامشخص',province:inferred.province||row.province||L.provinceForCity(row.city)||'نامشخص'}}
function countsOf(rows,keyFn){const out={};for(const row of rows){const key=keyFn(row)||'نامشخص';out[key]=(out[key]||0)+1}return out}
function topEntries(object,limit=20){return Object.entries(object).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0],'fa')).slice(0,limit)}
async function analyticsData(){const rows=await all('contacts'),cityRows=new Map();for(const row of rows){const loc=normalizedLocation(row),key=`${loc.city}\u0000${loc.province}`,entry=cityRows.get(key)||{city:loc.city,province:loc.province,count:0,operators:{}};entry.count++;const operator=row.operator||L.detectOperator(row.phone).operator;entry.operators[operator]=(entry.operators[operator]||0)+1;cityRows.set(key,entry)}const cities=[...cityRows.values()].sort((a,b)=>b.count-a.count),operators=countsOf(rows,row=>row.operator||L.detectOperator(row.phone).operator),provinces=countsOf(rows,row=>normalizedLocation(row).province),sources=countsOf(rows,row=>row.source||'نامشخص'),named=rows.filter(row=>row.name&&row.name!==row.phone).length,located=rows.filter(row=>normalizedLocation(row).city!=='نامشخص').length,operated=rows.filter(row=>(row.operator||L.detectOperator(row.phone).operator)!=='نامشخص').length,quality=rows.length?Math.round((named+located+operated)/(rows.length*3)*100):0;return {rows,cities,operators,provinces,sources,quality}}
function dominant(object){return topEntries(object,1)[0]?.[0]||'نامشخص'}
async function renderAnalytics(){
  const data=await analyticsData(),total=data.rows.length,leader=data.cities[0],top3=data.cities.slice(0,3).reduce((sum,row)=>sum+row.count,0),share=total?Math.round(top3/total*100):0,largestProvince=topEntries(data.provinces,1)[0]||['نامشخص',0];q('cf36-quality-ring').textContent=`${F.format(data.quality)}٪`;q('cf36-city-title').textContent=leader?`${leader.city} در صدر مخاطبین شماست`:'برای روشن شدن نقشه، مخاطب وارد کنید';q('cf36-city-sub').textContent=leader?`${F.format(leader.count)} شماره در ${leader.province} • ${F.format(Math.round(leader.count/total*100))}٪ کل داده`:'آمار در لحظه از دیتابیس همین دستگاه محاسبه می‌شود.';
  q('cf36-insight-metrics').innerHTML=[['کل شماره‌ها',total,'دیتابیس محلی'],['شهرهای فعال',data.cities.filter(x=>x.city!=='نامشخص').length,'تشخیص فارسی/English/Finglish'],['استان پیشرو',largestProvince[0],`${F.format(largestProvince[1])} مخاطب`],['تمرکز سه شهر اول',`${share}٪`,'شاخص تمرکز مخاطب']].map(([label,value,sub])=>`<article class="metric-card"><div class="metric-icon">◈</div><div><span>${esc(label)}</span><strong>${typeof value==='number'?F.format(value):esc(value)}</strong><small>${esc(sub)}</small></div></article>`).join('');
  const max=leader?.count||1;q('cf36-city-bars').innerHTML=data.cities.slice(0,15).map((row,index)=>`<button data-city-name="${esc(row.city)}"><b>${F.format(index+1)}</b><span>${esc(row.city)}<small>${esc(row.province)}</small></span><i><em style="width:${Math.max(2,row.count/max*100)}%"></em></i><strong>${F.format(row.count)}</strong></button>`).join('')||'<div class="empty-state compact">هنوز داده‌ای نیست.</div>';q('cf36-city-bars').querySelectorAll('button').forEach(button=>button.onclick=()=>{window.setPage('contacts');q('contact-search').value=button.dataset.cityName;state.page=1;window.refreshContacts?.()});
  const colors=['#6ee7ff','#7c5cff','#ff5fa2','#ffc857','#39e58c','#ff7a59'],operatorEntries=topEntries(data.operators,8);let cursor=0;const gradients=operatorEntries.map(([name,count],index)=>{const start=cursor,pct=total?count/total*100:0;cursor+=pct;return `${colors[index%colors.length]} ${start}% ${cursor}%`});q('cf36-operator-donut').style.background=gradients.length?`conic-gradient(${gradients.join(',')})`:'var(--panel)';q('cf36-operator-donut').innerHTML=`<span><b>${F.format(total)}</b><small>شماره</small></span>`;q('cf36-operator-legend').innerHTML=operatorEntries.map(([name,count],index)=>`<div><i style="background:${colors[index%colors.length]}"></i><span>${esc(name)}</span><strong>${F.format(count)}</strong></div>`).join('');
  const unknown=data.cities.find(x=>x.city==='نامشخص')?.count||0,signals=[leader?`بیشترین ظرفیت در <b>${esc(leader.city)}</b> با ${F.format(leader.count)} شماره است.`:'هنوز داده شهری ندارید.',share>60?`تمرکز سه شهر اول <b>${F.format(share)}٪</b> است؛ برای پوشش متعادل‌تر شهرهای بعدی را بررسی کنید.`:`پراکندگی شهری متعادل است؛ سه شهر اول ${F.format(share)}٪ داده را دارند.`,unknown?`${F.format(unknown)} شماره بدون شهر است؛ نام فایل یا ستون شهر را تکمیل کنید.`:'همه شماره‌های قابل تشخیص، برچسب شهری دارند.',`امتیاز کیفیت داده <b>${F.format(data.quality)}٪</b> است و با تکمیل نام، شهر و اپراتور بالا می‌رود.`];q('cf36-signals').innerHTML=signals.map((text,index)=>`<div><i>${index+1}</i><p>${text}</p></div>`).join('');q('cf36-province-grid').innerHTML=topEntries(data.provinces,10).map(([name,count])=>`<div><span>${esc(name)}</span><strong>${F.format(count)}</strong></div>`).join('')+`<hr><small>منابع برتر: ${topEntries(data.sources,3).map(([name,count])=>`${esc(name)} (${F.format(count)})`).join(' • ')||'—'}</small>`;renderCityTable(data,'');q('cf36-city-filter').oninput=()=>renderCityTable(data,q('cf36-city-filter').value);q('cf36-city-csv').onclick=()=>saveCityCsv(data);
}
function renderCityTable(data,filter){const term=L.text(filter).toLowerCase(),rows=data.cities.filter(row=>!term||L.text(`${row.city} ${row.province}`).toLowerCase().includes(term));q('cf36-city-count-label').textContent=`${F.format(rows.length)} شهر/گروه`;q('cf36-city-table').innerHTML=rows.slice(0,500).map((row,index)=>`<tr><td>${F.format(index+1)}</td><td><b>${esc(row.city)}</b></td><td>${esc(row.province)}</td><td>${F.format(row.count)}</td><td>${data.rows.length?F.format((row.count/data.rows.length*100).toFixed(1)):0}٪</td><td>${esc(dominant(row.operators))}</td></tr>`).join('')||'<tr><td colspan="6">نتیجه‌ای نیست.</td></tr>'}
async function saveCityCsv(data){const cell=value=>`"${String(value??'').replace(/"/g,'""')}"`,csv='\ufeffrank,city,province,count,share_percent,dominant_operator\r\n'+data.cities.map((row,index)=>[index+1,row.city,row.province,row.count,data.rows.length?(row.count/data.rows.length*100).toFixed(2):0,dominant(row.operators)].map(cell).join(',')).join('\r\n');await window.ContactFlowFileSave.save(new Blob([csv],{type:'text/csv;charset=utf-8'}),'ContactFlow_3.6_City_Intelligence.csv')}

async function repairContactData(){const policy=currentPolicy(),signature=JSON.stringify({version:VERSION,revision:'location-spacing-2',policy}),marker=await request(state.db.transaction('settings','readonly').objectStore('settings').get('cf36-data-repair'));if(marker?.value===signature)return 0;const tx=state.db.transaction('contacts','readwrite'),store=tx.objectStore('contacts');let changed=0;await new Promise((resolve,reject)=>{const cursor=store.openCursor();cursor.onsuccess=()=>{const item=cursor.result;if(!item)return resolve();const row=item.value,loc=L.inferLocation([row.city,row.province,row.source,...(row.sourceFiles||[])].join(' ')),det=L.detectOperator(row.phone);let next={...row},dirty=false;if(loc.city&&(!row.city||/[a-z]/i.test(row.city))){next.city=loc.city;dirty=true}if(loc.province&&(!row.province||/[a-z]/i.test(row.province))){next.province=loc.province;dirty=true}next.city=L.text(next.city);next.province=L.text(next.province||L.provinceForCity(next.city));const repairedName=L.repairLocationSpacing(row.name,next.city,next.province);if(repairedName&&repairedName!==row.name){next.name=repairedName;dirty=true}if(det.operator&&det.operator!=='نامشخص'&&row.operator!==det.operator){next.operator=det.operator;next.operatorPrefix=det.prefix;dirty=true}const source=sourceFor(row,det.operator);if(source&&row.source!==source&&(policy.mode==='fixed'||policy.mode==='auto')){next.originalSource=row.originalSource||row.source||'';next.source=source;dirty=true}if(dirty){next.updatedAt=Date.now();item.update(next);changed++}item.continue()};cursor.onerror=()=>reject(cursor.error)});await done(tx);const markerTx=state.db.transaction('settings','readwrite');markerTx.objectStore('settings').put({key:'cf36-data-repair',value:signature,updatedAt:Date.now()});await done(markerTx);if(changed){await rebuildStats();touchRevision()}return changed}

function renderTelegramTable(){const term=L.text(q('cf36-tg-search')?.value||'').toLowerCase(),rows=telegramRows.filter(row=>!term||L.text([row.name,row.phone,row.username].join(' ')).toLowerCase().includes(term));q('cf36-tg-table').innerHTML=rows.slice(0,500).map((row,index)=>`<tr><td>${F.format(index+1)}</td><td>${esc(row.name)}</td><td dir="ltr">${esc(row.phone)}</td><td dir="ltr">${esc(row.username||'—')}</td><td><span class="pill active">Export رسمی</span></td></tr>`).join('')||'<tr><td colspan="5">مخاطبی مطابق جستجو نیست.</td></tr>'}
async function openTelegramExport(file){if(!file)return;try{q('cf36-tg-state').textContent=`در حال خواندن ${file.name}…`;const ext=file.name.split('.').pop().toLowerCase(),content=await file.text();telegramRows=ext==='json'?T.parseJson(content):ext==='vcf'?T.parseVcf(content):T.parseHtml(content);telegramRows=telegramRows.map(row=>({...row,sourceFile:file.name}));q('cf36-tg-count').textContent=`${F.format(telegramRows.length)} مخاطب`;q('cf36-tg-state').textContent=telegramRows.length?`${F.format(telegramRows.length)} مخاطب معتبر و یکتا از ${file.name} پیدا شد.`:'شماره معتبری در فایل پیدا نشد.';['cf36-tg-import','cf36-tg-vcf','cf36-tg-csv'].forEach(id=>q(id).disabled=!telegramRows.length);renderTelegramTable()}catch(error){telegramRows=[];renderTelegramTable();notice(`خواندن Export تلگرام ناموفق: ${error.message}`,'bad',9000)}}
async function importTelegram(){const result=await storeContacts(telegramRows,{kind:'telegram-desktop',filename:'Telegram Desktop Export'});notice(`${F.format(result.added)} مخاطب جدید و ${F.format(result.updated)} مخاطب تکمیل شد.`);window.setPage('contacts')}
async function saveTelegram(format){if(!telegramRows.length)return;const content=format==='vcf'?T.toVcf(telegramRows):T.toCsv(telegramRows),type=format==='vcf'?'text/vcard;charset=utf-8':'text/csv;charset=utf-8';await window.ContactFlowFileSave.save(new Blob([content],{type}),`Telegram_Contacts_ContactFlow_3.6.${format}`)}
function runtimeInfo(){const mini=!!window.Telegram?.WebApp,android=!!window.ContactFlowAndroid,standalone=!!window.matchMedia?.('(display-mode: standalone)').matches,save=window.ContactFlowFileSave?.capabilities?.()||{};q('cf36-runtime').innerHTML=`<strong>وضعیت همین اجرا</strong><div><span>${android?'APK Android با Bridge بومی':mini?'Telegram Mini App':standalone?'اپ نصب‌شده PWA':'نسخه Web/Desktop'}</span><span>${navigator.onLine?'آنلاین؛ هسته همچنان محلی':'کاملاً آفلاین'}</span><span>${save.androidDocument||save.filePicker?'Save As بومی فعال':'ذخیره مرورگر فعال'}</span></div>`}

async function readLegacyFiles(files){const rows=[];let excel=0;for(const file of [...(files||[])]){const ext=file.name.split('.').pop().toLowerCase();if(['xls','xlsx'].includes(ext)){excel++;await window.ContactFlow34?.addFiles?.([file],{silent:true});continue}const content=await file.text();if(ext==='vcf')rows.push(...G.fromVcf(content).map(row=>({...row,sourceFile:file.name,source:q('cf36-legacy-source').value||'Legacy V14'})));else if(ext==='json')rows.push(...T.parseJson(content).map(row=>({...row,sourceFile:file.name,source:q('cf36-legacy-source').value||'Legacy V14'})));else rows.push(...G.parseText(content,{mode:q('cf36-prefix-mode').value,namePrefix:q('cf36-name-prefix').value,city:q('cf36-legacy-city').value,source:q('cf36-legacy-source').value,keepDuplicates:true}));}if(excel){notice(`${F.format(excel)} فایل Excel به Import یکپارچه اضافه شد.`);window.setPage('smart-import')}return rows}
async function analyzeLegacy(){try{const fromFiles=await readLegacyFiles(q('cf36-legacy-files').files),fromText=G.parseText(q('cf36-legacy-text').value,{mode:q('cf36-prefix-mode').value,namePrefix:q('cf36-name-prefix').value,city:q('cf36-legacy-city').value,source:q('cf36-legacy-source').value,keepDuplicates:true}),combined=[...fromFiles,...fromText],result=G.dedupe(combined);legacyRows=result.unique.map((row,index)=>({...row,name:row.name||`${q('cf36-name-prefix').value||'مخاطب'} ${index+1}`,city:q('cf36-legacy-city').value||row.city,source:q('cf36-legacy-source').value||row.source}));legacyDuplicates=result.duplicates;q('cf36-legacy-count').textContent=`${F.format(legacyRows.length)} یکتا`;q('cf36-legacy-state').textContent=`${F.format(combined.length)} ورودی • ${F.format(legacyRows.length)} یکتا • ${F.format(legacyDuplicates.length)} تکراری`;['cf36-legacy-import','cf36-legacy-vcf','cf36-legacy-csv'].forEach(id=>q(id).disabled=!legacyRows.length);q('cf36-legacy-dups').disabled=!legacyDuplicates.length;renderLegacy()}catch(error){notice(error.message,'bad',9000)}}
function renderLegacy(){q('cf36-legacy-summary').innerHTML=[['ورودی یکتا',legacyRows.length],['تکراری حذف‌شده',legacyDuplicates.length],['اپراتورها',Object.keys(countsOf(legacyRows,row=>L.detectOperator(row.phone).operator)).length]].map(([label,value])=>`<article class="metric-card"><span>${label}</span><strong>${F.format(value)}</strong></article>`).join('');q('cf36-legacy-table').innerHTML=legacyRows.slice(0,500).map((row,index)=>`<tr><td>${F.format(index+1)}</td><td>${esc(row.name)}</td><td dir="ltr">${esc(row.phone)}</td><td>${esc(row.city||'—')}</td><td>${esc(row.source||'—')}</td></tr>`).join('')||'<tr><td colspan="5">رکوردی نیست.</td></tr>'}
async function importLegacy(){const result=await storeContacts(legacyRows,{kind:'legacy-v14',filename:'Legacy Toolbox V14'});notice(`${F.format(result.total)} مخاطب از جعبه‌ابزار ثبت/تکمیل شد.`);window.setPage('contacts')}
async function saveLegacyVcf(){const size=Math.max(1,Number(q('cf36-chunk-size').value)||1000),parts=G.chunks(legacyRows,size),entries=parts.map((rows,index)=>({name:`ContactFlow_V14_${String(index+1).padStart(4,'0')}.vcf`,blob:new Blob([G.toVcf(rows)],{type:'text/vcard;charset=utf-8'}),count:rows.length}));if(entries.length===1)await window.ContactFlowFileSave.save(entries[0].blob,entries[0].name);else{const zip=await makeZip(entries);await window.ContactFlowFileSave.save(zip,`ContactFlow_V14_${entries.length}_parts.zip`)}notice(`${F.format(parts.length)} فایل VCF آماده شد.`)}
async function saveLegacyCsv(){await window.ContactFlowFileSave.save(new Blob([G.toCsv(legacyRows)],{type:'text/csv;charset=utf-8'}),'ContactFlow_V14_Converted.csv')}
async function saveDuplicateReport(){await window.ContactFlowFileSave.save(new Blob([G.toCsv(legacyDuplicates)],{type:'text/csv;charset=utf-8'}),'ContactFlow_V14_Duplicates.csv')}
function bindLegacy(){q('cf36-legacy-analyze').onclick=analyzeLegacy;q('cf36-legacy-import').onclick=()=>importLegacy().catch(error=>notice(error.message,'bad'));q('cf36-legacy-vcf').onclick=()=>saveLegacyVcf().catch(error=>notice(error.message,'bad'));q('cf36-legacy-csv').onclick=()=>saveLegacyCsv().catch(error=>notice(error.message,'bad'));q('cf36-legacy-dups').onclick=()=>saveDuplicateReport().catch(error=>notice(error.message,'bad'));q('cf36-to-hex').onclick=()=>{q('cf36-codec-output').value=G.textToHex(q('cf36-codec-input').value)};q('cf36-from-hex').onclick=()=>{try{q('cf36-codec-output').value=G.hexToText(q('cf36-codec-input').value)}catch(error){notice(error.message,'bad')}};q('cf36-copy-codec').onclick=()=>navigator.clipboard.writeText(q('cf36-codec-output').value).then(()=>notice('نتیجه کپی شد.'));q('cf36-image-file').onchange=async event=>{const file=event.target.files?.[0];if(!file)return;const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let index=0;index<bytes.length;index+=0x8000)binary+=String.fromCharCode(...bytes.subarray(index,index+0x8000));q('cf36-image-base64').value=`data:${file.type||'application/octet-stream'};base64,${btoa(binary)}`}}
function bindTelegram(){q('cf36-tg-file').onchange=event=>openTelegramExport(event.target.files?.[0]);q('cf36-tg-search').oninput=renderTelegramTable;q('cf36-tg-import').onclick=()=>importTelegram().catch(error=>notice(error.message,'bad'));q('cf36-tg-vcf').onclick=()=>saveTelegram('vcf').catch(error=>notice(error.message,'bad'));q('cf36-tg-csv').onclick=()=>saveTelegram('csv').catch(error=>notice(error.message,'bad'))}
function patchRouting(){const previous=window.setPage;if(!previous||previous.__cf36)return;const wrapped=function(page){previous(page);const target=page==='import'?'smart-import':page;document.querySelectorAll('.page').forEach(element=>element.classList.toggle('active',element.dataset.page===target));document.querySelectorAll('[data-page]').forEach(element=>element.classList.toggle('active',element.dataset.page===target));if(target==='insights')renderAnalytics().catch(error=>notice(error.message,'bad'));if(target==='telegram-offline')runtimeInfo();if(history.replaceState)history.replaceState(null,'',`#${target}`)};wrapped.__cf36=true;window.setPage=wrapped}
function updateVersion(){document.title='ContactFlow Personal Ultimate 3.6';document.body.dataset.cfVersion=VERSION;document.querySelector('meta[name="application-name"]')?.setAttribute('content','ContactFlow 3.6');document.querySelectorAll('.brand span,.setting-box code').forEach(element=>{element.textContent=element.textContent.replace(/3\.5(?:\.0)?/g,'3.6.0')});q('cf36-live-count')&&(all('contacts').then(rows=>q('cf36-live-count').textContent=F.format(rows.length)))}
function bind(){bindTelegram();bindLegacy();q('online-badge')?.addEventListener('click',runtimeInfo);window.addEventListener('contactflow:source-policy-changed',()=>repairContactData().then(changed=>notice(`${F.format(changed)} مخاطب با سیاست منبع جدید هماهنگ شد.`)).catch(error=>notice(error.message,'bad')))}
async function init(){await waitCore();addNavigation();addPages();addDashboardHub();replaceCredentialPanels();addCommandPalette();patchRouting();bind();updateVersion();const repaired=await repairContactData();if(repaired)notice(`${F.format(repaired)} مخاطب با شهر/استان/اپراتور و سیاست منبع ۳.۶ هماهنگ شد.`);const hash=location.hash.slice(1);if(['insights','telegram-offline','legacy-tools'].includes(hash))window.setPage(hash);window.ContactFlow36={VERSION,parseTelegram:T.parseJson,storeContacts,repairContactData,analytics:analyticsData,diagnostics:()=>({version:VERSION,dbVersion:6,apiFreeTelegram:true,saveAs:window.ContactFlowFileSave?.capabilities?.(),legacyTools:Object.keys(G).length,offline:navigator.serviceWorker!==undefined})};window.dispatchEvent(new CustomEvent('contactflow:3.6-ready',{detail:window.ContactFlow36.diagnostics()}))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>init().catch(error=>notice(error.message,'bad',10000)));else init().catch(error=>notice(error.message,'bad',10000));
})();
